### ISSUE TITLE
Commenting on questions at apps.owncloud.org

### ISSUE THREAD

**Issue by vgezer** [owncloud/appstore-issues#1]
Copy & Paste from developer mailing list:

We cannot comment on questions but only reply them. The write comment
link always takes it to [0] which causes the problem. (Try to comment
here [1] and it will direct you to [0] - which is wrong as the content
id is not 0 (zero))

Maybe disabling knowledge base and forum here could be better? It
seems nobody checks the questions. I tried to go through some of them
some days ago, but still there are a lot to answer.

IMO we should only make it possible to let users only comment on the
apps, but not anywhere else?

[0] http://apps.owncloud.com/comments/add.php?type=1&forumpage=-1&content=0
[1] http://apps.owncloud.com/kb/?kbid=2619

**Comment by ghost** [comment]
@wakeup 

> IMO we should only make it possible to let users only comment on the
> apps, but not anywhere else?

Probably the best solution as most questions are better placed at the forums.

Recently there are also tons of spam posts at the KB http://apps.owncloud.com/kb

**Comment by vgezer** [comment]
Yes, the best solution is forums, but maybe app related questions can be still there as the developers of the apps have direct access to their users. However, really we should close KB as there are almost nobody answering the questions :).

**Comment by vgezer** [comment]
Another thing that should be disabled:

http://apps.owncloud.com/kb

Tons of unanswered questions :(

**Comment by ghost** [comment]
@wakeup 
Maybe you should pull some one in here? This is probably not noticed by anyone in here. :-)

**Comment by karlitschek** [comment]
i saw it and will look into it :-)

**Comment by vgezer** [comment]
@karlitschek any updates here? The unanswered questions are increasing rapidly there.

**Comment by ghost** [comment]
@karlitschek 
Another bump. The KB is still full of unanswered questions and also full of spamposts like:

https://apps.owncloud.com/kb/?kbid=3287
https://apps.owncloud.com/kb/?kbid=3285
https://apps.owncloud.com/kb/?kbid=3282

Doesn't look that good from my POV if the KB is full of unanswered questions and spamposts. With the forums, the mailinglist and the bugtracker more than enough support points are provided.

**Comment by DeepDiver1975** [comment]
apps.owncloud.com is dead -> close

**Comment by PVince81** [comment]
@DeepDiver1975 close the repo ?

**Comment by DeepDiver1975** [comment]
we still need this repo for the csr
