### ISSUE TITLE
Broken images in the the app store website 

### ISSUE THREAD

**Issue by sw-devendra** [owncloud/appstore-issues#10]
Currently many images in app store website http://apps.owncloud.com/ are broken.
Please check and resolve it.

**Comment by vgezer** [comment]
Can you give an example? e.g to the page?

**Comment by sw-devendra** [comment]
I am sorry for the late response. I checked the notification late.
Actually the page looked fixed now. I saw the issue at http://apps.owncloud.com/ main page itself. None of the images was visible at the time I reported issue. 
As other websites were working fine on my PC, I doubt that it was my network issue. Probably your web server had some issue that day.
