### ISSUE TITLE
Sign certificate for bookmarks app 

### ISSUE THREAD

**Issue by ghost** [owncloud/appstore-issues#101]
Please sign this certificate, so I can sign the bookmark app under https://github.com/mondjunge/bookmarks for upload into the Marketplace for OC 10.

Thanks.

-----BEGIN CERTIFICATE REQUEST-----
MIIEWTCCAkECAQAwFDESMBAGA1UEAwwJYm9va21hcmtzMIICIjANBgkqhkiG9w0B
AQEFAAOCAg8AMIICCgKCAgEAvOAEpYKoMXpwjwggHLTmqhfv3rfGNMM4FtAyoBfZ
xbb6PFbZp4dKVmnyuqInkAeVjHHAezE5PllR6jFulzTYypOUtZ73Ob0mBJOc7y3k
NGmVS8uqpIZcMPYdUkj3S3jYG6poScvDpuqrzV89F1CdkOInwsWtbymEc8G6Rh4x
AsIGUAI/MEN85jlNv3AjNTGs3pgq+YFJ5lfGV0MyTG7D0t9Ka8aojVGa6Ze01PbH
1SK7PoCg0wirBnbHfK2vuMKtMZip6LOnqIIjUqrqMxjDcvft91ayjI0StMUnlY5K
LXta+uD24RK1jzipPfOiGb3RgKzhxqHYDapcURVWYVfSoY+amecNPQvj2nhWaGC+
ux/qTIYAIpF70ktKtFOgFPl88M4yQhG/P0kdjSA9RiNhmcBI4tR2I93Z1JB/OAat
99qr1RezphWQwEPbhZCKQNbaq3TUY1exTdVAgMnINY4Xzoe1bZJrIho241PJTavx
QRkB/UKMkF1l/XTD8vqnAagX9mCq9ByhvjJcA7rkaH2dlfGCpc2MfLYD4PeHWUzy
uG5XKU5bILw4FPG/dmbV1zwoNRDsqFzOujVx4GUpV0J9dqCWBBrko0Pk6Tee2c8E
Ies56/nQ/koXRtDZGNlS3Ie5MnKmgBoqmk12INYc99kGJPuD0FmRSXIiQO5agaRf
EM0CAwEAAaAAMA0GCSqGSIb3DQEBCwUAA4ICAQC3gNHX0cMh31f0iYvXAGnnEEVx
peXZzw60Wgg7bKTzK30RPI+XFXyVX3g9t1mj5joiMyPtCSTLYK0ZPVW5FEdlhiNu
5A9R173Atfcx/zD5xSaNg26nexMXb6IShPwWK8zNkeiygTolQnZQfpLt9vG8dipX
mzrwk/hv6F8DBaUIcVh+lGKb44bPJhuBDWgSCpyD+yS5so3aHjK+z+SKOesv8OfJ
EfQQKZItBeJS9fPgUXQXUuDzspYdBfzKLwLTk+H2VnampFLzHHZjk3X4aa2d/xhk
sbuDhAJyE/lftzSaVootXW9e1MwgJELbvuS85k82olAPzGuszy2mIV7BP37eicdB
OGEgfji6HhEd3rwTJ2JfDR14Qk1B4TftMxxO/31RyWDvw6TCBuh/HsZUhHDShNQF
6zn+D0SWwmcy29EV4I7sgvl1Q78z2jsb5mbkla+S6xjIWgXrz/7VkZtUhFLiOI3t
hVXywFFm7bFaimRFYXxO07f3FEtx+r9b6goH4s5iBB46gFadg4qebb1zmdclKrj6
z6fdFi57eP7xh2kJDYBiBZAHrsqM4EOHm1aX2SXtV59cujL1xoj8AgG4XXZElBNZ
hRx4F7o+FiILgppJz3OI+e7Hfshx7KuUR++EEjGQ+7nlq5C6iRZzcDIZnDQG4Fea
8mAwytvdjmPgmBAgKA==
-----END CERTIFICATE REQUEST-----

**Comment by DeepDiver1975** [comment]
```
-----BEGIN CERTIFICATE-----
MIIE9jCCAt4CAhA8MA0GCSqGSIb3DQEBCwUAMG0xCzAJBgNVBAYTAlVTMQ8wDQYD
VQQIDAZCb3N0b24xFjAUBgNVBAoMDW93bkNsb3VkIEluYy4xNTAzBgNVBAMMLG93
bkNsb3VkIENvZGUgU2lnbmluZyBJbnRlcm1lZGlhdGUgQXV0aG9yaXR5MB4XDTE3
MDgwNDA5NTc1MFoXDTI3MDgwMjA5NTc1MFowFDESMBAGA1UEAwwJYm9va21hcmtz
MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAvOAEpYKoMXpwjwggHLTm
qhfv3rfGNMM4FtAyoBfZxbb6PFbZp4dKVmnyuqInkAeVjHHAezE5PllR6jFulzTY
ypOUtZ73Ob0mBJOc7y3kNGmVS8uqpIZcMPYdUkj3S3jYG6poScvDpuqrzV89F1Cd
kOInwsWtbymEc8G6Rh4xAsIGUAI/MEN85jlNv3AjNTGs3pgq+YFJ5lfGV0MyTG7D
0t9Ka8aojVGa6Ze01PbH1SK7PoCg0wirBnbHfK2vuMKtMZip6LOnqIIjUqrqMxjD
cvft91ayjI0StMUnlY5KLXta+uD24RK1jzipPfOiGb3RgKzhxqHYDapcURVWYVfS
oY+amecNPQvj2nhWaGC+ux/qTIYAIpF70ktKtFOgFPl88M4yQhG/P0kdjSA9RiNh
mcBI4tR2I93Z1JB/OAat99qr1RezphWQwEPbhZCKQNbaq3TUY1exTdVAgMnINY4X
zoe1bZJrIho241PJTavxQRkB/UKMkF1l/XTD8vqnAagX9mCq9ByhvjJcA7rkaH2d
lfGCpc2MfLYD4PeHWUzyuG5XKU5bILw4FPG/dmbV1zwoNRDsqFzOujVx4GUpV0J9
dqCWBBrko0Pk6Tee2c8EIes56/nQ/koXRtDZGNlS3Ie5MnKmgBoqmk12INYc99kG
JPuD0FmRSXIiQO5agaRfEM0CAwEAATANBgkqhkiG9w0BAQsFAAOCAgEARzdTE4Q6
6sRLRZFcEjZHzXDZ+So6SFTfAkinJUy1oYVVA5rAEm84bzbIfNmWcdDmSwpU+Hxu
FiipkRV43huOuw0SpTqxTPu5rmNfD4S1OsRQQFgeWD5SFOsjiZTrg6CGUb63Qk9U
SFBNKpJQwCkDyYWn0UoZUQwkn7a0oQ9ufuQ00m8XRsMeyo3cL4EUdXK3/7g1+Fjt
HbbDduMDdLoaSO4ktDwRIbbUA6IyOMpzAIhYS2N3wqjVDwoNX1R/n/do8JcFebP0
VsR9Q9XZ1O0RQ8qONOZeQpPdt2Ywgvz1/HOWpGc4mAFWW83FSyH3mBalPwiFx8Hz
viCNeYUgQmFyrUx8LFI9ptIh8vuGgZ6QB++46nq+f+95jpJgkwo5HsWW5U0r4+7n
noyuGsxfNpyqyHAkx75zANyikgm3lWW84mXuUXUu99+JqzjmLksenT1ToQzssOKr
6H3+frQtn+EVExgujNpFAMYf+iglCB1oXGsI0pm1e4obEtYfOx3iMI/DBgPuDUCi
Hv/BNvsotar3Qthc8/RZgbGpMBlIVOzkMVT7YBuZRhLsv97T2N6z+UC95ex1OHam
5LPdjDVSmkE64Wj2COG+3l4hZL3K5A8eu9F2Gwk/4oIJS+hjTZc6pCAWD3ty83NK
gH+9ikMMRDHQpjsGk1CsvcEgDxZEGPoQMXw=
-----END CERTIFICATE-----
```
