### ISSUE TITLE
files_clipboard.csr

### ISSUE THREAD

**Issue by leizh** [owncloud/appstore-issues#102]
-----BEGIN CERTIFICATE REQUEST-----
MIIEXzCCAkcCAQAwGjEYMBYGA1UEAwwPZmlsZXNfY2xpcGJvYXJkMIICIjANBgkq
hkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAurxENQEzI4ziDumtKJeU6toEwfRpyeXP
QCdAwajLkCQAJE4nChcxLY2b7Tah54dikoak4jhuvscM3pIm2cE1dAlc6WzyeJE5
sMyF6/zehBFNwjjuOAx1e49oyL4Z2GLqTRNTDcl16dYUzWWEHB8FbfUtmgviMFRS
JoelnA2htOSMbnt6O+KbBS4Ls60X+H8PSPJVKz55K+pzH7rLG65XdEmaiEp13byu
rWJwP9v3M3j0zyfo0fajnnP13ZfQUA+neKEO824115Tim4HavwwTemgehVw0duUd
YWZUPU2sKyiYSpHEeJ5JtA5xMrSMISdlnsdKD8pXdBxEOwkI+q1RjLPHz857sdWm
v/q41rpreYpIiNhkER0ffkAqmrC+T6Ji5ZQfk8ILMsOAvHM6C/UQJjgF6jOGwNXp
jbMRW8BlGHWS3mtraOY6xQdVTG1EcMb+7aOjMpdioKk/DrgRSEbXOiBGVvBJ6Hy3
H+wcGpIsisHBE6M3zNFPkAb3uorgtl62A/0PInpxZ7x8ZXx3ZwVM1GH9AniDf21k
wtIAa5WYDBIas4II6xBvamKh4aI8QxjPXoygqklf7CFeDffEZnqt3r8rNLNZjC3/
tyfTE99DH1yj7iEPaPE3uo24meTPGFuRiRfDcnmFJjnwKWtmL0RiKJCZhpD5cj/l
9jRgcMUVgZ8CAwEAAaAAMA0GCSqGSIb3DQEBCwUAA4ICAQCDrGyE+y2OQ7IZ/QXY
khV/ldAIgjKizBIFx+EZPZFBu4OTzp2hMrb7hF/M0c63yKBByCF9OzgPKxn/uyZQ
mxqYeOqrDOKK2X2UD3natmyLZLAMonS9OQiM9Crds2eCFz6G7PPeJUVjltS2DzUu
JsX+yrdnywYH4Sk+KLLiuUVOTNONz3jP976d1vx8joQ2bgbkWe2EYFXJ2xE9PaXE
E3yoPM3pTEJeCpYOVUzxBK6i0IKpuVWikxeTL4KUH5Lkn9sZI/dmmpBRoiC616d/
VF97RZgafJdm6kbiuYDr+P51vHotmTiElM204KVdzPUE8cxA24AUP7UkAHOiNchZ
bbX6WoOSCg2b/CqM9ZarOmAPQaAhzP3+cbD8ve2/MFLzrrp/mdBEhtXPsMu/THum
/N/MwuVQ85JrbKza/oDu34TVhf4Xungw76vHK+2WTF/CLBToTYFF8O31EWT793xN
EuHZfD7cRnObF3UexXoOdMQrBzgHtoC9Z6axRa+M8AmADSrZ+fg/1PWE+Ig61nKR
SsKPCepuvjqVDHQP3iII+JerlqoWOqFIm0wPj8gYj7m044y723PK2S3JTeWNBfS8
09gH8t2dR39C1YzjoJGjxNMocnq3ugFwWmwDzf+mi1hCApb9B0WOXmjQluHMJCYe
XCKnz80dIRrj36Vyso/OtmM9Dg==
-----END CERTIFICATE REQUEST-----

**Comment by DeepDiver1975** [comment]
```
-----BEGIN CERTIFICATE-----
MIIE/DCCAuQCAhA9MA0GCSqGSIb3DQEBCwUAMG0xCzAJBgNVBAYTAlVTMQ8wDQYD
VQQIDAZCb3N0b24xFjAUBgNVBAoMDW93bkNsb3VkIEluYy4xNTAzBgNVBAMMLG93
bkNsb3VkIENvZGUgU2lnbmluZyBJbnRlcm1lZGlhdGUgQXV0aG9yaXR5MB4XDTE3
MDgwNzA3MTgyMVoXDTI3MDgwNTA3MTgyMVowGjEYMBYGA1UEAwwPZmlsZXNfY2xp
cGJvYXJkMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAurxENQEzI4zi
DumtKJeU6toEwfRpyeXPQCdAwajLkCQAJE4nChcxLY2b7Tah54dikoak4jhuvscM
3pIm2cE1dAlc6WzyeJE5sMyF6/zehBFNwjjuOAx1e49oyL4Z2GLqTRNTDcl16dYU
zWWEHB8FbfUtmgviMFRSJoelnA2htOSMbnt6O+KbBS4Ls60X+H8PSPJVKz55K+pz
H7rLG65XdEmaiEp13byurWJwP9v3M3j0zyfo0fajnnP13ZfQUA+neKEO824115Ti
m4HavwwTemgehVw0duUdYWZUPU2sKyiYSpHEeJ5JtA5xMrSMISdlnsdKD8pXdBxE
OwkI+q1RjLPHz857sdWmv/q41rpreYpIiNhkER0ffkAqmrC+T6Ji5ZQfk8ILMsOA
vHM6C/UQJjgF6jOGwNXpjbMRW8BlGHWS3mtraOY6xQdVTG1EcMb+7aOjMpdioKk/
DrgRSEbXOiBGVvBJ6Hy3H+wcGpIsisHBE6M3zNFPkAb3uorgtl62A/0PInpxZ7x8
ZXx3ZwVM1GH9AniDf21kwtIAa5WYDBIas4II6xBvamKh4aI8QxjPXoygqklf7CFe
DffEZnqt3r8rNLNZjC3/tyfTE99DH1yj7iEPaPE3uo24meTPGFuRiRfDcnmFJjnw
KWtmL0RiKJCZhpD5cj/l9jRgcMUVgZ8CAwEAATANBgkqhkiG9w0BAQsFAAOCAgEA
lwW9isr2syaf+NTf03WUheGRCIFtKAcDZjfYsHGYdC2C0eZhz7Q3hujbUdpEnYU9
3Bnacm/u1GGEecbgBrAYdvNeHIXr1HmjVUrL2gxGqbPP+g4ht5BvyvQow0F6z0Xd
ou70LAOlSYg83n5l3SGz/D3/yqQ7/lW8I62ehRNLhIIhJ1KhjF6o3kcO5iGeh+LW
q+4pBk1ZPkQs8ZaQMz9rN9PB+9VmlMJPULNmlmsLTXjBM85nxTu/D0I9F5kw4+80
GnPfzRCcVnx/dAdNeZv9zZ3Zxhx3deP4KuNVu38qsxvM7pDwQvBFRUoe5JcV7yFL
gLEiNg5ohnagTaL7wYKZwbAqDOuFvHwk6xkWWfa67xsqhYHxgyzhU7lJDaS0fgud
WInL1CTIpjd6BZmUvCOoG1duhNErBYuFycIQ2o8+TW33UxSmCxEogiZYoKfu/wYT
rDHHrO0c3ropkxBlFue4+QroQRSPJQa1S5jNVOwustQQP1L32Ld9tF72WybR/V6g
0ZoSN2nkmJWGa7WzTRM8XClvujXGmgBssKGhVKiVFwTzDbsj6PVGM5pmQXd3P7qq
HLfbYqedvT+14Fz2EK6QCckzH4k1p3oivWh1lJo3txqcm429MtlLxif1RivYtevl
gvpDHjMMXWjGyGkYTnl/H5+7bDS0XDoLkz4dFuHdnjU=
-----END CERTIFICATE-----
```
