### ISSUE TITLE
csr for PhoneTrack

### ISSUE THREAD

**Issue by julien-nc** [owncloud/appstore-issues#103]
Could you give me a certificate for my new app ?

-----BEGIN CERTIFICATE REQUEST-----
MIIEWjCCAkICAQAwFTETMBEGA1UEAwwKcGhvbmV0cmFjazCCAiIwDQYJKoZIhvcN
AQEBBQADggIPADCCAgoCggIBAL0jgsYKmU0x42Ii3TIVoQe9DT9gC8eBLubDV0JY
MJ/OmG7mZZyfsOcrCnFtzgkUlHW/nK3v0wCYofHk/P1m0Mg0JEY/WujU6JYx4/2D
UeFo0C5FUsTH04RudHvCP14cIX0KS7BTatSq62VMtRBiXZfW2RF9MCO50Kam2KXb
Gf3Gq0xGQe6aiTcfYEzC3DTRQpS8EYjuhtwVRcb+VUcpGKCtiEESb/CaJCvPxDxt
iXKRZ0RTz8SKoyykmclvhiXJ4llJB1uPLIABCrYL9vFR6OcF43puF3yGU7hLr/gj
Z7pZSzgfE6mJo5hNy3tr8SczIfEIpMv3hX8IK4QmwSR3SRNpMEgzIx8PkOafzmYw
MdecYQsr6BokcKrmCqzihf+b4SRj7rho05s+AUCbQCZNzeSa090xsJPxV+OM8Ryw
pCIqrJouVL4suwLGANt18r4TPeuyRfHN/4lUCGk3rPhNS3vvdQzuk/yLYdAJJ/VY
NimaJCk/1exSYMI3oUYhjAlT642H6e6Ky1Li6iIhzn16R1onNNNg0nWhXZErKanB
/4DSfSklj2FYhQnXO8GH7Vtucs+s1vfHYZyQqKIPPwKttKVGSR7XkRRdjKNBRMoq
ER0uNSvoU6I80x3AIZE6ZCA2Nq0vmq6JRL7yeLGiSlKCaT7EtpGLLOQPnIH/o920
qBw/AgMBAAGgADANBgkqhkiG9w0BAQsFAAOCAgEAeu8aKoVLud2hN6u190MehXWd
S4SomBMRZVY1kfAdyiMQInrUCLGkYSRh0tD+SEsrJ1HmZO5QCNg3VXzameMoA45E
Kyo6in542A+yE2Agn4We316R2Yatj0wnLqnzzrpQZuGmeB6cG4uHIKKNOI/nQpge
YOKfLSDmxpCBnWuq18TCM+tLlqYrn9teih6zbB0dEGw+0aOin3sFp2/14iQ4nAL7
cZ9hErBi8N/SdQXLRdoDiMCAPh71uWbbWuwTsr50OlPurTFCTtig0f0uhn7E50sA
FNUOKukrA7KTQY7cA2WW73PQDExLhGx3eRWpk2yq5CqYrUln5zAAMpMkc1HTBRrX
FZrd0XC14xJMusCrAOIS45deA06DPKIzjWMuMjbVr8f2NK4NfXbG3qAlrNAghGZ5
lIeNbAN2za4LqatONmISZqNLu4+w0G0a7knMefqWEuha3glSvXdqOepWJUTWTs3x
o476oejb4cl1pvm34wX7tLJJHLGw7y1Q29lrt9BbsPeYoHUs/P0FDsBAzcOYiUFf
pV7+xDu/jTF+2sD+A8V/Imb5IQXWzcIAIKB2RYvH3s1xW21IW6FuVWhQ0w4r5BDa
sIHc+4UC3yCxGYo1cdzpOkZ4emGBTQ1AxKWrk13v1BJl43fUddxyiRoFOYaUTk6G
q/EdpTc2cRbvq5Q5yFA=
-----END CERTIFICATE REQUEST-----

Here is the repo : https://gitlab.com/eneiluj/phonetrack-oc

**Comment by DeepDiver1975** [comment]
```
-----BEGIN CERTIFICATE-----
MIIE9zCCAt8CAhA/MA0GCSqGSIb3DQEBCwUAMG0xCzAJBgNVBAYTAlVTMQ8wDQYD
VQQIDAZCb3N0b24xFjAUBgNVBAoMDW93bkNsb3VkIEluYy4xNTAzBgNVBAMMLG93
bkNsb3VkIENvZGUgU2lnbmluZyBJbnRlcm1lZGlhdGUgQXV0aG9yaXR5MB4XDTE3
MDgyODIyMTI0MVoXDTI3MDgyNjIyMTI0MVowFTETMBEGA1UEAwwKcGhvbmV0cmFj
azCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAL0jgsYKmU0x42Ii3TIV
oQe9DT9gC8eBLubDV0JYMJ/OmG7mZZyfsOcrCnFtzgkUlHW/nK3v0wCYofHk/P1m
0Mg0JEY/WujU6JYx4/2DUeFo0C5FUsTH04RudHvCP14cIX0KS7BTatSq62VMtRBi
XZfW2RF9MCO50Kam2KXbGf3Gq0xGQe6aiTcfYEzC3DTRQpS8EYjuhtwVRcb+VUcp
GKCtiEESb/CaJCvPxDxtiXKRZ0RTz8SKoyykmclvhiXJ4llJB1uPLIABCrYL9vFR
6OcF43puF3yGU7hLr/gjZ7pZSzgfE6mJo5hNy3tr8SczIfEIpMv3hX8IK4QmwSR3
SRNpMEgzIx8PkOafzmYwMdecYQsr6BokcKrmCqzihf+b4SRj7rho05s+AUCbQCZN
zeSa090xsJPxV+OM8RywpCIqrJouVL4suwLGANt18r4TPeuyRfHN/4lUCGk3rPhN
S3vvdQzuk/yLYdAJJ/VYNimaJCk/1exSYMI3oUYhjAlT642H6e6Ky1Li6iIhzn16
R1onNNNg0nWhXZErKanB/4DSfSklj2FYhQnXO8GH7Vtucs+s1vfHYZyQqKIPPwKt
tKVGSR7XkRRdjKNBRMoqER0uNSvoU6I80x3AIZE6ZCA2Nq0vmq6JRL7yeLGiSlKC
aT7EtpGLLOQPnIH/o920qBw/AgMBAAEwDQYJKoZIhvcNAQELBQADggIBAAPXg0zr
HdcQ9QVOlLdsY1DcMUvDK+tQEHHB2EkbiQmft9gq+DICAWXdLXd7GfX2FPIXmXIi
ivAGFYLwvtHJFQEOCkdru3/lOGdsRrBQktG7NjTbfHrbdikhPy1W9gD/Pj2+NuyD
tNpsRP+5LgFBCd5JCu3pBO8dAJZkaigqNqE6s69aQK+x0p8W8MdmCaYjijNkWxbk
uNkH8Xn0AxvF0jFGBHuRoZUVZL5yL4XyqbX0l4lM7n+oMiPZMlC7/jZuaEAGswjI
ZwOs/6+q3FBEd386cOD3tfV83gP54S8cz+XvklZ5T5FbgXgReSzK6FI7X7AHDf4F
nbaJO35kXEDLq7q4EaVjOgQczA51IfDo5s1D+jZkveB9Lo6tY8lhoHDimoVcKiuQ
d4eQwN2AKKdUMtGogtrGB8gei4PHJjvAso4mKClw1Rne0P+2oMLap+IOxmdUUdDw
CS/XrIDuc4/s0PLuE17wdALrMxxbRIv0pq1LEnBVX8q6Z+fab56+5BIkXqa1YAIY
M2qEnxBQNZi3xdz9blgVtcSz2j/VIuQ33ImqIcDJ9lc9/zq3Xep2OkQ9f1uQIAYv
Dyq0eu23qMGIg33XP7IksinxW5KiidLrZuToh1aUxB6ccdkbNFJXpH0qe6wlUXoV
Yv4XZqo+3xlcNUHFprCuFHhO7uz4ap1lG/E0
-----END CERTIFICATE-----
```
