### ISSUE TITLE
CSR for my own theme

### ISSUE THREAD

**Issue by svengit** [owncloud/appstore-issues#105]
`-----BEGIN CERTIFICATE REQUEST-----
MIIEWTCCAkECAQAwFDESMBAGA1UEAwwJb3duLXRoZW1lMIICIjANBgkqhkiG9w0B
AQEFAAOCAg8AMIICCgKCAgEA8RqzeMweYFr5QkytvKoc19uLdcZdeAgRDozpkFb/
6JOvwpxT/KnaNvu2Tl+H6nAjbSbtBqi4P19Af+j1g82YhSDNMU7h4vkNQe0/n+bc
BQjKnkXcF/xV59LXQ5v0b8tUq5JnW2SI8Ijm7Ees/KIcugfbNLUHV4hYUlESioG2
AH09ZifiRJVL4MmyaIjPWhCLjpYdfnNjiStcP9dtQQVfR51UTG3vxCbzaSy9IHtv
SoStvxLf+00TxfgUXoPH4xJ11251GwQVULw88rOsGIqOpPV5j4DzWSPIhKy1HRr6
TQ/Alrx1frSc3gllkNyx48RogH6DWAwsI9j37LmRGngF5TlihdFnuhCmPidJ5Lh/
gs5LT0edx+/y6DHXYtEe/7VVZ5wICrlDsyWOZziLf3aAGUcQ+kRWKd5PgoNsYc7T
psdfL9gyrvoQeM9li3Fr8Xz0AmibBOx8/vjkunET44OrN4P3BTA6WEPU0/QFAU89
bBJy32iWQePgAUrezQdMXv3tN2ZOh1jRJPyioBMXKEHeGGTqxPLnRVzY+Gr5V/Kq
qeoLBTORIfpT5tB0EoDdChzmpi9m8Z99x0M8XCZUTbZaQGDDC88XcOBvrBlh3kFx
Ek982Es1gzjh/aspPP/vuYyOrMAVw9tZLC3d8zBATftxAuV476Tp5dSofjHidreO
mssCAwEAAaAAMA0GCSqGSIb3DQEBCwUAA4ICAQCIOLgCjVnTnDaFvyfq2dkiQhT1
sWI961tmN/nL5TBm6g0Fpi/QZ5b15ZuroisWNIrUTJDWISbpUz8dVDvMo3t/Ie5G
UX/Fj6R97SoGh6wpyc7HxKMJzIYRMfgVUUuaw8Ry53+Bz5umFD2Rwwyh8QwfcnYY
c23/YuHqY+VQK9IcEl+l2vOh4iPj1PdGL3Ob7/dGL1KAFTyIDgCnVhCo+GShUKaQ
SEEA86vYEZpTsYcJmPM7bYFxW9OxIYwBWpyAyHjmO5p+2yl7JbL37xpD3xalpq8h
iNMIeY+wfVWo2jVnPcwe4BY91MkfrQNfyJtojElIfkAxR0OIypJFcMg4KJFr+0++
cdwIeOkCujdghbbGsRTwsk5t8bqNkLYrwq/mRANe03z4DtzA2qVC15Y05PRALfRX
/Lt7jb2K9I73G66UM8mbUTBcyzifH3JN8fJ/cwA0wdh0SwAHtzpnSRjHn/ipcTuS
ycUVzgvG5Debkv4T7TJ1Gl0qoAQAN0g73Gn1N0knzkNJtmRwJys1jztfcEdC3Mxm
roTpYFOi6RYzUEIg65piNcZFWpsyOm40sSg3H70FwR0vTGB6QK8PwJmg2W+zA95a
Xg5Z9aBl9v9bDJY1oSqzn4sfkMfwWNdOCcGbSJnZHqKxC5ixFFAJFQOAkFtL9LrJ
QVgcB6paFJ1ji5G14Q==
-----END CERTIFICATE REQUEST-----`

**Comment by DeepDiver1975** [comment]
Do you want to distribute your theme to others via the Marketplace?
In Case it is only for your own use: just remove Signature..json from your theme

**Comment by svengit** [comment]
I do not want to distribute the themes to others. I want to get rid of the error/warning in the header. As long as I get this warning I'll have to ignore it, which will mean I will miss real warnings when somebody tampered with files.

**Comment by DeepDiver1975** [comment]
so just delete the signature file from your app

**Comment by svengit** [comment]
Then I'll get an error about a missing signature.json, which also hides any real tampering, thus making the whole verification process completely useless.
Also, closing this issue before it is really resolved isn't really helping

**Comment by DeepDiver1975** [comment]
Then we need to have a Closer look.
From my understanding this is supposed to be the  solution

**Comment by svengit** [comment]
Hi,

thanks for reopening the thread. After browsing the oc bugtracker for issues on the integrity check and giving it some thought, I came to the conclusion that code signing is rather useless and ridiculous as a safety measure for non-binary code. An attacker will simply alter the files doing the integrity check and no one will ever know about it as long as no proper integrity checker like aide is employed. Thus I will set `'integrity.check.disabled' => true,` in my configuration and simply avoid the issue.
Sorry for any trouble.

**Comment by DeepDiver1975** [comment]
> An attacker will simply alter the files doing the integrity check and no one will ever know about it as long as no proper integrity checker like aide is employed.

Who did you come to that conclusion? Hashes in signature.json are signed with the app key.
Only the original developer can change the hash and resign the app.

This perfectly fulfills the requirements we have with this regards.

**Comment by svengit** [comment]
If the only requirement is to guard against a compromised Marketplace, then I agree. But then we are back at the point where you need to be able to make exceptions as an admin, so that your local changes do not trigger the warnings and hide the **real** violations.

**Comment by DeepDiver1975** [comment]
The second scenario with which we want to protect us is that either upgrades have been done wrong or that people apply patches which break the system.

Nevertheless - own themes are for sure be taken out of this for the obvious reasons.

**Comment by svengit** [comment]
For both those cases unsigned checksums would be sufficient

**Comment by DeepDiver1975** [comment]
> For both those scenarios unsigned checksums would be sufficient

could be a solution as well - thx - feel free to join the discussion at https://github.com/owncloud/core/issues/29094
