### ISSUE TITLE
CSR for Private Theme

### ISSUE THREAD

**Issue by WalshCollege** [owncloud/appstore-issues#109]
Application is called theme-walsh.

[contacts.zip](https://github.com/owncloud/appstore-issues/files/1411320/contacts.zip)

**Comment by WalshCollege** [comment]
Would you prefer that I just put the CSR in a comment?

**Comment by DeepDiver1975** [comment]
Generally speaking there is no need for signing your private theme. See https://github.com/owncloud/appstore-issues/issues/105#issuecomment-331486098

**Comment by WalshCollege** [comment]
Sorry, saw a recommendation from your site to request a cert for private themes in addition to getting a warning for a missing signature.json file. Since the request was made, it seems the public repo was fixed and now it's not required. Re-scanned and all checks passed.
Thanks.
