### ISSUE TITLE
Default page should show highest rated apps instead of latest

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/appstore-issues#11]
Currently when you open http://apps.owncloud.com, you see the latest submitted apps. This doesn’t give a very good image of what’s available for ownCloud.

We should make the default page show the highest rated apps, as in http://apps.owncloud.com/index.php?xsortmode=high

@karlitschek can you change that?

**Comment by jancborchardt** [comment]
@karlitschek can you change this?

**Comment by karlitschek** [comment]
I have to think about it. The concept of showing the newest files on the homepage worked on this websites for over 12 years.
But I will look into that.

**Comment by jancborchardt** [comment]
You know that "it's been done like that all along" is not a very valid argument. ;) Especially when it's 12 years old.

Every time I open the appstore I cringe because people basically get a random choice of apps, only based on if their dev recently checked the "updated" box.

I get that for us it's cool to see quickly which new apps are there, but we are not the people this site is (or should be) targeted towards.

Especially people new to ownCloud should be presented with the best apps there are. Much like the "Recommended" tag we use.

Just look at any other app store: It's based on popularity metrica like rating and downloads, and oftentimes some manual "getting featured" on top of that.

**Comment by oparoz** [comment]
I agree, the top apps should be shown first, emphasizing the quality of apps. It's easy to get the latest apps via a button.

**Comment by ChristophWurst** [comment]
Good call! Any progress on this?

**Comment by DeepDiver1975** [comment]
appstore is dead - long live the marketplace!
For suggestion please head over to https://github.com/owncloud/marketplace-issues/
