### ISSUE TITLE
appvncsfae CSR

### ISSUE THREAD

**Issue by stefansaenger** [owncloud/appstore-issues#110]
CSR for https://apps.owncloud.com/content/show.php/appVNCsafe+for+Zimbra?content=155100
sources available at https://github.com/vnc-biz/appvncsafe

`-----BEGIN CERTIFICATE REQUEST-----
MIIEWjCCAkICAQAwFTETMBEGA1UEAwwKYXBwdm5jc2FmZTCCAiIwDQYJKoZIhvcN
AQEBBQADggIPADCCAgoCggIBAKZ1Nzh5JRhbqKAT25Re+MEn2KovzeZ3fl1ZgVzt
5UYFIgb2RLYe1GuN9AENL0f1wvIGAcxEkZUZxiw3+geYcjOfe6n7bmFzEJu36jah
7HExPmO6G+GPljcJueN3Y2tUZvFh6KrGrfcLNciZU5QBY+IPJZGMO3lOKv8dG0rb
PBz5OSSY5udjlF5y+zwCPoJFyEFHxo+Zmaa0FzhhUGhiOWNj6ODQDI8U1x+SXtZn
pTJETvCH8KavHrRmnhNc599e0V7RGFl8RBZmbw47dCJzB0+JsTv2cat/6ZYlt7bl
rsYcbNvjF4k3ZX3mhTAJ7QFQHAoVsHP8jGQUFvQ9vF5tciwRfwNYLWhAcNA+wTxB
ffUjoQK8w0g/CuChG801i7rQibfkI/BfcnY88r8eyxFRA2NVtd5zc0ObcwZ+ga3T
/CcSyLvYd1TM2Z02iserQpOh+grrd3BC9n/ZkefFnMFkXd104v3EYp+DbikvQs3u
ixXdjW6GB73HSr3bPA3ghQ7fRA73KZWzFzX8za+euDEXl7UyFa9gmIB+aXDymZ4y
k7TibG/pocOaZCgJL/zPW8NQofTWEf4ouCsGeKIUUJXo0I6TjyUvckdd2MLWptZ0
EQFTT6bi+IsnUFW4F+xPojV14Gjs9ELwkEXWHgcHeWE3OJT+EbmAStRZea16z/9p
x6ATAgMBAAGgADANBgkqhkiG9w0BAQsFAAOCAgEAZpNO5OsgDoQGLurBO+nKhpGv
I7+okjSe02UiUuVLPFGKstyEzXtcmM9jx31I/2NyuqDRQpL6lQa6zU2PTw/LCPaT
jYa/OzgRm3bxf4RqLVd2cAcpKHEeJ8J+XUugehKHhD3nSejckP1EeER9TW2QwzBF
B4lE59ppLhhI8UZpjUFza+nJyhI4aCcwdaBp+QvsbOsgieh6l/KxidAovrmrWjxd
qKLjRNQm4bGsuTeNK6LX99IHdrlYvM8u6ro7NxNIDo2m+eQdkZvQEit18COtEaxS
tBy/TcOGMjH6hLXshuc3U+wzhMrzaExM0iYsvV9cRt9e5rEQ8wWfkXnz/IAnBD1/
1B1aLf4e5r17tsZ2tLHCSyeqygPQ1wACygYFLr3Rqk8dch2xI8L/a1CI0i/APdxW
U7JZT6AqL7/VSY4/WVdCfXdx/XX5IcN2trB5xtU7WxFGBN90RM82XMgqUD4jOoZn
hkjBcg0c6DKSGby5p5/HbhnkdE9QSt+ZP1iT/OEVKDeobNOH76J/A9aA2aJv9cYW
vctJ14R6u9e+QEDt9ushi0HmkDn3u60MxQSSMcw3dSXW2Om9uo0nDy0fYkB5NqXk
kaL+ZTz3xxW2Bar1e4oz81Mb4Yw2u9g/CFluzliwqeiyGTSW27outBMZLHeOBV5b
mlQbVfXx/8KZBkRAKT4=
-----END CERTIFICATE REQUEST-----
`
also attached as zip
[appvncsafe.csr.zip](https://github.com/owncloud/appstore-issues/files/1426160/appvncsafe.csr.zip)

**Comment by DeepDiver1975** [comment]
```
-----BEGIN CERTIFICATE-----
MIIE9zCCAt8CAhBGMA0GCSqGSIb3DQEBCwUAMG0xCzAJBgNVBAYTAlVTMQ8wDQYD
VQQIDAZCb3N0b24xFjAUBgNVBAoMDW93bkNsb3VkIEluYy4xNTAzBgNVBAMMLG93
bkNsb3VkIENvZGUgU2lnbmluZyBJbnRlcm1lZGlhdGUgQXV0aG9yaXR5MB4XDTE3
MTAzMDA4MDIxMVoXDTI3MTAyODA4MDIxMVowFTETMBEGA1UEAwwKYXBwdm5jc2Fm
ZTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAKZ1Nzh5JRhbqKAT25Re
+MEn2KovzeZ3fl1ZgVzt5UYFIgb2RLYe1GuN9AENL0f1wvIGAcxEkZUZxiw3+geY
cjOfe6n7bmFzEJu36jah7HExPmO6G+GPljcJueN3Y2tUZvFh6KrGrfcLNciZU5QB
Y+IPJZGMO3lOKv8dG0rbPBz5OSSY5udjlF5y+zwCPoJFyEFHxo+Zmaa0FzhhUGhi
OWNj6ODQDI8U1x+SXtZnpTJETvCH8KavHrRmnhNc599e0V7RGFl8RBZmbw47dCJz
B0+JsTv2cat/6ZYlt7blrsYcbNvjF4k3ZX3mhTAJ7QFQHAoVsHP8jGQUFvQ9vF5t
ciwRfwNYLWhAcNA+wTxBffUjoQK8w0g/CuChG801i7rQibfkI/BfcnY88r8eyxFR
A2NVtd5zc0ObcwZ+ga3T/CcSyLvYd1TM2Z02iserQpOh+grrd3BC9n/ZkefFnMFk
Xd104v3EYp+DbikvQs3uixXdjW6GB73HSr3bPA3ghQ7fRA73KZWzFzX8za+euDEX
l7UyFa9gmIB+aXDymZ4yk7TibG/pocOaZCgJL/zPW8NQofTWEf4ouCsGeKIUUJXo
0I6TjyUvckdd2MLWptZ0EQFTT6bi+IsnUFW4F+xPojV14Gjs9ELwkEXWHgcHeWE3
OJT+EbmAStRZea16z/9px6ATAgMBAAEwDQYJKoZIhvcNAQELBQADggIBAKwInPzF
FQeQ/RoJXZBcLkwMzf1IyJc307EcksYEBNm9g1guZzbWwN4zITrVhIbhQhIY+ybZ
vjRb6qBQUfL3INpQ4fHSdOAzGAVduMYUcoEmJgjXqYuPlWuqMHd2ZTlaDINcFCBm
Pt7nrRzXQqBHIEa37DqMXLHwNPIlgpGRpjhdPn+tJuCC57vhLJ7queJCYxCQv66u
icZjGuqdVQWqMBaWowQxoBkKk5opb42L2eJwnnovRWajAqN+l6s25fjO3ml27HbM
KqcdbhaR9TCIDMoyczftkfX8Tyeny7/dWRuBSq3uCiCLzML1F+CkUQf0Li/pyqLN
lH5QMExBVRCSc8+Ol9MOqknNyTQAuwD55SADfbF3rO5CrtHfCuKR1CS+iLJOYj3H
+ICTWQ6uUuGt3BSghXvLMlyAe1Na7VtrczVUNKyixn/92TiLcdCEce/VYhS7reZz
OD9J2FYLUY/277Ai8igbAxvKStxrH5Qz067p54y74C7+UdCs6No0sBqsqtMhInI6
GWehIbQ4hS0CdQd1vPLc25Q4ArOztifM9y06FaC8tCN7x1GU2MSJOAuoqZpTMKyR
YmWDli2USI0h5bfgcSCnSktrjiaHTiHYMyzc3H23Zq4Q481qIKGVZqtcM4Tc42UG
WdIt3o1y25hyWlk7AmnO93i28fv1SOFk4oLU
-----END CERTIFICATE-----
```
