### ISSUE TITLE
CSR twofactor_backup_codes

### ISSUE THREAD

**Issue by karakayasemi** [owncloud/appstore-issues#111]
-----BEGIN CERTIFICATE REQUEST-----
MIIEZjCCAk4CAQAwITEfMB0GA1UEAwwWdHdvZmFjdG9yX2JhY2t1cF9jb2RlczCC
AiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAMdm+eKPA3UwAE3aDQMt3OJI
v2vEswy7W/qWZwDZRjAov4OFcsPHnIwBGhnT4+Yas2L4FPnNAWg+jD0ysaHJLydH
2IRkUNWkiRJa7qyGjnZ3YERgyfDbCtbbqjh9HMCUKubJqyT4Q6I2593qeef+C9hf
MRkXC54xUjaFCUrRsErgKGbgZPtZ5vn0MJst28kkRQ8Wi2DwBXbPf6wMPSCF9rhY
ERN4XOAxE+NltPQhZ7AVE6HPxbHCV/MoRN9f4fFJd5lqiTjY6dkPW1uMvooPHN6o
CH9waFFjKfGhC2DQ0ntB993mKBupf1AcMroUa53za9x0irrHQmjiGes5dTPSGQrH
aIUPemk/6iJRkthyY1IOP1hdyA6vm0P2o6ngs9oj8K72H86a517YvIS20MMBRpU5
tHlsUOZGigfvx/FO3qfVtn+C3IfwkzTUPuzcqdFojdnqmXZf28Kpyn+d0k3a4TRB
exqu2nVu75Bke+ae5mydO9TjZZHGUlSwFGjVs3s2U7W7VoVe7/2AmW4r22qtZOu5
A30wffRHag+oDDEVayRdTwpUef6pzjV+WUejbgePTOO9PqV4nBH8eeePVdNEM0NT
uQbs9+CN8aiHTgKzJL6/bQBy2iLjIjwDkMWhPtw/OJ96HSOEDSLzOkC5Virzt/wx
Q0JhDd58TOUFsjqIT+aFAgMBAAGgADANBgkqhkiG9w0BAQsFAAOCAgEAOX6SM7BN
Cae8iHUWIRu/C/owdn/GJuDlGeZygvMEWaghu5To+UyQuiK7HWNhmBjodiRFKKLS
ZWxY98FARACXWhuAV65qc3ce4nW9quSWjBl3M1CO4865FYNyX2Z4fj+dmnCcJfg/
vZ5EDrt0y3qX9y1JxjG5so0qyydEuEtOgKxDA7oyzFC//5+WkI3g48nHy5P6V6ON
1jSZevjYa/urd4Vm3HjJM6r+r8ttrjReRm4XsD0wL4EaPV5yCmlCbzrsqokfef4l
xKoivytg/hSO0aV0E3PxCv3dThtQ2n01cA4Oh0f4HR//tT6ZqPdq6ONG0mz/o538
+lWoOJ79xwUimj0onhC60j5lIu3jsBkCh3KSd9MWaSCzs4ozTDlHtPoZrkm7kDNw
9/AVjHqXTZG3apNHm9dhDarQlzh2fyzuRTnQOiiDdOxPclmSIaabPS3VKR9I4ZbC
WhiZ6cRvd5/t1H6QI33+hTcQY7FVpdLWJCv/oBfJ2W9GjNFUUeCrlveG14MzhE0/
U+ogX2FEXtDlb3eQAvl5dxuWtwOBplDuAAPQV0nyXzKz2nunUXK6Xcyhhg5Uepts
cJT0WLRWue0icmIHgPSso0bPtrgnj//1cuMQ1vR20nhHa1ltd6j8R9qVPfR5HhQH
EJ5WOeuIT4WzXWg8nOZa1TxAeo0SOQ0Wwkk=
-----END CERTIFICATE REQUEST-----

Thanks.

**Comment by DeepDiver1975** [comment]
```
-----BEGIN CERTIFICATE-----
MIIFAzCCAusCAhBKMA0GCSqGSIb3DQEBCwUAMG0xCzAJBgNVBAYTAlVTMQ8wDQYD
VQQIDAZCb3N0b24xFjAUBgNVBAoMDW93bkNsb3VkIEluYy4xNTAzBgNVBAMMLG93
bkNsb3VkIENvZGUgU2lnbmluZyBJbnRlcm1lZGlhdGUgQXV0aG9yaXR5MB4XDTE3
MTEyMjA3MzE1MVoXDTI3MTEyMDA3MzE1MVowITEfMB0GA1UEAwwWdHdvZmFjdG9y
X2JhY2t1cF9jb2RlczCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAMdm
+eKPA3UwAE3aDQMt3OJIv2vEswy7W/qWZwDZRjAov4OFcsPHnIwBGhnT4+Yas2L4
FPnNAWg+jD0ysaHJLydH2IRkUNWkiRJa7qyGjnZ3YERgyfDbCtbbqjh9HMCUKubJ
qyT4Q6I2593qeef+C9hfMRkXC54xUjaFCUrRsErgKGbgZPtZ5vn0MJst28kkRQ8W
i2DwBXbPf6wMPSCF9rhYERN4XOAxE+NltPQhZ7AVE6HPxbHCV/MoRN9f4fFJd5lq
iTjY6dkPW1uMvooPHN6oCH9waFFjKfGhC2DQ0ntB993mKBupf1AcMroUa53za9x0
irrHQmjiGes5dTPSGQrHaIUPemk/6iJRkthyY1IOP1hdyA6vm0P2o6ngs9oj8K72
H86a517YvIS20MMBRpU5tHlsUOZGigfvx/FO3qfVtn+C3IfwkzTUPuzcqdFojdnq
mXZf28Kpyn+d0k3a4TRBexqu2nVu75Bke+ae5mydO9TjZZHGUlSwFGjVs3s2U7W7
VoVe7/2AmW4r22qtZOu5A30wffRHag+oDDEVayRdTwpUef6pzjV+WUejbgePTOO9
PqV4nBH8eeePVdNEM0NTuQbs9+CN8aiHTgKzJL6/bQBy2iLjIjwDkMWhPtw/OJ96
HSOEDSLzOkC5Virzt/wxQ0JhDd58TOUFsjqIT+aFAgMBAAEwDQYJKoZIhvcNAQEL
BQADggIBAKYZs4+oJ5knwQnJ3iRHdaFq5y1OqVAyP1xFAe+RL6rqTt3VSYj+1LWc
4DtHrI41M8Zq+piM6/o5uUlNetUpPnGAKzDRHmWrbVNNrxPsn75GQMtphlq6W8ub
udIrjx/CAeCZpXY/MbcKINX+087Df6lREJZfKmXu+KWCcfo+gpe0zFpQTPzgqCQm
zg5/NE05EzPdtDNrRXggxf9I/ItSdyPv9QTOg8JUUrDapoh4iNHy9xgAY+CKRgup
gXRc0vD4XWGTPl/esrQ+zO1dp1vDW48uHPXKThTTNWRF2L1nxx3nOMKVpYU7/AzA
kApn8rFCGHJvKQTcGwJdatm7vHzgNxrabCoW5G8gqMSHTU1uLDteAZFJra53DiE2
mXK3TXQJt3X45XJ1my5YJpqIbQwOwFF6uMTe/C3g/lgzeoxlYPl76l9w/0tmhCk6
aQLSrH0d3MtdNu69BB1JIT0sYo4VJjDVlZxBzQXDtJyHxvMP8bfMGJvwBLZGhhh6
Y4zfI/wIWcHOaUIjSaUSBaIT3kZVogIVIPhQdeJ8jfyg4dyL/E85lQAR3C/pwFdM
JAwal209iRH62gvXi6GmDEl1Qu+Iq8APdFJBoDTDA8CTjkKFFKr1o5FumPWr/TGs
mNT7DtyrrjBx4e11Z9rrUBw+1RBcDwevsP/0XQ2uy1RdGw2byLmO
-----END CERTIFICATE-----
```
