### ISSUE TITLE
CSR security

### ISSUE THREAD

**Issue by karakayasemi** [owncloud/appstore-issues#112]
-----BEGIN CERTIFICATE REQUEST-----
MIIEWDCCAkACAQAwEzERMA8GA1UEAwwIc2VjdXJpdHkwggIiMA0GCSqGSIb3DQEB
AQUAA4ICDwAwggIKAoICAQCZUH/LYB/OrCJ3yqNX/srdz/XV0aE/tNShBWbVVQXN
8BzYP8wLlFw61DWyWm/t9Mub73HTBxOIrQoBMhugdzn0ReeC2S2QoftaP0LxEV9O
s+vMIsdUOEOJu0qFWL2k6g2l7Tw5Utu4HGXBWXhVU730QXAUO6EZvV4e2MvDYWvm
fDCPVs1eWO7pnOXyEOfdgfsKpAGQsG7lkP+2BOD40dm3N4yqMdGSW9Dk9PH1L5wQ
Sa4tSRj/Cc2f/WGV/jnzY/f/kiwXHju/YeF0BDsVPRLi+gitjhyMfNvNmdtVYXLF
bl25Zs+sUXEN8VmsLDiaFd+oSU9fv9/EU9lwb4+gZHpxzA1S6G8/ZfNv2OQ6cUAr
NOzNfIA6fZWiP7v6x3A92gKHz0uOkML/Dv/p5ms9yZSP+AN2WVs5KZOiWro6CPae
G/35HX5GinlHMk8jMihgw+RCLg0vMNGjFqHanQ22Fdn99Izkziefn4L4sgVGTXuR
0fmceKgchfdW3fzArs2cFZ5TchlTokpUhANa9p0DWOwS6TzMaofUkg9rQnimq0ht
H/+N0QPZF8VsrgD4bwBqls6tfKfVClhYy2ZugeZFCr/JjvEpk5z0OfYzJMgvME6X
iG2iwaZ87fEJzeEaIUuEgz07zvQ3UQh1aK2wVU0bgseeQLHMRq2cn/qZGewZCkEJ
GwIDAQABoAAwDQYJKoZIhvcNAQELBQADggIBAFCf4vgYNV7W/K/HAiE244JIZISE
xOWVsU10ErY2/Agh8d1JkBt8jSvgm/CAFX3i49E3TUAj7460v5J725hpvI7K9U+A
NMFKjbgQFQgsyNo3oTfqbTIbojHVs3qdPYCSSp5PUT1OJSJIazrfL8rinPWqo/ww
Ttg3c7u0IWSWSukWWwswiqrmg3/x/JRkwurr4nJO9DPRqWVfGazV1EcHMQ9Gp9ii
OHl6fwUML3QEfKBzDDAUfdBh1Z9Iwzhist2SXEnpsI5bSRk29D2JxjphO3cfi9jC
08OmDs97lCJFy1BA+TKJf/Q1dM7H5PuhVGIrACymL3HGxq9QYvGywuypBSM9lhwH
psa55SXduUvzc8h76AWLqO1LdGdhHjNFtV4a0gGjL0uTVKO/bWv9fGAAEMCqXc2j
sxV8f471WfPNJ0GfeE/QnUv+DmxhM6aS/tearoffZjYTT0PN4FW/QCYh4wc3zco5
bwvUSoLR2ZFldygner7kKmCUuC5LxkZdClV1wqM8QCANflQ+jyb9udO5gSHbCy33
Dv61itmrx2htMpIpivZF+IXehPzwICzrHt/3IiUU4pkKLYUNVgMfa4sOxT1IWPMY
MD7VY0lkBYJ98EwUCad8qBE7+SAZp72QEECjHRN5+0lJnTu89vJTBNdkbsKCj+jf
wZPSVzcfzDlcxzC0
-----END CERTIFICATE REQUEST-----

Please sign owncloud/security. Thanks.

**Comment by DeepDiver1975** [comment]
```
-----BEGIN CERTIFICATE-----
MIIE9TCCAt0CAhBJMA0GCSqGSIb3DQEBCwUAMG0xCzAJBgNVBAYTAlVTMQ8wDQYD
VQQIDAZCb3N0b24xFjAUBgNVBAoMDW93bkNsb3VkIEluYy4xNTAzBgNVBAMMLG93
bkNsb3VkIENvZGUgU2lnbmluZyBJbnRlcm1lZGlhdGUgQXV0aG9yaXR5MB4XDTE3
MTEyMjA3MzEwMVoXDTI3MTEyMDA3MzEwMVowEzERMA8GA1UEAwwIc2VjdXJpdHkw
ggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQCZUH/LYB/OrCJ3yqNX/srd
z/XV0aE/tNShBWbVVQXN8BzYP8wLlFw61DWyWm/t9Mub73HTBxOIrQoBMhugdzn0
ReeC2S2QoftaP0LxEV9Os+vMIsdUOEOJu0qFWL2k6g2l7Tw5Utu4HGXBWXhVU730
QXAUO6EZvV4e2MvDYWvmfDCPVs1eWO7pnOXyEOfdgfsKpAGQsG7lkP+2BOD40dm3
N4yqMdGSW9Dk9PH1L5wQSa4tSRj/Cc2f/WGV/jnzY/f/kiwXHju/YeF0BDsVPRLi
+gitjhyMfNvNmdtVYXLFbl25Zs+sUXEN8VmsLDiaFd+oSU9fv9/EU9lwb4+gZHpx
zA1S6G8/ZfNv2OQ6cUArNOzNfIA6fZWiP7v6x3A92gKHz0uOkML/Dv/p5ms9yZSP
+AN2WVs5KZOiWro6CPaeG/35HX5GinlHMk8jMihgw+RCLg0vMNGjFqHanQ22Fdn9
9Izkziefn4L4sgVGTXuR0fmceKgchfdW3fzArs2cFZ5TchlTokpUhANa9p0DWOwS
6TzMaofUkg9rQnimq0htH/+N0QPZF8VsrgD4bwBqls6tfKfVClhYy2ZugeZFCr/J
jvEpk5z0OfYzJMgvME6XiG2iwaZ87fEJzeEaIUuEgz07zvQ3UQh1aK2wVU0bgsee
QLHMRq2cn/qZGewZCkEJGwIDAQABMA0GCSqGSIb3DQEBCwUAA4ICAQBVBIFh5OrH
LU582Yr0GZ5s9RIuW7SjbMz6HJG5czpzDwHw63M/szyma+9Dzfe026BIqyeZ6/wy
dnN4WchLbjHL+koGanH/RWeH0onJRp+L7gQO1nF+gJM03/BIsV2c7zv35TUHqXVW
CRk/38uM3B0PuuI5NoxZoQJFGD02hm2cV26XhzkqZiqwQHY55i1Ny2LvYBDT8vbR
tePpT5BWqRm4cM32K8dDiM9JTpbpbMI2BJ3H19m/kAknL9aYfOMldrZ5mHdztROR
XvFpVn52kHihNGp/VEvRE8ImjeOzlu6YFrHnWkGBk6Fr13reeh55NLjNSDi3vhjF
H6WHcKp4KHyrGe8wyElZeprySw35D4FwyduoL0dd09tGaJqgYcWloRMprOK+WNoG
sAKRdmhN4PFJTGvVRBZCSSE9R13Z2hUcq6J/1HVhDiwxGedq9dix+tJ/9IPEwfuf
3Cz2Ymd0CRUOnrmu23FGsicQk/1Djq1kOO3J3N/4YMKlgYSbac57pULjnPPhtJEg
CUDNUCDK7iwVX1JfaS4GW0/7mhaUU5Og/dm4whQD3tYlwQPVg75I/TVt5UPGJVVj
/WENsjrXSjbtq1ofwaozCPh4DoZ0SpoF6YD3PeZiXaztkUj93BXosd+2I30CfxPO
bEIipJomT3J2x0PABuaqZS1c4j90dRVPww==
-----END CERTIFICATE-----
```
