### ISSUE TITLE
Theme signing 

### ISSUE THREAD

**Issue by Karelperez** [owncloud/appstore-issues#113]
[Nordiatheme.zip](https://github.com/owncloud/appstore-issues/files/1540412/Nordiatheme.zip)

Create a new Theme For Company use and need the code signing 

Thanks

**Comment by DeepDiver1975** [comment]
the app is named NordiaTheme?

**Comment by Karelperez** [comment]
yes

**Comment by DeepDiver1975** [comment]
no need to sign themes - https://github.com/owncloud/appstore-issues/issues/136#issuecomment-423891540
