### ISSUE TITLE
xmas app signing csr

### ISSUE THREAD

**Issue by tomneedham** [owncloud/appstore-issues#114]
[xmas.csr.zip](https://github.com/owncloud/appstore-issues/files/1543107/xmas.csr.zip)

**Comment by felixboehm** [comment]
-----BEGIN CERTIFICATE-----
MIIE8TCCAtkCAhBLMA0GCSqGSIb3DQEBCwUAMG0xCzAJBgNVBAYTAlVTMQ8wDQYD
VQQIDAZCb3N0b24xFjAUBgNVBAoMDW93bkNsb3VkIEluYy4xNTAzBgNVBAMMLG93
bkNsb3VkIENvZGUgU2lnbmluZyBJbnRlcm1lZGlhdGUgQXV0aG9yaXR5MB4XDTE3
MTIwODE1NTM1OFoXDTI3MTIwNjE1NTM1OFowDzENMAsGA1UEAwwEeG1hczCCAiIw
DQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBANgxvDwN3wpQceJSjkOYHeZyh7Mh
cvwlwjhplRha3vF8Ntv9ERK6pLRSw4WAcpsX+8v0Xo3B3+tTiJAo6X4T6PJzK5xN
1XgthgyKFudlA72EnYaFtlOsR0LEiWP+K0jwHhBwWPVmmsYWP02Wk+PA78c7Uo8l
L5pN5MGb6x2zC7AravqqQEzUGEC+JhimQjrOhQDtSB+s17qdZ2XP+GnuXCrjFM3P
LH3hVnGEPmHMPtTNj4GcvRp/CMos1SR6RvT+Mz3Mhl03rtXBSXr73++QeNGB4LD/
ibyp8FoxMlZ0Q/Ua7tEBrZSnVwTjIvqs7os2HVO6jQdUtK8SX36DtDzZZLITb+B7
wMu8rvwinEz8ZkXE6ksfmGTfEbsZh18uVs8j2VtVmfC8ug/Qwak5aQ0tjxEW7EPE
ukB2paXkWqMxZIX4wsMRcvozyISyd5eUPe9XRAw4lg5FR6z2tZoIv9jIdCvl/f9n
PQK+No2As0QCRIcS0Y6Co2NKY9PSuykbTWU/FAEoFx2GkB7nbYxs4IUGM89jttZ9
xehenzQ3I11jYfE4Efvr9qkYe1kUumlqS5Y5+AZCEr8IbLwyyjhQiaDsLkqxmZDC
itoN0e/TxjWL8rwkECOieLO06Rpz6zjjuZ0LWYNLXaHOOgnTnIKvuct7Mo/UY8FC
rT/hxP33vRjBUO9PAgMBAAEwDQYJKoZIhvcNAQELBQADggIBAHw6B3YOu9ZgGbNy
O70Fw18tRHTJy94c9LWokjBfH08fUPsVCz+J7sFUD9QakitGTXZHyQdHxSR5ohmy
Vvlbxzhqn6nP9j9SxMgdU0hCXFNexOg/G5KzqI+WwHhw5ET8lFNwzhZb85Y8cQ89
t0aNeY56uOMnh1yVGjXVXxqFlASzuHUslnHAxmhBxJqzAHpMKUMXoQVCyMuWm+NA
v3nPJfQ99FJmxur/0ZLnYMYr19k5o/TzHi3dcuT76YZElzA87wNOLcGSbi9YV2S5
lzIj0jiq4YWiB6W2tLtgXnFZsUBJ3dnQyvqw9b2hTbyK51EY5209auaYvIIn7r+d
niW7bbzbDw81zGM1Fr9IMqC0f//CmiiZ9K4DSp8gzD4jf70PbrBffgJFGNXD6Qu9
n5iCJpXclm71h2BssBF49KLND+dESQRlWqP+XzqLpD1+uul3/akI0FGSPbdFu3la
zzi+jBH1R5Sne5zLl18GlqYTLBQ3R8A4/76k6l+ESJ0z2RQsxT5hdGJInT1iZsz5
NZERzCVHuFaVT38J43RPAgBCer+1flAYDvvfHrCgxJ8w/Z3EKQlG7dpq3XtGjpI7
1wNTWHKk+TOKO6y7kla92BoxkbhCk3iSWn2dQHPawWUF25cwqzWZX8YgsoPajH5q
k40l8aGJCohlq5LACQgaR8628PV1
-----END CERTIFICATE-----
