### ISSUE TITLE
files_reader CSR

### ISSUE THREAD

**Issue by Yetangitu** [owncloud/appstore-issues#118]
-----BEGIN CERTIFICATE REQUEST-----
MIIEXDCCAkQCAQAwFzEVMBMGA1UEAwwMZmlsZXNfcmVhZGVyMIICIjANBgkqhkiG
9w0BAQEFAAOCAg8AMIICCgKCAgEA2Dro3KQnJEnKeJVGnhKvrQSzLNyphcF5UNj4
j3Km6wLcb86RkWtq6uX5eR6g0HI9NFZF3qxBLUGN8bpMgGyalTLwj5IsDYO/naSZ
e/wXNCBl82vZq+jjnDCYll7r2yNjTFVzRtH+o9AIQlmMpt8+PCcw8n8QqlXUIq9A
3kb8wggczEZnw6bCudDLQWXHYKD5/tn7n06h9fA4VxfBQMyuv8hIjKEQqun3Qqvi
3DfaR52sbeDvv9bGACxWqjiE3P6sZvL7MlDqJ5KeqWoM4qPGkgDusTtXuO7h3ro2
H4NMydWXcrbUAPTXcAPo2jzTfhV8m9xQDc+45VlONjIpTFwV1oF53hnu81TlNniz
1RTbDYMkExvPYtobNjNIR+VsOQs8Gq9iEDEIxyqCm2itcuMjeFhYr1rjyeS21i6c
NtD/kMxSFwKnluQPrb49pK6g2Nq5Go1iP8WgT12hAQhri7wwH32bLe11xnD53ko6
pAzhqmciaSHLxkZCm+eyTNwJzQa0uQ+gAD8gJ7bVQUxgPSjm1amfhMAzsHIraMFq
zlz7IWjWA7vJGkR9DcweYBXsyt6ZloLekPsNxEKnuh3FgjBHEoy7iPLmDxGvTfPW
76r6vBwBF9JgIrhJzRMtTHTsYX9olblQr957SLyiZaqJ/kKCQZ3cKPhWBh1KydMj
PlXbGFUCAwEAAaAAMA0GCSqGSIb3DQEBCwUAA4ICAQARmuXW9bcPjQ2z6DsNs6Ga
fl6hIuRb/LGeYHmHR5+zVj61nee/TpS4LwGqK2XEj6mVmFK+Or/Cj1tadu/LlT6k
5KOGqFOGX70iTPDUAJEtMWu0shjcpPhxYXgXgyxZHJhD2jeWN2XSTKSYN4ZOkoY3
yd5gh4CMzKF0p9cvMuXwEY/bFzBX9YXVSWZQBAvwYydF16NNGQXTxCq57H7Osoir
BIsYjBFV6HTUldi546nLZeEwjL3mSVIU2pE20ielLeyEmm0aBYjfIrKGMLJfJ3tf
2tf6o4WIN6NOby3imJ+MxZFIVkfOUHP5XGK+QElqxrFAXoMPYYUxAkO74sVS61Et
KDGNMzcYdO3wkuSzvqK1LozeR58UKHsZ3ctTQt9KpHK80JMtle13cAZcSuf9Cc4g
yQULCUgAmc5dNty7q5zaLgzGa7HfUiudz6jiVm7APYAECHaSByhG+gO7n8XIhRbm
8b9OywgfowUOB86DZWMcwp1wFoJ/W3X/ly+3MNxu4GlqAXeqytNV8lL2kbNf5f88
rLsIhPc787qRlw5oCsZsRPYuQQEmvcPZmCxlmesNj7mY46GF+kmYoGGKGtaLNoX4
rdXSUM3sZz6oDBAuyus7O6J+fSWDtNoQF5cJ1IIpEHHPrt00kyJsOkGG/PjNljVg
xfop/qgZ8SICvUZbL83rsQ==
-----END CERTIFICATE REQUEST-----

**Comment by DeepDiver1975** [comment]
```
-----BEGIN CERTIFICATE-----
MIIE+TCCAuECAhBPMA0GCSqGSIb3DQEBCwUAMG0xCzAJBgNVBAYTAlVTMQ8wDQYD
VQQIDAZCb3N0b24xFjAUBgNVBAoMDW93bkNsb3VkIEluYy4xNTAzBgNVBAMMLG93
bkNsb3VkIENvZGUgU2lnbmluZyBJbnRlcm1lZGlhdGUgQXV0aG9yaXR5MB4XDTE4
MDExODIxMzMyNFoXDTI4MDExNjIxMzMyNFowFzEVMBMGA1UEAwwMZmlsZXNfcmVh
ZGVyMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA2Dro3KQnJEnKeJVG
nhKvrQSzLNyphcF5UNj4j3Km6wLcb86RkWtq6uX5eR6g0HI9NFZF3qxBLUGN8bpM
gGyalTLwj5IsDYO/naSZe/wXNCBl82vZq+jjnDCYll7r2yNjTFVzRtH+o9AIQlmM
pt8+PCcw8n8QqlXUIq9A3kb8wggczEZnw6bCudDLQWXHYKD5/tn7n06h9fA4VxfB
QMyuv8hIjKEQqun3Qqvi3DfaR52sbeDvv9bGACxWqjiE3P6sZvL7MlDqJ5KeqWoM
4qPGkgDusTtXuO7h3ro2H4NMydWXcrbUAPTXcAPo2jzTfhV8m9xQDc+45VlONjIp
TFwV1oF53hnu81TlNniz1RTbDYMkExvPYtobNjNIR+VsOQs8Gq9iEDEIxyqCm2it
cuMjeFhYr1rjyeS21i6cNtD/kMxSFwKnluQPrb49pK6g2Nq5Go1iP8WgT12hAQhr
i7wwH32bLe11xnD53ko6pAzhqmciaSHLxkZCm+eyTNwJzQa0uQ+gAD8gJ7bVQUxg
PSjm1amfhMAzsHIraMFqzlz7IWjWA7vJGkR9DcweYBXsyt6ZloLekPsNxEKnuh3F
gjBHEoy7iPLmDxGvTfPW76r6vBwBF9JgIrhJzRMtTHTsYX9olblQr957SLyiZaqJ
/kKCQZ3cKPhWBh1KydMjPlXbGFUCAwEAATANBgkqhkiG9w0BAQsFAAOCAgEAcYdp
toKFBZV7rswQ9yL6Y8F//VUM1J1jincG3soCz5/n5rL0TDekS0FI8eNWX0tay0ne
3/FZ93/fb+gkQf7KutU/9EWZwnc90XNq+Q3/3DWz+nIm3EFttz6GioVYz7XEAx3A
SMWeWY05ei9V7SVSnqglhouhLENrKKI8ilzGI/pEtCs3RUv3xi7GPBdCDnvqqeXy
RHrP7ZFe3v1go84v1MwQOt4/OtaYk/4HU51oxzUI8yDMNtLNmZm7gqLbT9bRsWCz
5gqFa15K4X7sVL/ECI72zEDZsF0RtmTCp9fJLoYXIPPQ1CACi0K0hB/ssE6BC9Zl
aUXcbZ2BLwvQiZmEUhyyr0WYK4D/dE4LbYqYpDDGRhXpf4cRhQahsYL8aMzZtZfl
NDE4PN/4sV6id6MnwrtDmsW3frMlkhzrsm8ftzwkbIyJD1Io5OAOJn6oxN2sjlWD
gof0tuweAlTGuAI7/CUA2yMZb45MFkLWDExzZsiVy9UtU641cDzOxAbg7UIeTBRZ
YUdl5ci1f8299Yridc4n70yQg2GHwa8YJ6p42f93sTOo0E1UAX1+eBmuAmc/eBq0
FjjmMyPZy7EhElAUa2sqw5QS2/AK34P0rccCaJerRJ0mU54neL5qSEuuPQnVcn//
3LGndYF8t5kHI3iXV3TJ2vyagUkWeDl6z9pyW0Y=
-----END CERTIFICATE-----
```
