### ISSUE TITLE
files_opds CSR

### ISSUE THREAD

**Issue by Yetangitu** [owncloud/appstore-issues#119]
-----BEGIN CERTIFICATE REQUEST-----
MIIEWjCCAkICAQAwFTETMBEGA1UEAwwKZmlsZXNfb3BkczCCAiIwDQYJKoZIhvcN
AQEBBQADggIPADCCAgoCggIBAND/ZZATXas40Gv5RSGI3iiLtjmZMREy791rlbdN
2k5Yfo2MtQePJLaaJPkrQ5uHNKTu0TkgTrAxzCV5tNVZB+UTun6+kPowjcyQN7zh
Qt2m+4wtmmRvKr//lb4wZfORjClbVKfSYjO+D/cQ+k4mgsntBqoUUUZ7D8TN7M9g
FTyK9m9reUEWZDEUdu9iuNRE3fGh7tiJnRpkYtoZPm+Rhv5S3ni2m47848L3VvAf
VBirD0OQfCWJZnxMmRkMztT5F66lnrETGE1dROxFpM8+d9HwE5r0pmPR7L3bEZ23
axwiHgJH7nBypqUtQM5foMYb/T6Rm/+Pjbq1AvcuN4wgolBXlG45nEdEjxKjsJcK
dzGipTEnpAwSYtZ1WGjh5Ph3cv2f++fIphqZ1UjohMbRJvloeiPAliITFPBUlqJj
aXowCzHko1XVyL5DBCZ38xQKIYa8A3mQQJucm2gxSP5zpW0u8VxDCSleaG7waBGD
VU+v5u3X1U9q2Bzeflk5jVjUe2rsVIXW1YyXBNLEbYkhS9+1qKuyuL58gZ/JTGVq
dJkSHQX+Pcq4RgUljzybeU38PtFYB9mNW1LBJvuwHAVBnmBpcJH7eSZuaeAez4Ta
1cJnKcXgPvrSNeYJ5iZOSFFwdVo2SWmRq7UI/LsBOThUPqKwVFHvCkQYi5G10ka+
AdAzAgMBAAGgADANBgkqhkiG9w0BAQsFAAOCAgEAs2FytNarsyiDJUyvhctov9Bx
rWZjAIXLSzfHnmP9+eCjAaseDyxi4VFYVwMbDKFwur+YapBasZU7Q+FRurbDgSWN
UsvJeVk3pAEMi33yQ+8Uqfi1Om9+1DXl3ty/b8solGjHPm87qe6xbf80BWk27TX8
mn3SK8M4VO2bVxx8Ay+ktNRr7Pphzh/4EPHtdDdJdMnk45I1RG/DUlbxhYgqg2oB
o4XQTexJrVY8RERDkJPG/3okzdV4BIxPEGqrWW3eZ39/mrqeVvT+WoFvRA9LmQaM
7/QG4qllAjoVbSoJRqwuzLMtwnluT9Y+VM40RALBlPVeuK3MubPXeMTDGtikLMjM
GKSS3s1VbAiJpc779qtwqKAPd1PDXXJAviYw2S7uGBtt4AiKAISnPA+TSc8vjZX5
hPIJTyYj9AmdWVEUWfkWy1vQWzKzH5XMfkOVpodCHoeSFDxGmyKEjELGrZtoywCn
TVzX0rWXQ68IGBB4IS3LESPUJSplpsTpd3NLDwrixnGpXKoYEqc3FBb/oLDL0q59
v1Qzhofrqo+rz1gH6of/59iE5lxTB5Qxpm9n8D4Xfhf0NC0LeaYoNHYb+Pum0rbh
BbVuR3k1VEAlx4Efkv+Z/iKvncccviI3zbAxDmwQCJI2eyNqtl6cImUXkH5DbMw3
J9AmXg9aq2HG8SlJBYo=
-----END CERTIFICATE REQUEST-----

**Comment by DeepDiver1975** [comment]
```
-----BEGIN CERTIFICATE-----
MIIE9zCCAt8CAhBOMA0GCSqGSIb3DQEBCwUAMG0xCzAJBgNVBAYTAlVTMQ8wDQYD
VQQIDAZCb3N0b24xFjAUBgNVBAoMDW93bkNsb3VkIEluYy4xNTAzBgNVBAMMLG93
bkNsb3VkIENvZGUgU2lnbmluZyBJbnRlcm1lZGlhdGUgQXV0aG9yaXR5MB4XDTE4
MDExODIxMzI0NFoXDTI4MDExNjIxMzI0NFowFTETMBEGA1UEAwwKZmlsZXNfb3Bk
czCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAND/ZZATXas40Gv5RSGI
3iiLtjmZMREy791rlbdN2k5Yfo2MtQePJLaaJPkrQ5uHNKTu0TkgTrAxzCV5tNVZ
B+UTun6+kPowjcyQN7zhQt2m+4wtmmRvKr//lb4wZfORjClbVKfSYjO+D/cQ+k4m
gsntBqoUUUZ7D8TN7M9gFTyK9m9reUEWZDEUdu9iuNRE3fGh7tiJnRpkYtoZPm+R
hv5S3ni2m47848L3VvAfVBirD0OQfCWJZnxMmRkMztT5F66lnrETGE1dROxFpM8+
d9HwE5r0pmPR7L3bEZ23axwiHgJH7nBypqUtQM5foMYb/T6Rm/+Pjbq1AvcuN4wg
olBXlG45nEdEjxKjsJcKdzGipTEnpAwSYtZ1WGjh5Ph3cv2f++fIphqZ1UjohMbR
JvloeiPAliITFPBUlqJjaXowCzHko1XVyL5DBCZ38xQKIYa8A3mQQJucm2gxSP5z
pW0u8VxDCSleaG7waBGDVU+v5u3X1U9q2Bzeflk5jVjUe2rsVIXW1YyXBNLEbYkh
S9+1qKuyuL58gZ/JTGVqdJkSHQX+Pcq4RgUljzybeU38PtFYB9mNW1LBJvuwHAVB
nmBpcJH7eSZuaeAez4Ta1cJnKcXgPvrSNeYJ5iZOSFFwdVo2SWmRq7UI/LsBOThU
PqKwVFHvCkQYi5G10ka+AdAzAgMBAAEwDQYJKoZIhvcNAQELBQADggIBALQhLQrF
sUZDJS6S95sr5kJgUIGSwxx27jbCxSCl1lMg7Nnlf9eQnfB6BNtKhmiQ7K45lwae
5rfs4L/SEv0uQVhLTM42Jkj9WmfhF8kXrhuwaYZKFg+sI2c5roY2xtHmnVWZlYnk
nMa45iI0XccSBSX4pFR/H6Wi4/cXAENG44XqmPh7+FSC0kaVy1f0VDTd87tw8cRB
enWJXn9fTh5RscM7eFeq3VdzL8baFSaJwj+vlgOTT7SpzzRdO6ujWfgGY9MrAj1C
YfP78OHgk6oO4iAbOkpDPfdXimW/uQs6UZbQKWorh8kxSNUnKOWgvVSYb6MzYYfd
Ln+/NDrHfGTTuupjbkLC8B9ZdcisOhYQ3bVN18iNQTmeTMSP3r2H1T+RyE0lWyVr
PeD1ZSV5MaYSA7IfSrUEkYHf4/VCcI8OGVdNBbkjq1LrZ4SQvNkvn0wEVgPiy5qR
S+k6GDFjlxL6cdaFRFjvfD8xvUG2aXEBBpp9lqVPdH7t5fAnlcqcN/MKHGSWlZ+n
urMpIEEi/JmVvXJO+BmZUq8RHf0YITu+qBoH69A6TPO1e4qeZdZEJBorEPr2b5OU
A5lveN6B+NxrtgQ8kV5zz9qRDzcLFeq31Iv4Puep5JGx1C6Zoac9rKfbzXu1Pd3V
6Xa9917Q9zAakEzBfKFY0c4cVKw0Z+miT0mB
-----END CERTIFICATE-----
```
