### ISSUE TITLE
HTTPS for apps.owncloud.com

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/appstore-issues#12]
http://apps.owncloud.com is only available through http – https://apps.owncloud.com breaks the stylesheets.

We should also by default redirect any http connection to https. cc @karlitschek @LukasReschke

**Comment by BernhardPosselt** [comment]
Can we fix this? This undermines the entire appstore security...

**Comment by PVince81** [comment]
![appstore-ssl](https://cloud.githubusercontent.com/assets/277525/5315604/e9e0970c-7c7f-11e4-94d3-edc03f5b20f9.png)

**Comment by danimo** [comment]
The app store should not be available via HTTP at all, i.e. http should immediately redirect to HTTPS:

Here is what's missing / what to do:
1. `static.owncloud.com` has an invalid HTTPS certificate, add the vhost to the cert
2. All CSS and JS includes in the header should drop the `http:` prefix (so the browser automatically picks the right protocol)
3. Verify that it works
4. Add redirect to HTTP vhost: `Redirect permanent / https://apps.owncloud.com/`
5. Add HSTS header to HTTPS vhost: `Header always set Strict-Transport-Security "max-age=63072000"`

**Comment by karlitschek** [comment]
fixed.

**Comment by danimo** [comment]
Thanks! Just a two more to make Google services work and the browser shut up:
- `'http://partner.googleadservices.com/gampad/google_service.js'. This request has been blocked; the content must be served over HTTPS.`
- `https://apps.owncloud.com/img/headers/header2_77_1.jpg Failed to load resource: the serve responded with a status of 404 (Not Found)`

**Comment by Wikinaut** [comment]
- proposal: fully remove the googleads thing from the OC web pages

**Comment by vgezer** [comment]
I think the search functionality does not work now.
