### ISSUE TITLE
Certificate request Signing

### ISSUE THREAD

**Issue by mindmazeCH** [owncloud/appstore-issues#124]
Hello, 

We would like to have a signing certificate to test this OpenID authentication plugin:

https://github.com/inwinstack/OpenIDConnect

And we are developing a company Theme for owncloud and would be great if we can have it for that as well.

Thanks a lot in advance.

[cs_owncloud.zip](https://github.com/owncloud/appstore-issues/files/1960384/cs_owncloud.zip)

**Comment by DeepDiver1975** [comment]
the app is named singlesignon1 ?

**Comment by DeepDiver1975** [comment]
no feedback -> close
