### ISSUE TITLE
Market place reports api.owncloud.com not reachable

### ISSUE THREAD

**Issue by abasso78** [owncloud/appstore-issues#125]
When accessing the market place in ownCloud 10.0.8 the following message is displayed:
`No marketplace connection: cURL error 7: Failed to connect to api.owncloud.com port 443: No route to host`

I checked with [https://downforeveryoneorjustme.com/api.owncloud.com](https://downforeveryoneorjustme.com/api.owncloud.com) and it is down from there too.

**Comment by DeepDiver1975** [comment]
Do you have a configuration setting named appstore url set in config.php?

**Comment by abasso78** [comment]
Yes, my config.php has the setting:
`'appstoreurl' => 'https://api.owncloud.com/v1',`

Shall I remove it or change for something else?

**Comment by DeepDiver1975** [comment]
> Shall I remove it or change for something else?

remove it please
