### ISSUE TITLE
Certificate for bookmarks app

### ISSUE THREAD

**Issue by alfredbuehler** [owncloud/appstore-issues#129]
As the previous publisher (mondjunge) has removed bookmarks from the marketplace and deleted the repo, I would like to fill the gap.  

-----BEGIN CERTIFICATE REQUEST-----
MIIEWTCCAkECAQAwFDESMBAGA1UEAwwJYm9va21hcmtzMIICIjANBgkqhkiG9w0B
AQEFAAOCAg8AMIICCgKCAgEAv9zHbpVDpgjWbHxnSzMV1cBn61UZOao+60b50P3p
mKHwU9n+r6HLglfe1r7FpIFYf9jXK7Xn7E375lIeSMay+QiEYln3rAg+ngu1w4Iz
R17lgsHq66r8ep3Je/fTrKJvP1P25JiS3IFrSJoIcgSLgUMnciKEE0qOpkRKDuw2
U2f8tDbGCodq2qHKqEusvSZ7Tvexh14wPs39rpYOfjNNyorIY6LXYe0y/8+4oNSw
yxIB/tsrXm4VjrHQJTwPe+ivNO3PnkeybzvjhUxFdDvpxnvajW7KxDJoTGvtADpg
jnvqm1SR6+NYWxv07qQBpRjOzZ1DRYR3gwcH+IBTn2ITwHi/fCarUEQMwdYzjwOU
lXuYiAV0LqXdbb71z6s6PoTEwWaGTR/KJ0DspUYc4wulZ0ep4XGH8V4rm6ekNkDl
y1Asq1lO1IGeNGuVX7OK809adQ/Hi5HKIvfhWi8I8NHZX1XvL/Y7a16x02nFVDhK
AmtdZoYcfJn0/LbHbg5TPt3I3/7f89JAklOan0ZcKATb7j2yFJMJQz86w670zXih
P6AT5mOZr+xx9YcHvDCah9DZlMZaCx+Xde4dailVTuk3Re0HVqM6Homistjvid2c
eta4QLSKDmoVlNk0v5JRRHAhdoQNTdCQqaXIe8ejcqIt1zf3veE7U4sIBd46K7ac
Gw0CAwEAAaAAMA0GCSqGSIb3DQEBCwUAA4ICAQAnOe1sLiew/d+PQDOgnO6GzAmJ
Vu6ZwhOquc+TRAmoWLhf3lXHY6Hl/z7RA/q+hT0ulOV1xIuRLuPVocK7jU/McLSJ
ugx0ilE/JCtVOYOVjP921L7rwWsX+bCloZjyJCu5O5Piuqqv0kOkBy44WiMixhpe
B2j1nglDsISh4MZVrR0RXwQPhciZk2U8P1B0olDPsXGxGPVK82DpOp+EEhUswCWP
RkbTStvvze+DojSVsHcoFgB/0nWG9DW6Lu1QcKEZHm7FEbKFOUizU05s1VaUnosN
qm3MY7RX49HIc6BX4OqkscjMCHRyPdG544SB+IcBIAQLS5wEcdzhiGcLHSLm4Xba
OG/FgQ8joFUQbwCrBvH37Y3iYrqubvByFdxlvoSWreNqxrix+KM19WGzmtEHC7J9
EZuYgsqBcUo6jbDX09vzXmdKUxqb07+WzA/5FaRx8+9jrTXJXozJfe+5IquemVn9
eKODQuWqIHU/AyiYj1reQOr8FxNSr3LDKrzf2bsmrbLQiegR5Pv6IV7xFU3clPQk
Tpfmm9Wv21IRCMhGlOGMlkGaG6PpPCARO4MrNvBne5HtdChpsesXJ79T55VVQ2BT
N0x9WIkFfcIBkJrbHS8POZMEgfIIUuNWmzWBWXS/BClQTWzQZuOr3g6eF5ZsQ7Be
HC9m3X257xqzmSP2cg==
-----END CERTIFICATE REQUEST-----

**Comment by DeepDiver1975** [comment]
```
-----BEGIN CERTIFICATE-----
MIIE9jCCAt4CAhBcMA0GCSqGSIb3DQEBCwUAMG0xCzAJBgNVBAYTAlVTMQ8wDQYD
VQQIDAZCb3N0b24xFjAUBgNVBAoMDW93bkNsb3VkIEluYy4xNTAzBgNVBAMMLG93
bkNsb3VkIENvZGUgU2lnbmluZyBJbnRlcm1lZGlhdGUgQXV0aG9yaXR5MB4XDTE4
MDYyNTA3MjQ0OVoXDTI4MDYyMjA3MjQ0OVowFDESMBAGA1UEAwwJYm9va21hcmtz
MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAv9zHbpVDpgjWbHxnSzMV
1cBn61UZOao+60b50P3pmKHwU9n+r6HLglfe1r7FpIFYf9jXK7Xn7E375lIeSMay
+QiEYln3rAg+ngu1w4IzR17lgsHq66r8ep3Je/fTrKJvP1P25JiS3IFrSJoIcgSL
gUMnciKEE0qOpkRKDuw2U2f8tDbGCodq2qHKqEusvSZ7Tvexh14wPs39rpYOfjNN
yorIY6LXYe0y/8+4oNSwyxIB/tsrXm4VjrHQJTwPe+ivNO3PnkeybzvjhUxFdDvp
xnvajW7KxDJoTGvtADpgjnvqm1SR6+NYWxv07qQBpRjOzZ1DRYR3gwcH+IBTn2IT
wHi/fCarUEQMwdYzjwOUlXuYiAV0LqXdbb71z6s6PoTEwWaGTR/KJ0DspUYc4wul
Z0ep4XGH8V4rm6ekNkDly1Asq1lO1IGeNGuVX7OK809adQ/Hi5HKIvfhWi8I8NHZ
X1XvL/Y7a16x02nFVDhKAmtdZoYcfJn0/LbHbg5TPt3I3/7f89JAklOan0ZcKATb
7j2yFJMJQz86w670zXihP6AT5mOZr+xx9YcHvDCah9DZlMZaCx+Xde4dailVTuk3
Re0HVqM6Homistjvid2ceta4QLSKDmoVlNk0v5JRRHAhdoQNTdCQqaXIe8ejcqIt
1zf3veE7U4sIBd46K7acGw0CAwEAATANBgkqhkiG9w0BAQsFAAOCAgEARf7MwGV+
fDQwGdONAOZhcYUSH8IREIhj0wT8TvR4Eg8CggpSeAI1AJ+brGBM8S6tf08hIcEw
io0dKPo8NooQNwd/nYNprSyVtPgF0Kg3x1c9l4s/gdSsOYxDBNUhf0rfvjB8uVpz
xtQttGHjsPXcuewE47wVYbWlBn7LL6+Y5MvALcZGg4IwjfVzZmf2JJWYsFzzUnJQ
hymE8t8KxTRKxz0vVNNeAfe1WylqUgYTMGApGRGT8ctxgB2CLueZLa09MEZbdGjy
o4+HJVSbysvr2VsC7CfZeOb2HyKe4+tmcyTQR1XM/5Txy1t26A7G1fvlS+kCgKwr
zR/TTaISIxxZtOlYoAgKc7Osk68wpBHNYb9wL2v8ZxztfQjvDI5/jJDjm0tGG/L/
sn/QGlfWWEqUAa+2ezCXP8b+5qdZAE7nEJPW3Nc7jEVfbaHvgIMDx7ZwiWKuXtFl
6bbfLxe7/qcEqlaTdKu4PBYahINXFJ5ulGdwWVBTx9/9peVu2hzBoriP4MySbXLl
wlUdIK6W72coZpBEgGU558cvmX0fV1ZbZ6URJKy02IDTQCXdrdAmjMTA6uAv6RIh
rOBPEGhvH8aiW3PnDer96sZACRoL6SV8q16mZENi6sXMKzuuvXBMPBNXpgJCrnWH
JhWvvUWM83u8vcvfdMzYp/SPnGMlTe1K6v0=
-----END CERTIFICATE-----
```

**Comment by DeepDiver1975** [comment]
THX a lot @alfredbuehler
