### ISSUE TITLE
Confusing to have »Forum« and »Knowledgebase« in appstore

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/appstore-issues#13]
http://apps.owncloud.com also has a »Forum« (on the left sidebar) and a »Knowledgebase« http://apps.owncloud.com/kb

This is confusing and spreads support too thin. Questions don’t regularly get answered and very few people look there. We should deactivate that and instead lead people to the very active and maintained https://forum.owncloud.org

@karlitschek @LukasReschke @MorrisJobke

**Comment by vgezer** [comment]
Also related to https://github.com/owncloud/appstore-issues/issues/1

**Comment by karlitschek** [comment]
The forum will be removed with the next update. I have to think about the knowledge base. This is interesting to build a FAQ on an per app basis. I will see what I can do here to make it more clear.

**Comment by jancborchardt** [comment]
Well there are the comments on each app, which works as question-answer mechanism for the apps.

Good to hear the forum will be removed! :)
