### ISSUE TITLE
camerarawpreviews CSR

### ISSUE THREAD

**Issue by ariselseng** [owncloud/appstore-issues#130]
I want to sign my app https://github.com/cowai/camerarawpreviews/

-----BEGIN CERTIFICATE REQUEST-----
MIIEYTCCAkkCAQAwHDEaMBgGA1UEAwwRY2FtZXJhcmF3cHJldmlld3MwggIiMA0G
CSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQDDWmmhsAg61OnvsM32Dc07i7alb8jk
YoXebOd1BguDRCiz4h70wdqIa4cwupvyPXHRhZjL8ntsul1h3N8hvqNrW67D7xAV
Xii6/y+z8SoxywfJcJrVs8jz0ZyiH4ksppcIAa6I8slTjCQF5VLvqy3qqlx/sh9x
VSUina4uO+lEOJIWnQySJ7Bz5ox/E38JFRUvaovXliziqT2C8JU90llbfJ7oo6tl
Ejlnbf6LksBgDTJKu4SkT9jkmjF236FCWyxz9F6T0+Tsq1vlHtv3egbiQKc1lTOg
kKbDvHOr+seE36ns4Eh4NIJ2hGrqat5m1v8Kl45X2Befs6zMG39NCJmyGBI9hqtq
RxYbmo1Fo31t/EPcWH5mkAhKrPLguPXNDboOlAdsKA6WoncM02qR36tjXX8paxun
KRxSAH4/EhQxd/+ROueKQk+s95fmfhhPnF/2Gc5ZruJinguiULLl/BiUPTKpwte9
ywYChm3CsPvF5kvFu/6ovIVcCZDFOJ2EMbXcM3zVbYxH2UfP975X6rbEL/mRaIX1
HIreig7NBVePUuOS4KVfi/ClmS5cnKbVioBHYIMERYHd7KmuV4Pzw/IwGIZT+ZB0
koNieHCiRaWpbcE3blYS6ko0M08DRhbK1e6fgP6F2Xwk9MGawd5QmKJHLp5dAUzt
N03fi+VSyWkDWwIDAQABoAAwDQYJKoZIhvcNAQELBQADggIBAEjtwGoF43iO9NTP
ygEyuVNVT+FUMEC7fa1FySpey4FW7I4p9JgDS7YzsQMACf4Fz++T/zay/X2w31A7
bAugez5L8O8xRP/ix8lUSroknq2yrJ8g3PsT3pvm15Xl9mqzYlGK8FKNDTE84fg0
b9nRsYWU3owQ4avSa33i0Vf3rLrS7Ms9xo0wcUOKJ1LjdG1+Mw/7y3VAN0qx0uTY
12R8mReXER7ms7wsYOCOrA7+24l0m+kS8n+28mIfgvkfxCOme+gXwPeHh57gxvg+
d2EtcmOcUwP6C2/yc1GwPr3rdC5sIEH3eC+oZ0PpPuckyMb+4lKz/gNQRsK4qMDt
alW2zNrpjsoOWUtLg4SgpcWaWi8D8/QQ89rqc6JAu4x1iRNt+9iOB0qI1DPesbSs
E4LR3BRMuD2WjxYdzpXTz5YfsOxWo22bM50KLuP4gwaGk5LsJHHdClDf1uH2ytnX
DIaoL6qiEBwecDDWj5S+NwzS4TqssblFfSDy0ozF/0hnC0+7GtbU7uzaAFbWk9YM
GyOkqL6Iyttkja65gOInTs3bp6SBsTFmRBw/MsQUXowf/6YKUoyf5MSw4IDL5qN9
oSjIDUCk9BNdnewZkEbE+CHhI/vQ88+D1a32VSGS9DWIfsox4aViQreenZkMo0gv
iZcTQ304ZLAYnLsHkOLImIakX9iO
-----END CERTIFICATE REQUEST-----

**Comment by DeepDiver1975** [comment]
```
-----BEGIN CERTIFICATE-----
MIIE/jCCAuYCAhBdMA0GCSqGSIb3DQEBCwUAMG0xCzAJBgNVBAYTAlVTMQ8wDQYD
VQQIDAZCb3N0b24xFjAUBgNVBAoMDW93bkNsb3VkIEluYy4xNTAzBgNVBAMMLG93
bkNsb3VkIENvZGUgU2lnbmluZyBJbnRlcm1lZGlhdGUgQXV0aG9yaXR5MB4XDTE4
MDcwNjA3MjM1M1oXDTI4MDcwMzA3MjM1M1owHDEaMBgGA1UEAwwRY2FtZXJhcmF3
cHJldmlld3MwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQDDWmmhsAg6
1OnvsM32Dc07i7alb8jkYoXebOd1BguDRCiz4h70wdqIa4cwupvyPXHRhZjL8nts
ul1h3N8hvqNrW67D7xAVXii6/y+z8SoxywfJcJrVs8jz0ZyiH4ksppcIAa6I8slT
jCQF5VLvqy3qqlx/sh9xVSUina4uO+lEOJIWnQySJ7Bz5ox/E38JFRUvaovXlizi
qT2C8JU90llbfJ7oo6tlEjlnbf6LksBgDTJKu4SkT9jkmjF236FCWyxz9F6T0+Ts
q1vlHtv3egbiQKc1lTOgkKbDvHOr+seE36ns4Eh4NIJ2hGrqat5m1v8Kl45X2Bef
s6zMG39NCJmyGBI9hqtqRxYbmo1Fo31t/EPcWH5mkAhKrPLguPXNDboOlAdsKA6W
oncM02qR36tjXX8paxunKRxSAH4/EhQxd/+ROueKQk+s95fmfhhPnF/2Gc5ZruJi
nguiULLl/BiUPTKpwte9ywYChm3CsPvF5kvFu/6ovIVcCZDFOJ2EMbXcM3zVbYxH
2UfP975X6rbEL/mRaIX1HIreig7NBVePUuOS4KVfi/ClmS5cnKbVioBHYIMERYHd
7KmuV4Pzw/IwGIZT+ZB0koNieHCiRaWpbcE3blYS6ko0M08DRhbK1e6fgP6F2Xwk
9MGawd5QmKJHLp5dAUztN03fi+VSyWkDWwIDAQABMA0GCSqGSIb3DQEBCwUAA4IC
AQAqVHt7kPikWa9L9wYLOK0sJ6DAUNMeRQQNyEO8BgNLj15b5r4RRYgc0TbP06Hj
SIM6zc1FMWs0ztB8gvuTMKCKdiDxX/JZx9C5nlb0cykP4PH2snnYDReyuCoE50/R
F+7dn+4CM0kTb2NLKkduWcQ4t6sXmMrtKYPLZCj0XMJqRVsbV1q6V766/VgzIhkV
1Icg9L6sgi43rkZrIQKlEvjN/YuWaZsajhHQVzfrNFcK++cOHjvPjK1rFQ66vmcE
I70WSLwj2Irs+iKJ1csj/Oe4V8kqWwHjfGt32VWLm32S7i+w68PBJPDsTa6fTkIe
bdvguCc81lP6aHvcwbd4AXgpExXOrQ4lg3VDWvlRFWjD5Y6hjDcVtNM00K/iBlTU
Wed94Jkiy2kSzHcYtEbiFmbe/nB5hpm9sn2UXAOXsRjFgxCzzQnj6rbeKueYJvRi
Z0mgv+LEfDofs9W5QurhwbXrA1gJv5PQleutyMQOlun2K/jtXMaymvSLZOcLm3HU
bk400IQ5nADDXpVIwb/cdO5IltReR8o+VwfnqtTzndF1kzehThKnn+ojPLoY3keS
3EdkbvktkyZANn0J20YNgj1tXxGuHF8n4aOuYjFxBLHffX2/vIIDanQBO9RDtUSX
OY4AgouWvi1fJoGIWpHUo0vonFN6oBgorz99nMW6nq5XjQ==
-----END CERTIFICATE-----
```
