### ISSUE TITLE
Signing request loginprotect

### ISSUE THREAD

**Issue by tomneedham** [owncloud/appstore-issues#132]
-----BEGIN CERTIFICATE REQUEST-----
MIIEXDCCAkQCAQAwFzEVMBMGA1UEAwwMbG9naW5wcm90ZWN0MIICIjANBgkqhkiG
9w0BAQEFAAOCAg8AMIICCgKCAgEAscnkL2gvyoJ8UQxEnPuxHiYHGbwaUKLnkYJa
S9ivWaQSjAohU/Ltky6AiYnUwmNzm9AfaLNIlckQTBUtO/aMRFlKYFjLXFY89RS5
kBFbRV0Fdu5hurH9RsErO3U4DMO36O2yN0D4pAW1EIETyWvdjhQumMTOGJa1SEJD
QUxECMNc+4/9aBL6NTUbJbMWAFejJk7OmbA+jGQE9UYWlhI1j2jftz8dQs3kNvzt
0ixgUisOkXeUwxd1oUcbOhzZD/MxnmsWvUG//4ffc/n9zVIFHHkNuEFnm4nyQkH8
SDmk7VVUlUjRcYD1UISRpEu64Aba70N/BlCTq4oNhH84EDObnQv6Kd1N3yJ06IcJ
FnSG7DrAlTjkZz8lcRTUGzzvWgip6xnZrWxNuBFMHnGxa+NJkKON1yzqivB9Yq+D
F6vUQuOj3gYNbRg8nSmZEfSpjjMtdZs2ca7dLMYXMeThxYJ8ufa2J/iaWo9Hb/lt
zXB8p8C8eP4tP6CdBKcFMAYlOzRCxMfqHGr5Imkr0ULAE5P01QV1/QN1c8yV1B9C
tszlYcWd7KaIYkAxz9y3rwgKcxby32O+Kwj2/mWtmASw1Qjl+tSiqNlJMUSEaJ/q
c8X4gZhGq+Js+T0EaDDlCC3bspt0uBrsKP7Wu9SBGgvdmU3Bc/UkH4I7292lhL46
GIsrGy8CAwEAAaAAMA0GCSqGSIb3DQEBCwUAA4ICAQBDtAgdnvRl/SSanek6ZJPU
DUxrYQ76+IdaivvFmq+AE26vD236r1LJilZhUVDQExAFujIrcgEaj+n/180GMuh6
z1VU+B/GfxTnxgW5gnH9hXWykA7tM8c+nhCogjwIuUqyiV08GtuMEBFmh2mdnbod
ZRs+TcWzYDeJ6I292lkU3adzmy4CbB2ENhoK8x3A0qOJK9OiH1gmQZprEY2Zdk7A
zycMWrgfuMq+IAA5oXAax2uZqXv4RsVwEZ0RKV78DF6dE6LsCZXXJVKqx73bf8YU
1W++0jxDyQFb6AlpMAXopNJKs70Ej99HcusBiTOHFNC9vaQaJBKtFTj5eAd8mR2B
FvQpATSTOIyQ/LOYw0ifaZQCueSrZnDdluLIqUDsoWmTY+yNJ78v2HvQgm7Lh2yt
qTtWORxv8ot2x4fWZtrzOvfR4nYj0JfDF8oheNgeFHkHK8Li53+sM47ApL8Koxht
b4w9hnw6HWlOULSHMMcdhqOBa0iLydMNn143zB4fbpVIIfj3DKdOU6MZaICMFodp
GNlR7u5oUFUOLUqnbX46Aye2RjA3JpaA+yYJm0eNIxrAAYwPgE0xc2qrXh0nvgs1
c8eFs4dKXJMxeWdQM3SaYr9hWGrpnZ/KgzSK2waWtkVOTLbnegCrFEtmrD2CmtbM
hvrhRs479FlATMwmyMx/yQ==
-----END CERTIFICATE REQUEST-----

for app: https://github.com/tomneedham/loginprotect

**Comment by DeepDiver1975** [comment]
```
-----BEGIN CERTIFICATE-----
MIIE+TCCAuECAhBjMA0GCSqGSIb3DQEBCwUAMG0xCzAJBgNVBAYTAlVTMQ8wDQYD
VQQIDAZCb3N0b24xFjAUBgNVBAoMDW93bkNsb3VkIEluYy4xNTAzBgNVBAMMLG93
bkNsb3VkIENvZGUgU2lnbmluZyBJbnRlcm1lZGlhdGUgQXV0aG9yaXR5MB4XDTE4
MDgxNDEyNDY1NFoXDTI4MDgxMTEyNDY1NFowFzEVMBMGA1UEAwwMbG9naW5wcm90
ZWN0MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAscnkL2gvyoJ8UQxE
nPuxHiYHGbwaUKLnkYJaS9ivWaQSjAohU/Ltky6AiYnUwmNzm9AfaLNIlckQTBUt
O/aMRFlKYFjLXFY89RS5kBFbRV0Fdu5hurH9RsErO3U4DMO36O2yN0D4pAW1EIET
yWvdjhQumMTOGJa1SEJDQUxECMNc+4/9aBL6NTUbJbMWAFejJk7OmbA+jGQE9UYW
lhI1j2jftz8dQs3kNvzt0ixgUisOkXeUwxd1oUcbOhzZD/MxnmsWvUG//4ffc/n9
zVIFHHkNuEFnm4nyQkH8SDmk7VVUlUjRcYD1UISRpEu64Aba70N/BlCTq4oNhH84
EDObnQv6Kd1N3yJ06IcJFnSG7DrAlTjkZz8lcRTUGzzvWgip6xnZrWxNuBFMHnGx
a+NJkKON1yzqivB9Yq+DF6vUQuOj3gYNbRg8nSmZEfSpjjMtdZs2ca7dLMYXMeTh
xYJ8ufa2J/iaWo9Hb/ltzXB8p8C8eP4tP6CdBKcFMAYlOzRCxMfqHGr5Imkr0ULA
E5P01QV1/QN1c8yV1B9CtszlYcWd7KaIYkAxz9y3rwgKcxby32O+Kwj2/mWtmASw
1Qjl+tSiqNlJMUSEaJ/qc8X4gZhGq+Js+T0EaDDlCC3bspt0uBrsKP7Wu9SBGgvd
mU3Bc/UkH4I7292lhL46GIsrGy8CAwEAATANBgkqhkiG9w0BAQsFAAOCAgEAh0SA
sVwOt1jHOuEeCEOoeUwy0xlPWJYRBWV+mfDqkugekI5BfuK7a088M9ECvNQg51ez
JI1GfB0cKPC8yT+HkaW7HvN04znwEvfXRoFUOI2cfEj7EV4Z/jh/8uHdgb4ruXMK
HzMxSilotwUYK02MoCzTojNdMi6M1ihbhh2U+xCVNixVJCCgYRpsM8WMD1iuXf8a
4NJM1l6mLNfivV5+MAhAnKhDfG/VsEMBPmcpQGMXluORJ+B0hGHc+iI4hbPylfy9
AQCjXuoVq6jkmyhbKzD0mUhsAy+qyuArJ6NoPx2G3a2F1iVfygKKh/V6wMFAMqpB
m4qmF6ccYGfzdE7Dv21/0pgImY+6BbBosYVxaT2ulBfPAKhxh9pAIPToMdnjA6Kv
5cl6OiOsoINIfPYWG8v6tJIhJ+i8YmMVS7F4pdrfbrxdJkPdzrRlN11sfjiCfoZl
EDQuj2iWxVvCVKD7BUmj6g4T+hEFc6L4mthwgx1y9E776qoFX8lLy02xptj3FqDx
ztHzob0JTfXcWRU4Z4l2zLD9g4NKWodWoI0ZWmQEE/XQWp5OWuKlw4pvw5oXMkLI
/vbDeEnUI7SykON/QY9rQmmOk8GhO69F1xS/Xl30ExvvN00cicfuty5A6UF/s/AL
O9BXdsa0pzTraDOJNCaTvQ5TmnZxHmVHu+8kE8s=
-----END CERTIFICATE-----
```
