### ISSUE TITLE
CSR cms_pico

### ISSUE THREAD

**Issue by VicDeo** [owncloud/appstore-issues#134]
the app is at https://github.com/VicDeo/cms_pico

-----BEGIN CERTIFICATE REQUEST-----
MIIEWDCCAkACAQAwEzERMA8GA1UEAwwIY21zX3BpY28wggIiMA0GCSqGSIb3DQEB
AQUAA4ICDwAwggIKAoICAQC5//GC21wdpHW1Oowroah3aOMjSvEDtc6QBsCTb6/n
R3jbFX4ED9gk5Su0qbG+RNQB3nmy2PfJxcq1sEWkwee6buCm1islG92JAVgl3BcP
sjT1KkARtfmZqwD9xWfj2YpGySEgUlCabyuYSXbqXttGjr9TQYs0iPQ2IJxW2Kqi
NNiSAar5FC4oivwttfJ7zM2Y1gsn1JgBd6KxAVFx4FQGM9FXMIWDL7ZHy7y8/la+
DTfBnRto+EpEaLOOnefWKjeQpI4/oLdBrx8g2Oo1Qc5qk69r8scyQDXzXTDZhcHR
H/XybLdK5Ikyw9D/Axxqf9fBsbIBJNeZXTZKZg1VQKZ08uv3n69em/LiDNdXWwsi
zgNVQLtq4tIEqnhEG4koDwu2QuxOFHKhDPzsPiZd6Ikq/F9bE6SHxtNSVuAuKGHC
Idp2NpeeGVkP+/RG3mdkD6HGACwUlg9RI8A/s8MrSRQqd13vN7nfDPWoNy9c2D83
KtM+LPvzoIdv8e0Wzv0FkB5E7zgePyvIgBGNMgTOe0tNVFiAXmzd8AXgXohX4eZN
ik5nl32YW+PCohMNJCGAV431qIQFaOSLfSqZdd8vt0lPU0SKnnGobo6soY+q8pI8
slaixMkQ67o7t4+CBZI8r+NdKocuB+UbCTP55sn8QAXVxWJXkf763Rj/6x8xvfVk
uwIDAQABoAAwDQYJKoZIhvcNAQELBQADggIBAGAyyBsAMvZJ80vJ/5SmyWYG6Nsi
kz3sGYDj/Byu44dVd6PyiahOid7h42n5X7JMd5xJwqBLew6Q22oA2b7/Rl0ropSM
RVrSaMrPiFJoQgESVBWPARXiGvFEN9FXs5lHB1vgTdKrJJrqwSleJq5xy1cLFyz5
s9GD+22K9vV15lCisqXIwMLlHoG3J/KFXOImPP88855ke1uCsHYr6aRO5Gts7m7/
cxbLFBXPVyxSXbs9NYAkBkyoELsILv3mTwTLIHnREMWx90/Vg6doXgIVpoYnPD45
bIDGw/STSnd0pFFLqgWhlXQG7cjfpvB/40bCHa1vwOZiU/ZZOw3uwB7RydOdQy7w
cPDO2odBOJfLXgGobDk736+vBDaTEi5x0qtflaOx91W8I3ScOtgntN3LGxjl25kl
pe9d2JKtSnM+kmUTt9qgFwLUyj+YBIk+4TGG3GsAY6m/O4Las3y7vq7nO8L3NKOc
Qpf0pLsM9gd/pk9nL4cMX/n5Qe7q5ygfKCaA3kH24j6SBIHH4WPAVy1O5fmn2oV2
1A0gmbm4OZNotRuCF5Nqp/xLVm/triTMyEBVy8M3EJHWzs1yg608GjWmebiAOgpq
cGDjk119HDj628J7fcWsKxKUWQQ/uisCnx8JKkoYOIEN5QgcEqL6z185/RQlnc0E
nLX1EsHuLaNK7YAN
-----END CERTIFICATE REQUEST-----

**Comment by DeepDiver1975** [comment]
```
-----BEGIN CERTIFICATE-----
MIIE9TCCAt0CAhBmMA0GCSqGSIb3DQEBCwUAMG0xCzAJBgNVBAYTAlVTMQ8wDQYD
VQQIDAZCb3N0b24xFjAUBgNVBAoMDW93bkNsb3VkIEluYy4xNTAzBgNVBAMMLG93
bkNsb3VkIENvZGUgU2lnbmluZyBJbnRlcm1lZGlhdGUgQXV0aG9yaXR5MB4XDTE4
MDkxOTA1MjU1OFoXDTI4MDkxNjA1MjU1OFowEzERMA8GA1UEAwwIY21zX3BpY28w
ggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQC5//GC21wdpHW1Oowroah3
aOMjSvEDtc6QBsCTb6/nR3jbFX4ED9gk5Su0qbG+RNQB3nmy2PfJxcq1sEWkwee6
buCm1islG92JAVgl3BcPsjT1KkARtfmZqwD9xWfj2YpGySEgUlCabyuYSXbqXttG
jr9TQYs0iPQ2IJxW2KqiNNiSAar5FC4oivwttfJ7zM2Y1gsn1JgBd6KxAVFx4FQG
M9FXMIWDL7ZHy7y8/la+DTfBnRto+EpEaLOOnefWKjeQpI4/oLdBrx8g2Oo1Qc5q
k69r8scyQDXzXTDZhcHRH/XybLdK5Ikyw9D/Axxqf9fBsbIBJNeZXTZKZg1VQKZ0
8uv3n69em/LiDNdXWwsizgNVQLtq4tIEqnhEG4koDwu2QuxOFHKhDPzsPiZd6Ikq
/F9bE6SHxtNSVuAuKGHCIdp2NpeeGVkP+/RG3mdkD6HGACwUlg9RI8A/s8MrSRQq
d13vN7nfDPWoNy9c2D83KtM+LPvzoIdv8e0Wzv0FkB5E7zgePyvIgBGNMgTOe0tN
VFiAXmzd8AXgXohX4eZNik5nl32YW+PCohMNJCGAV431qIQFaOSLfSqZdd8vt0lP
U0SKnnGobo6soY+q8pI8slaixMkQ67o7t4+CBZI8r+NdKocuB+UbCTP55sn8QAXV
xWJXkf763Rj/6x8xvfVkuwIDAQABMA0GCSqGSIb3DQEBCwUAA4ICAQC4VvMoK4eG
kpr6sufvCAaaE+OSyEMQjMMxlR3gg99DbXbETtIe4C9fiVHc9WrllyoqCJ9F1ZNG
tgZl+/gBRyqZt5b85nM9uH2aZIi09e5D/vu5HW5kT4wTZhWFY+SJEuUOMa5gZLCK
bKXKqESJmMAyZwAYLy8xhzdkq/UuIr+VdQBGiRKnB5vTxMWui6j0sItlbn/12SMR
BFRH65YJX8MCV9W+ljKXlQOVjtdn0MOhyrTEGiTNBr6zKKS0PL9cslei6JzBXWvJ
TiR/rTaBTk5zFBtdFPldh7CvEqmJf/6n3r4n7rdFRxHOVz2dXQF3fKyc9E/czqeR
1PMP47SrXjzApFGBPzOfDUEUC9dVaTXlKv7/oozzg02tFRKR5Yms1Twl9/42p2zS
b0i0hujm2vgPNsTLS/A1IPtS++Vjck+Trv131NfV/cs1/v8tLCaZH3Ufi2Zf0x8m
0Vfo7P+TJZ/WCB3Zz86M7R/uXWLn2o3vyk+Tu49uYufTkPTdQbu2yGw1jDW5IWXx
Ov5dMAbaBApREEK/jM8vldYgORXqz2zqZ61EOhQP5mVoV07o+SrrZmZ21BJeiXRP
+0d43JW/UVG4BSnHoh1OWBmA8+Nq8+Eqo+SydFONLHKuLMs4MNqGHhDkiMIB+e5j
I+IYRiHbfPt+SzFuocnwUM5WrhqhWnpWig==
-----END CERTIFICATE-----
```
