### ISSUE TITLE
wallpaper app CSR

### ISSUE THREAD

**Issue by tomneedham** [owncloud/appstore-issues#135]
-----BEGIN CERTIFICATE REQUEST-----
MIIEWTCCAkECAQAwFDESMBAGA1UEAwwJd2FsbHBhcGVyMIICIjANBgkqhkiG9w0B
AQEFAAOCAg8AMIICCgKCAgEArD9hnJyq3tC5K4FgUHNurZSx3UkXykWibGVZtnh+
jNyaWyT4yzHtncnUZboPfO3FnZAIiJAJ096y7nwp3Wzgzygf/lzVrDj+2+fjHV/5
wOSPUlCW+e26sCOE+7nhfTKQhridIatHm93vBBh7tXQKAjfDrj4vlYqZ6js5rqm5
VRB4HvF2NQZ1gc1uWDk9KRFShUxIvxJurvpnxuDeRiSyMjuRJZVCUUxRECzc0uze
wPnTfjRH+p7Hh1TMoTHr1kFPJWiHVzU45qkLRIR8NJvh6g3emi1srwAhjsocIdYO
w6xvdAGPiZfiK1Yeza3bGjpmj3Ggp74J3fNj4mStU1CtJkwLSPTcf4rrxJ7jhrnD
hxHnMM8sX7NcJAtpgfNEVDSdHK47zosc232/NHNYxVTK6Nui/xXUWyKm6OUsRI2S
5pSIAH0BON8IZhPo9A+M5ATexvMPSGQurbXV4vG5dH08R7jdBWMOrb66M0jPMTPK
LQG3DPaIro3VyhiOCZDjQnFkd6A06TG8Cz62e1joH+6TfVAQLmWsULaH9E/p3YjY
awlhPw5KEcjBUytixiGaBNTc+Lu+C+pNZaonpHI10k8TMyGtXV2CugH75mUagDdp
0zPdFM3B9F39MoyPkBO4+mbgD2kf0kV0VkByLPL99uf7pzsMhOrDSvFzYKJfLpQE
RZUCAwEAAaAAMA0GCSqGSIb3DQEBCwUAA4ICAQBNrrK+1fLRWRq6USaZ2ktcaU06
RZZT0Q1f6V9WxsOmpu2yUpWtJ87YJy7ijo1PsZVW5t7sHhaEfJOwPru5KNitzWN0
C/l3W6PTl3NcFMfHld7ImcmXMaiNePWWAyPgLb0Zc+YlPGUkU++wwcFarL7RXLpr
QcjG+ab20gTaNfMWAcpZNX9e7JUgR0ayb474CxG0reiva66EJClxKNdIpHGmkqHM
v4IdQ8yJ+VGO70npcnAV3OI7EiExVx9b8WIpPR8CWfa+gPazvMH2MeRQ4tcHwYG7
qCVFZVgDy9C6+C13C34WykDRU+u31rsEO4Q5EgN169A6W3iU7GOylHvg1MvDTobv
mK4HTvHrKwG2cKWK9+iqItTc4jn1ajmu/gZwes1jiK144N9tSFPygjzgtaPjuPm6
uJNe3esvEMq2NCZbwpaR4xMIezSrIjW/DsienzYxVMbC8bS18CUT+JWRksVInEol
E9LfxlUUuLR9yWe6vIURXaueBWyMsku2Xr5NYo053pKKjEnGQ+2h5iqLc/FmlDnR
ratTeSV44kv/WTpQQ1Hq208uy+0YJRr8HbO8o0c8TukYnCRFYBno+EIDHmh7MlfW
3GW2zpHNE8KZaRlmjIl4xq+QRPo0WUFuFrAPwIN7zKScKWigWXhyfVZMUd/21t8a
aaWk0HQldR/sBkETQA==
-----END CERTIFICATE REQUEST-----

**Comment by DeepDiver1975** [comment]
```
-----BEGIN CERTIFICATE-----
MIIE9jCCAt4CAhBnMA0GCSqGSIb3DQEBCwUAMG0xCzAJBgNVBAYTAlVTMQ8wDQYD
VQQIDAZCb3N0b24xFjAUBgNVBAoMDW93bkNsb3VkIEluYy4xNTAzBgNVBAMMLG93
bkNsb3VkIENvZGUgU2lnbmluZyBJbnRlcm1lZGlhdGUgQXV0aG9yaXR5MB4XDTE4
MDkxOTEyMjMyOFoXDTI4MDkxNjEyMjMyOFowFDESMBAGA1UEAwwJd2FsbHBhcGVy
MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEArD9hnJyq3tC5K4FgUHNu
rZSx3UkXykWibGVZtnh+jNyaWyT4yzHtncnUZboPfO3FnZAIiJAJ096y7nwp3Wzg
zygf/lzVrDj+2+fjHV/5wOSPUlCW+e26sCOE+7nhfTKQhridIatHm93vBBh7tXQK
AjfDrj4vlYqZ6js5rqm5VRB4HvF2NQZ1gc1uWDk9KRFShUxIvxJurvpnxuDeRiSy
MjuRJZVCUUxRECzc0uzewPnTfjRH+p7Hh1TMoTHr1kFPJWiHVzU45qkLRIR8NJvh
6g3emi1srwAhjsocIdYOw6xvdAGPiZfiK1Yeza3bGjpmj3Ggp74J3fNj4mStU1Ct
JkwLSPTcf4rrxJ7jhrnDhxHnMM8sX7NcJAtpgfNEVDSdHK47zosc232/NHNYxVTK
6Nui/xXUWyKm6OUsRI2S5pSIAH0BON8IZhPo9A+M5ATexvMPSGQurbXV4vG5dH08
R7jdBWMOrb66M0jPMTPKLQG3DPaIro3VyhiOCZDjQnFkd6A06TG8Cz62e1joH+6T
fVAQLmWsULaH9E/p3YjYawlhPw5KEcjBUytixiGaBNTc+Lu+C+pNZaonpHI10k8T
MyGtXV2CugH75mUagDdp0zPdFM3B9F39MoyPkBO4+mbgD2kf0kV0VkByLPL99uf7
pzsMhOrDSvFzYKJfLpQERZUCAwEAATANBgkqhkiG9w0BAQsFAAOCAgEAlm07AfoN
bfhnDtuddjmAq+dYvXgMFbxT9S7KVzz5EOiR2CN6LT0V7a6a2g73Aq261nXicjgp
XdqW1OTg6M+mOnvJ+60zksCKPFPGukK5Xl19mGyXFRiObfMwi6fOCkDbb7JNWles
Qm59h3j2Edjh7TS6fO1xRXpaCuvrccHHh8cOBXLYQ4Kd3xsKaOxkpw1HsQDEggLa
rM34pTxxhx9O7f9I9eJJ8OiutxR72Nx88q9WBThuYvUfA4JjYcoyzKpBpQVfeWcq
ABAcHyZfyYccIiE6LkNNv5wO45fvcxG5vsSm66kNvueoaCcv5UkphDQWk1Juc1g8
/g2z46iWdKwkPc9UbRWiBNFG0N4ooxcrtxZiu9AcoyeLV1IeSG09K7XhZGDIERp5
ZxoVGbzFEXi4NlbEVhfHbyxaxXyhIK6WTSzTGOkDI3BcP2AWHtgjOkx0G9nqZCX4
zaYLbC7SeJNGnlu7/9Z+01RPeAv9hu6+OG3hIH7Zm3Sd7WopCP93bmk4JVAPmJt2
l2HzFu8CAHmPt8ZQdwxYZeRuWXvHlvEoifVRBf1ZOW9jPfL5RXbt7LoAnUpElAvY
wxmQb83mZYnCHQmI6COyLuf9UXRXz7TwaaP3gRd4w29VuN/8Y+4CEdvOH/xX7cSI
WzCZkt1wVU3vejpIQsfwiaxopyPgAYvnxAc=
-----END CERTIFICATE-----
```
