### ISSUE TITLE
Theme Signing

### ISSUE THREAD

**Issue by gpapaiko** [owncloud/appstore-issues#136]
Create a new Theme For Company use and need the code signing

CSR file has been zipped to upload

Thanks
Geroge
email: george@icednetworks.com.au
[ins-theme.zip](https://github.com/owncloud/appstore-issues/files/2408778/ins-theme.zip)

**Comment by gpapaiko** [comment]
Theme Name is ins-theme.
Thanks.

**Comment by PVince81** [comment]
you don't need to sign theme if it's only for internal use. you can also use a config.php option to exclude your theme app from integrity check, see https://github.com/owncloud/core/blob/v10.0.9/config/config.sample.php#L1275

**Comment by PVince81** [comment]
@DeepDiver1975 should we introduce an issue template and have a mention about this doc ?

**Comment by gpapaiko** [comment]
Hi,

Under normal circumstance I would agree with you, but as I have (am ) discovered tit might actually be required, and let me explain as how I  come to this conclusion/theory.

First let me explain, when I use my custom theme without it being singed I cannot edit the mail templates and I get a error on a plan page as per image attached”.
Error message is:
**Mail Templates
You need to activate own theme to edit mail templates.**

Now when I disable my theme and enable the “**theme-example**” theme, I am able to edit the mail templates. This theme does have a signature.json file and all works well.

Now when I copy this theme “**theme-example**”  to say “**test-theme**” and update the info.xml so as the id matches the theme name “test-theme” (no other changes are made to any other files) , and remove the signature.json as this will no longer be valid.
When I enable this file, and again unable to edit mail templates and get the same error “**Mail Templates - You need to activate own theme to edit mail templates.**”

Hence to validate my theory I need to be able to produce a signature.json file for my theme so as I can test to see if I can edit the mail templates, and I suspect that I will be able to edit them.

I have followed all of the instruction in the manuals to a tee and the results are always the same, I have even test a script that some wrote called “theme-bootstrap.sh” and the results are the same I cannot edit the mail templates.

This was not an issue with OC 10.0.07, but became an issue once I upgraded to 10.0.08, I don’t know if this is still an issue with the latest version 10.0.10 but I think it will be. But before I upgrade to find out I want to test with a signature file.

I cannot even edit any of the css file in the “theme-example” any changes will make the signature.json file invalid as the file hashes will have changed.

Are you able to help with this so I can sight my theme and test it?

![image](https://user-images.githubusercontent.com/21032399/45946873-94f9d200-c035-11e8-9fc3-f733d7ce4fd2.png)


Regards 
George.

**Comment by PVince81** [comment]
@DeepDiver1975 can you sign it ?

then if it turns out that there is a bug in the template editor, please raise to https://github.com/owncloud/templateeditor/ @gpapaiko

**Comment by jnweiger** [comment]
Suggest to close this. Please reopen if help is still needed.
