### ISSUE TITLE
Certificate for my own theme

### ISSUE THREAD

**Issue by ignasibg** [owncloud/appstore-issues#138]
This is the CSR for my own theme.

> -----BEGIN CERTIFICATE REQUEST-----
> MIICXzCCAUcCAQAwGjEYMBYGA1UEAwwPdGhlbWUtZGl0c2liaXRzMIIBIjANBgkq
> hkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA2co8OIhrbZbBy8dtzDM+3Uu8kv0e/VXg
> jRh+caiyU1rvg/PrvK5//YU8FVCweEBBJDduDIB1BYkHaCIfJuJm05h2RpCG5SwP
> YDybh5qdUjP5NEOO3nvyAmwb+GIU8E84933gvCbSnPRcSTMSBw2PwgyYVdDCiRko
> hpbpWJPAx1zhtHCkGTjWZzWh63k7cqoyXDB6Dd9fEWcyZpG7ratLJGO9gFSSUlRv
> vBPKck7To3N8xIyixxuepUHUoYxm3Oy6e1noRJK25G9brxx80Hr3h838u+vXcz0L
> D11X4kRFlvEOY66UGvdN8mIZ95JIGiECU8tVj69KvNb3PMSfn378nwIDAQABoAAw
> DQYJKoZIhvcNAQELBQADggEBABLW7SrHIcDU5XYj+rTmjQd/VKPFzjPUXLafty+h
> o5NuO+If2NbKAeRLm4nMlTJe1LAcdgow10tlnPhPkqKADXqkec+fCmJWXRJclTir
> mI8y0e3l8Svi2TOBY6IpN2NTmhBPuys4KZWNjLDbV/mmFvJuoz/LsK59CxQfBJLw
> cd7gC8kNP3Z9QNKcNMfTFQedcBEEi/ro9UUzhVr2BCTA+dnv9UzMX/IfsFOG2xHO
> /NNhWt7QJA/Frg6C4mxF7FoRtXZyin/wTzIEnph+R9Z1sjgEw5Rt/mqeSgVLLP1s
> xUYgf9EMk8kY6lMim/kV8gPN7WtXDmBywaD6lIZ/sD6aqUU=
> -----END CERTIFICATE REQUEST-----

**Comment by DeepDiver1975** [comment]
https://github.com/owncloud/appstore-issues/issues/136#issuecomment-423891540
