### ISSUE TITLE
Private key contacts.key does not exists.

### ISSUE THREAD

**Issue by mnalam30** [owncloud/appstore-issues#140]
I want to get my app signed and it got error that private key does not exists.

mnalam@ubuntu:/var/www/html/owncloud$ sudo -u www-data ./occ integrity:sign-app --privateKey=/var/www/html/owncloud/contacts.key --certificate=/etc/ssl/certs/ca-certificates.crt --path=/home/mnalam/contacts`` 
Private key "/var/www/html/owncloud/contacts.key" does not exists.

**Comment by alfredbuehler** [comment]
Is your app also named 'contacts'?  Or did you just clone the signing code from the official contacts app?

**Comment by DeepDiver1975** [comment]
You don't have the key for contacts because you don't own it. Please follow the docs on how to get your key signed. Furthermore: you cannot get the key for contacts signed because the contacts app already has a key and I own it ;-)
