### ISSUE TITLE
CERTIFICATE REQUEST

### ISSUE THREAD

**Issue by mnalam30** [owncloud/appstore-issues#141]
-----BEGIN CERTIFICATE REQUEST-----
MIIEYzCCAksCAQAwHjEcMBoGA1UEAwwTQUVTLUVDREgtRW5jcnlwdGlvbjCCAiIw
DQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBANRCL6HcNqNHFNKh5+sTUTQGng5g
wSNf6hrhu7Dhi7PkCAoigFHh1H900RD4f3BS/zknaa2/YYNahhjUZ0vcCoRKBiFz
570CPQRBrCD9aTket+uHExVuMmsNXzB7Xs1eMjd/Yr1O7o2VslfetSepyMTPE8a8
AdxRtUPjFj6zXEhE0HPRTeimNvQkNeWJ3egpamesx0N1mZxoZTgSEurohWX64rBv
4la21CULSqg8d0R2IiJbJvCOw3qqRpbHhT3ljTHXld+GBrBvtqNdpGpykh1ykZjy
Am3wx5z23cWcUpLv9Go03eracOS/OKDhaJ9vwiyWRLp1GaZcJe1oCWq7CO/fWQNH
ydgV7RNdcLf/bH3JOk12KJZWtE/PMi/4gRv+9TyrUAZETFqGmmPhGzVdJ/oYcgof
vLIKgaurCtNwrlF39PXiYV3ur3y5AZFcSTqKGFGwktUA88WvqCheAzTEE3uW4VMK
K69+ACNfKp4Q31QZ9S+DsjBO1WD2f7GKj2Lh2gJSfzk6DDhgpZM2rEMS09Rlla5O
M7nqUWAPjc+v/fk5+9RUE8lw1mto/D6W0TV9W0tcTUOPwQA7dghzY8RapU/Z8FoY
amXIr04lnqeVs+4DD7BhFbJpjJXpPo+6hLFohnF/FOXw0hljyK4HwicKOUdYGml2
/6DdKRXLL141mGKJAgMBAAGgADANBgkqhkiG9w0BAQsFAAOCAgEABSxRh+ZsW36z
Z0kKPyNqt/VmgmwvgqwYaktk8J+nX+TbtM3nIyhFsi0Ltwn2PTKDwvja5tUZ4c4l
QNpwZPZqZWLPpcMniruqZ8DUHf24dYuxRZ+Lkee9fcoUKTkl46b1Z6i1sEuCNB98
UKVmZAHYv9OI25r7hDao8SCagkZGs1qk5ZfbAyhE77DcmMyp89WNMfDryQUNl3Sa
ux0NH8uXwsi8kx0uwnZkm19Iz68XBy9M1moHBmDA5mjwiN+sn924xjEWOsKVZ9KQ
lRYmJTnCsu4soDIGhxdS+ZhXXnhbM8FUk93YBHSKB95A1Iz/OugOYZn5QYGgmiT3
eKAbxd14LlixV0SpPl2LfX5G5e+2rqQg8Uwdf+HOoAktDELVKstuokTUzKHwmUJw
W1jvF+Je4xWgGiq2ESNGE8xDK0nLq1qcNZv+iYzv2FmAjTsUu/WJSnQFL4yqYmmr
cS1InM1fM++moj+PgjAHo8OcFvdPfOW9+MWgtXPa9IL4SdhGQ/3y0tNEuXFWFoqo
ooNP5cYv+f63fNJp72vkf+65B6iUPANovPEMzkmJfdWsHwm4dqAfn7QQoHhY+iji
BEGqeE/JtvInziktHyJOv5itREUTRHZOTNsaSPONtbmg1j11Txs7Da1fntmnzvf8
IS97mbBaqyfVNPnrQOE4FJlJynoHp6g=
-----END CERTIFICATE REQUEST-----

**Comment by DeepDiver1975** [comment]
your app is named AES-ECDH-Encryption - this is not a valid app name.

app names have to be lowercase and - is not allowed.

**Comment by mnalam30** [comment]
-----BEGIN CERTIFICATE REQUEST-----
MIIEYzCCAksCAQAwHjEcMBoGA1UEAwwTYWVzX2VjZGhfZW5jcnlwdGlvbjCCAiIw
DQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBANz8tHPKcJBGVxx+Kk2q4CTNCGaj
vZ/wnZvmzwP0KOi3wl+J8FLyJ0cYwhEzMWKbtREa8Ctio4zVqLmPLpW6c5IzdY0N
HGYekBjkFZsRRDf9ZKMtNcYJchJBsh/492hK9sTWIgJedimWaklTGBwxAkP1cw8H
GC8lw3wkvu30iZDzkxEuJ+OoR5SK5fTCCDgwOFuGAX0+mE3n3auh3WvsKM7c2J1H
Q42eatNVOxQB3Gvqwd/1qNGR5LVg9+4yB3DslSxd3M5nLQVuurQrBvcFa3iJFrBB
g2v1WqEtVTXeuoHck3VYLknn+FbtcBtrtWAHzjA7Rh4x+LjbmtndFV18cerRTk/x
f0Cd9EJqF4AYti9kU5lpmW8N7oDSjQOfGMd0jTw26TVF3dqYSL1XXKVDP1J8Xgjx
Vf6/o2I/3NTOZMO8fReDkX37QEn8Axu46b7/Heq69NksoMmMGIq02VMwsaawSngG
4SC7vwPWKQIQJK5wAyu8oFTdFTUIcaG9EeVhGap7VhtmbEVPBjY4kv1fvm6eGDBF
ggOS+DFtt1RmUcJ/N1/TIPf0KaXyZR2Knv9BVKx6dzYmNUx3vdt7o8x0ob4/pJFi
0nAV3dAQvpEfljwk5OPLID7Rd5K40ONtCs05hTcEY0hWinbT+FEzjnTDjb8jnadZ
821SqjuStelvpYk9AgMBAAGgADANBgkqhkiG9w0BAQsFAAOCAgEA2p0vkS9QLhkr
DELOFtFm2cq2hkDuqL7YX8jXYTvYSmku3hou4aWdWmD2vxmVyannKY5VHJ6u7kId
+nu0ygwtpbFKwfBMtrQFcSOTmLSLept9BA/Mn99S4D+hXyonZQJh2liiGIF0i5BS
JM7rRqTWqJJvT1KqgoRYDMffq4MBXkUBtQBrq4cIwhiypkIXLgsVbfO4QTBksRSX
X/eC4A1ymC6J2t8m7fTxcAEgEAHM/v61YNu5pPcYGaXNr/KVLXzCYLJMfGX0QZJz
yub364/8NUF+n/vsZoOdVwNTxHYUKm7EJy2Wp5jAXS6Dzo1OIke8wfIujkh7Pd1W
xhSy8Bjvan0gMLLPqjVvaq2ih7rr8A/7V3ZDEqj+jjAfexkiS2mmhQRMYAoHcwpn
rhT5udCXlP9cRdSgMgYf4uixZOPws5X8A5x95oAVOloZvx2uq8c1o91twf3rYYuK
w2w3a7tZGW8eTMTItsiU2n317KROYQZnfqR9yE69beZ9SB0MsLIZeJiht4C0dvi4
AYyMqCalVpuAgp1bzjSNFvIARUiHw0DQ3i4YVFFs5oI1tFIJoKyYBiWGWOmvMqp7
peeTl9JULtrJmg8wiAtdCnZjo6D+FLm2h2fGxVUH2t/2SdnXd9CerUX5HS8mjZur
sDnr10cYez0RHWPD6RkCEjdv8Co1kt8=
-----END CERTIFICATE REQUEST-----

**Comment by DeepDiver1975** [comment]
```
-----BEGIN CERTIFICATE-----
MIIFADCCAugCAhBpMA0GCSqGSIb3DQEBCwUAMG0xCzAJBgNVBAYTAlVTMQ8wDQYD
VQQIDAZCb3N0b24xFjAUBgNVBAoMDW93bkNsb3VkIEluYy4xNTAzBgNVBAMMLG93
bkNsb3VkIENvZGUgU2lnbmluZyBJbnRlcm1lZGlhdGUgQXV0aG9yaXR5MB4XDTE4
MTAyMzEyMTkwNFoXDTI4MTAyMDEyMTkwNFowHjEcMBoGA1UEAwwTYWVzX2VjZGhf
ZW5jcnlwdGlvbjCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBANz8tHPK
cJBGVxx+Kk2q4CTNCGajvZ/wnZvmzwP0KOi3wl+J8FLyJ0cYwhEzMWKbtREa8Cti
o4zVqLmPLpW6c5IzdY0NHGYekBjkFZsRRDf9ZKMtNcYJchJBsh/492hK9sTWIgJe
dimWaklTGBwxAkP1cw8HGC8lw3wkvu30iZDzkxEuJ+OoR5SK5fTCCDgwOFuGAX0+
mE3n3auh3WvsKM7c2J1HQ42eatNVOxQB3Gvqwd/1qNGR5LVg9+4yB3DslSxd3M5n
LQVuurQrBvcFa3iJFrBBg2v1WqEtVTXeuoHck3VYLknn+FbtcBtrtWAHzjA7Rh4x
+LjbmtndFV18cerRTk/xf0Cd9EJqF4AYti9kU5lpmW8N7oDSjQOfGMd0jTw26TVF
3dqYSL1XXKVDP1J8XgjxVf6/o2I/3NTOZMO8fReDkX37QEn8Axu46b7/Heq69Nks
oMmMGIq02VMwsaawSngG4SC7vwPWKQIQJK5wAyu8oFTdFTUIcaG9EeVhGap7Vhtm
bEVPBjY4kv1fvm6eGDBFggOS+DFtt1RmUcJ/N1/TIPf0KaXyZR2Knv9BVKx6dzYm
NUx3vdt7o8x0ob4/pJFi0nAV3dAQvpEfljwk5OPLID7Rd5K40ONtCs05hTcEY0hW
inbT+FEzjnTDjb8jnadZ821SqjuStelvpYk9AgMBAAEwDQYJKoZIhvcNAQELBQAD
ggIBAGE3U5Tj2OJigHx4IcOmotJX06t5WT58NjBdgHBxQg72OvuoAmoSi0wd8ES5
+bMGjcMgq6j7Uh9aY2A5sZcOhQeTS0cLkzLjXmI71aSxAGUCAeXcPtn95EBWXvfu
WO95Fez7zagxc3ROxjv9s2EPI+B/qh3IAYwn18FAAezhIdbPvMTJVj+KZ82rFMTW
SIx4y6lvJLh2mXe9hvgkdAkF3+5xWz4D7fQDPSNGEzXgqkTG4em4eD1VeIwLFtMN
rmjTAuI+zOeHOTJLjDMord4jtB9EpzjbgXDCfUfgR+rOQg1IsmwDH8JHH8pBYEJ5
MQRfWLbdbnIEaPfkjWJKHuCC5cp4uK0OzGxY+vKKMIJazVvchp48xXTi9YwZM8Xt
T5s8Ib5i9pyTaQRQF5PTML9ObidENpb4/Wi6HiwyuBOeSrk5WOrxUPWDi9w9zDj+
ZywQSWPxKrzhEDIoOo6PGn/j3Cioqa0/VOhSiENABPS4bFvRjb2gjyQrxouoOImP
ZRvdt8pYYDM7oOmji9f9XD6xELi8z2NwxmokvFFUMs3n81UIDvtP2LxWeLdBqSyD
kIP/zvLcf9E/2qQYWW7VKYBGv5BlDm2hq2kSAKk70sJZSCyAYmUqdJb/ajrdVwqW
YLaw6Vs+337Ldt3O5/yQhWlDKz/Abu/hFD3+8TnFzD/R8ZU+
-----END CERTIFICATE-----
```
