### ISSUE TITLE
CSR for bplog

### ISSUE THREAD

**Issue by alfredbuehler** [owncloud/appstore-issues#145]
-----BEGIN CERTIFICATE REQUEST-----
MIIEVTCCAj0CAQAwEDEOMAwGA1UEAwwFYnBsb2cwggIiMA0GCSqGSIb3DQEBAQUA
A4ICDwAwggIKAoICAQC4CPIuPnxj1xw4OoKjccQylaqSRt5LbVIkVTdE/KYzmHp2
7owrntJvfIJx4d+LrkFPLRdOQihz8SKhTHxg274pMbap6lN+z03dsVVEzDhwtnLo
Tbx4P9vb2iLBjWEyJkcS0+SVJwKhvY+Uhq1qZdNS9mCwRNcpO959Px2nVfhHB6JD
fQ6yKLW+7ul1OcZkNCQlkHv8K1xVNedWD0chBdp3gD1lteWQS1ibCCyGQPNi8ZL1
ofoehURUr8/RD39c2Oi7Pa3PaT368Bt5WzqpJfeznOPUrc4442yOGu5kqo8ie5Nc
fkfuwRcIZegBeWxO/cDbSwECYxJ145jmMZ84OfoZy89XQzbYvxKmytOJ/WP6mgMG
vpiUww6s04db6elPjNLxguSjjJFwCZrJQzR7q5x/JBduOx4LW+Bk+SyOZQlPNUj1
nYtdOidMEFZDNur6Q0cBFJV2sYAf9XH+RVjlpBAYocsOm0mElEk7HBqlS84wjDkc
nRoy9GlLP09fwyK2WbpkMTNFNjb6xAYfueyz6UIBtQcdT184k4Qq24G5Pm9j8aKh
lh0v3lPms7dEnhg+BpLCf//OyuAnvylwIcfKjN1DxOhvVC32aX65OZHlPtn/Wugx
kPtpCtxaaHkVWsbZWS0BOHuJWrltLVRhF0/mFtD4l8sj1UPXThyBn12oaUPwlQID
AQABoAAwDQYJKoZIhvcNAQELBQADggIBACqTQVtbiBI9TtFIlKbXdyNmMgnhfzbn
F+eHGG2T4omPKxJkkJe0cj7rNOq+em98Mnp4rZBpiK0SnrWk6afWv5LStnA4isnO
32jLXYSeYBSA7Hn1X54nCQJNfBXEnazLiam/l8e8NwB0lpqw6Rw0FhcPD5qS2pZQ
fXxgw8eUUwdLC73CgBsXJR0ybg1zir9x5OMkou+MEUdcRfoS95OJUcntWAOcC8la
Co5wMXStReV6HIMucGadeFizq9ypdYx/42OXoVBh/19dTXlMd5f8NEv8nx3JvFr1
mdcAXGHorpOfXxWI1TiTMcyJUSO3csPenUzCi7K20gupt8bk0vkU99JYSga92bWp
VNroTb7Z+fCWijLvTyJ0eAas4hDUURBzaQA+/jVy9AyIiRH1x0KbK1ZwYSTWoY/m
AaNB5Y7tSrXeyyPQUIrqCtR2kLNOcdLdtbs4p4ZQESvy9COqD4/8d5GOupCZ94BT
KBLIvSGTOrKwxl3PanvWKOgg2xYicab17uOLMvXVI39lcA9eJ/f9Kkb3RGUEBtUs
Ptn5uZNB4nz59Ou+Y9PS2UFOw6+MQfa1JlWnCpCxH3u3uIwjLRdKKxj2cauzTyJZ
qc5QdDoVsvP50qJeKrrlmtLnxgFa4vctcAbCZMulx87y1+UDXV8D4reW/5rMaenn
F+wyRr6sWtam
-----END CERTIFICATE REQUEST-----

**Comment by DeepDiver1975** [comment]
```
-----BEGIN CERTIFICATE-----
MIIE8jCCAtoCAhByMA0GCSqGSIb3DQEBCwUAMG0xCzAJBgNVBAYTAlVTMQ8wDQYD
VQQIDAZCb3N0b24xFjAUBgNVBAoMDW93bkNsb3VkIEluYy4xNTAzBgNVBAMMLG93
bkNsb3VkIENvZGUgU2lnbmluZyBJbnRlcm1lZGlhdGUgQXV0aG9yaXR5MB4XDTE5
MDIyNTA5Mjc0NFoXDTI5MDIyMjA5Mjc0NFowEDEOMAwGA1UEAwwFYnBsb2cwggIi
MA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQC4CPIuPnxj1xw4OoKjccQylaqS
Rt5LbVIkVTdE/KYzmHp27owrntJvfIJx4d+LrkFPLRdOQihz8SKhTHxg274pMbap
6lN+z03dsVVEzDhwtnLoTbx4P9vb2iLBjWEyJkcS0+SVJwKhvY+Uhq1qZdNS9mCw
RNcpO959Px2nVfhHB6JDfQ6yKLW+7ul1OcZkNCQlkHv8K1xVNedWD0chBdp3gD1l
teWQS1ibCCyGQPNi8ZL1ofoehURUr8/RD39c2Oi7Pa3PaT368Bt5WzqpJfeznOPU
rc4442yOGu5kqo8ie5NcfkfuwRcIZegBeWxO/cDbSwECYxJ145jmMZ84OfoZy89X
QzbYvxKmytOJ/WP6mgMGvpiUww6s04db6elPjNLxguSjjJFwCZrJQzR7q5x/JBdu
Ox4LW+Bk+SyOZQlPNUj1nYtdOidMEFZDNur6Q0cBFJV2sYAf9XH+RVjlpBAYocsO
m0mElEk7HBqlS84wjDkcnRoy9GlLP09fwyK2WbpkMTNFNjb6xAYfueyz6UIBtQcd
T184k4Qq24G5Pm9j8aKhlh0v3lPms7dEnhg+BpLCf//OyuAnvylwIcfKjN1DxOhv
VC32aX65OZHlPtn/WugxkPtpCtxaaHkVWsbZWS0BOHuJWrltLVRhF0/mFtD4l8sj
1UPXThyBn12oaUPwlQIDAQABMA0GCSqGSIb3DQEBCwUAA4ICAQA+5TdgSrOc9o5W
kdoqnDyZL/cPi2cEOV5+Ykorf/9SrhTn42vHmWNGF97TAozzXDyTq0XoX76iQldZ
B5ujI7a6k1YMjNNjpSsFg2Kz1GLsG8cOvB5BPjilgWuE5Vw3wmHXZu2QdHCQ1zeP
ulYNeAasFxvqwLVBhEPkCijQfPVHw+yX2+gxUUX8EoRSxskMvzq7WTeEkeE/K7La
NE6xBDSFWOPDYWK61KCV7Pr7vt2RQ/0pnnR+lBpYP5ljPH9FeMIXRRZFr5L0PVcC
dqnWNzgEnOFgCIkdnLWTJ/FQGa+bFB1aankmJ3tGt8lkhRxV031SmkHkKTn7I7wO
vXyvhbQpiM0mRUFw1GjAQKehpHL6BYG1k7dSpNybxXwiMi5IbGVMbTNrmdFQmZeA
eoh+jnowRRKRU4O3PRNGmesdaQKNqCk/47x8jZvmx3ZJ4Fds7+UoCy1/ri3ceDyv
BranEA6JoRfdeThcWpRe7vdlUyiO8acgeCDFW5e6hEHXN1HUlCn5Oj2ZbkPCtJ9e
fN2M7HpoIG2NFsOhvDUziaUVEqOyuMrnBZA9MSBN6g8xuKLwq8TLyv3eo+G9+xHf
XC29yj8KY/MOLVAM5VKhRCHnPVs6z2ukDj2BKY9c1xo1KwWg4Rlq6YQBdm+aJODA
I3MwqFI/EQUftgP4njObEtSRtFgyFQ==
-----END CERTIFICATE-----
```
