### ISSUE TITLE
Certificate Request for app metadatarepo

### ISSUE THREAD

**Issue by holzheu** [owncloud/appstore-issues#146]
-----BEGIN CERTIFICATE REQUEST-----
MIICXDCCAUQCAQAwFzEVMBMGA1UEAwwMbWV0YWRhdGFyZXBvMIIBIjANBgkqhkiG
9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1hnYzaBeQdjNh5zih3pFCrt8h3IdDxeo5dbk
6NEewcWiajcwUTnz8jwDh11ow807YHbv4R4zpnfjPEdXCICNjkzXT9/Ranu5W8IH
qdxzoj/rHfECA1SSLNcrx3RYTUddVDPDVG0FVc1chPPnqTL4C/zv08Ld72q5a2V0
xdWgqVgFwHZXdbKFQCtYsihYUIRKMjrq7HsuVYHCtmfdJSNyb8LguPgPlP0C8GSM
7uGnp5X3OnuphetC1sW/6ZdEimGU75VtgWl/iQzD0hzBpZWRlMJiZlQAgazh5lJ+
J7VZkLU/bnAbFLOvNyl2ZOO5+8jedeFs07gcynghk5zAQ7T0oQIDAQABoAAwDQYJ
KoZIhvcNAQELBQADggEBACwCeqolKig8sUToDKtOhMf9oJ0X9pg4tRir+AeNlAQy
xDpvbDw/XLBsaMg3MBYwpo5kdBjmn1A7r77sbp1e2xFeDFhQUbPzeatsxQxzCJSq
f7XFEgW1GH8Fjav9KimtX7BfxJqgnjxjEdN+8qra0PTUlW6LYUhQ7vBYG+XV21Dk
4/VSq8anV9Yc9gdtFDE5YSoGFpFw9Z2PfAghKZ/1ADYaKg1lz1zKZFAb+mjw84c+
2hIl53+66Aj3FgtqIwCqvXd1jd9ZSZXb5dRLxTrbs3w8SoRtFUbjI4vO5QhnwMvg
5y+TPEHigGfRk7vWEeTjm5+gHWmT2K+apJHh2wZ4a0o=
-----END CERTIFICATE REQUEST-----

**Comment by DeepDiver1975** [comment]
```
-----BEGIN CERTIFICATE-----
MIID+TCCAeECAhBzMA0GCSqGSIb3DQEBCwUAMG0xCzAJBgNVBAYTAlVTMQ8wDQYD
VQQIDAZCb3N0b24xFjAUBgNVBAoMDW93bkNsb3VkIEluYy4xNTAzBgNVBAMMLG93
bkNsb3VkIENvZGUgU2lnbmluZyBJbnRlcm1lZGlhdGUgQXV0aG9yaXR5MB4XDTE5
MDMyOTE1MTIyN1oXDTI5MDMyNjE1MTIyN1owFzEVMBMGA1UEAwwMbWV0YWRhdGFy
ZXBvMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1hnYzaBeQdjNh5zi
h3pFCrt8h3IdDxeo5dbk6NEewcWiajcwUTnz8jwDh11ow807YHbv4R4zpnfjPEdX
CICNjkzXT9/Ranu5W8IHqdxzoj/rHfECA1SSLNcrx3RYTUddVDPDVG0FVc1chPPn
qTL4C/zv08Ld72q5a2V0xdWgqVgFwHZXdbKFQCtYsihYUIRKMjrq7HsuVYHCtmfd
JSNyb8LguPgPlP0C8GSM7uGnp5X3OnuphetC1sW/6ZdEimGU75VtgWl/iQzD0hzB
pZWRlMJiZlQAgazh5lJ+J7VZkLU/bnAbFLOvNyl2ZOO5+8jedeFs07gcynghk5zA
Q7T0oQIDAQABMA0GCSqGSIb3DQEBCwUAA4ICAQBnVDZgX8JMfyCkVOq6byzf5Q1u
kpXLqZgqur3CvVthi9o/WqYaP3T9+E4iAXg78LWZtEAb+aBToG5eKbbx4cAmnnNe
+oGg3dG1f/zMDXYh1GTFzKskt31wF4ynX7Yb/Y4Om9WpD3+2W73GGBLcMs0GPxY6
as3CSStydtUZXtjN6U/JBgYFKatUT7fvQUCNO8YyBjQgCNrWJCEGja6YwxmxAyzC
x9qynBKJaLdGRSstmFmfwjEgbj7RH5LlA3K7CVw3SW2R0w4FkkpwjdZBvdH6KXYu
BAxTGPy9raXEPa6gsFJn3KU7JkH/J0H6QtRUlHsq+3wGegOGEdaFzg8DnVn4nZ+4
1wppnrmx05SrAQTtaNcbRCgnxrmBCrkbWUmAncBeISJC4G933PFclt9p2dw6kPPO
NegkzVl6zOQ3bEVHRAefu/mhDtaxuxsQftbXZ1fpErnpWP/KBSKXcIMb8151QGwU
ES58j0vIG/OrJrZj0INHyMEYRlfKRiDyuea6sQaXmBMwfrkYZUK+cMafBttqG5/0
K/kPZfvMXiGpivsRA7SGgJyP6fSyTzCAuAuO2pRFIe6KGMGAW38TBAPm1cSU7qxK
YT5HLY7KF1+ow9DOsSrE1y2suV/ySRKP7imgXYrzNI4wwLbxk7TDUjJZnLXYAgNK
EiLg1PNbs9x+P4p4Sg==
-----END CERTIFICATE-----
```
