### ISSUE TITLE
audioplayer_editor

### ISSUE THREAD

**Issue by Rello** [owncloud/appstore-issues#154]
https://github.com/Rello/audioplayer_editor

-----BEGIN CERTIFICATE REQUEST-----
MIIEYjCCAkoCAQAwHTEbMBkGA1UEAwwSYXVkaW9wbGF5ZXJfZWRpdG9yMIICIjAN
BgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA0SHgA5EOtT9DJYeSTtUS6CznjiHr
AibHQKK1azMS/BmNNAOWKmgxYAZ1sRdPQ7LbBu8s6bVGc0z8O6U4gcPOMnc8uMox
TJf6bt2qRHPMhIizR0ULqs/zh5R3ZhfSjaeMWSF9775HJaoxfLzCYHrBpQ/N3ePU
k+sEf8Ns6r//RiZQcL2F32MN2LQsqCqkEqAo4Y0eg9C+5FtgEFD90AUVIYOcO+R0
WXKPqwbuqIjQ7EDaj11vkGrkrjAvMZJe637l87VHUQutUxtYmqBWP2yjPqvdWToT
XN2RjOR2Yhb4yPuSyjx42mnMKeY1BYyUgfkrztcVDxXeMTLnq/9v2I2GD4bgP0hS
+mUYhIWzCREGU8j+azsF75TeGeSj1/ynCDV5APFj/GUKAmQIkxgbPCPt+rV5EF7u
0sIFEmx3pQrrZGtp+3XXEt0PIjOV3PpvALdCEjj7hkdr7Nz4hPL20VZgNbXApKTx
VkXgIzZ1KbN0h5avrxTjZ4Dcr7p++VRyQ+gd3MGfuJqWJBXI/Scrixy9Y92DZzKK
Dx5UCVvpGKg2roKhIGqzPl2K+QH0BAixMT4zKwnOhTFiTeMy6xEbnNwBx4Moz+Ng
TJSy2s2omaRHbAGgvMuZpkXPJAW6ylJ7jtuhWm8ssbU9T9iWCbYLJJC4axakWiTB
pSMsSz86M8ixka0CAwEAAaAAMA0GCSqGSIb3DQEBCwUAA4ICAQB4Is/ydIbsRlkq
IpHNL9N0vfH39Oey1dpS3OgI1E4zjn6hK9N1UuuJq7JvPAzT+91oOIu09RJEtVHp
ua69/nvGIQiZhyEMrOGvGtaLjUhNkPi7jPftAZBHQ/hWlgiBocLJS3BCTBI9fr16
8Tfrph/hr+bsCC52idp3DnCLyU3fcusJQtl1NDfsTUsBMB+aWl1cVGsHlNXortTo
VqUUXz0uhJdHV4UAoC4PKbaMYvrwlHkl91llzlyb8Pv5siqSMnfgpdtGozp5zstl
oUz2JiTd9N0ZapcobsApYdJNxi9WQ9L5DUv2lbNG+mxNaiN5l4HtsUHXPfTf+5qG
Pa3HNkdIlVjsq0ImkrwxlbZlNeA1RuU5xjgrw07dgDRreLFlntZwoZpf6DENuhXe
jVxZtrv0J+kZnRbOY2piif6aT+RXwcCnVwqZNc8WkBeD7rVl7QqptQFkLXftKV2F
wO9HTjfspKO1MNprn+zpIe7z8eQH22na6WgOexS84c1PUvllabNJR5YD0U8cOGgB
Ov3H1WCn3CQpXB8g5A1EzKANYsvqTy/S7Ex9G837+GY9M1jYSWOs3Auu35DKmBe1
cvWI9nylfqH4XYu5lnlk7+rfumNeQchaiqLJsyOm/Ml1hW7owwMGPNZB2PBNQL19
0IH5Q1rAdZclQaz+f0a2qr20oCsu8w==
-----END CERTIFICATE REQUEST-----

**Comment by DeepDiver1975** [comment]
```
-----BEGIN CERTIFICATE-----
MIIE/zCCAucCAhCBMA0GCSqGSIb3DQEBCwUAMG0xCzAJBgNVBAYTAlVTMQ8wDQYD
VQQIDAZCb3N0b24xFjAUBgNVBAoMDW93bkNsb3VkIEluYy4xNTAzBgNVBAMMLG93
bkNsb3VkIENvZGUgU2lnbmluZyBJbnRlcm1lZGlhdGUgQXV0aG9yaXR5MB4XDTE5
MDcxMDE1MTc0MloXDTI5MDcwNzE1MTc0MlowHTEbMBkGA1UEAwwSYXVkaW9wbGF5
ZXJfZWRpdG9yMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA0SHgA5EO
tT9DJYeSTtUS6CznjiHrAibHQKK1azMS/BmNNAOWKmgxYAZ1sRdPQ7LbBu8s6bVG
c0z8O6U4gcPOMnc8uMoxTJf6bt2qRHPMhIizR0ULqs/zh5R3ZhfSjaeMWSF9775H
JaoxfLzCYHrBpQ/N3ePUk+sEf8Ns6r//RiZQcL2F32MN2LQsqCqkEqAo4Y0eg9C+
5FtgEFD90AUVIYOcO+R0WXKPqwbuqIjQ7EDaj11vkGrkrjAvMZJe637l87VHUQut
UxtYmqBWP2yjPqvdWToTXN2RjOR2Yhb4yPuSyjx42mnMKeY1BYyUgfkrztcVDxXe
MTLnq/9v2I2GD4bgP0hS+mUYhIWzCREGU8j+azsF75TeGeSj1/ynCDV5APFj/GUK
AmQIkxgbPCPt+rV5EF7u0sIFEmx3pQrrZGtp+3XXEt0PIjOV3PpvALdCEjj7hkdr
7Nz4hPL20VZgNbXApKTxVkXgIzZ1KbN0h5avrxTjZ4Dcr7p++VRyQ+gd3MGfuJqW
JBXI/Scrixy9Y92DZzKKDx5UCVvpGKg2roKhIGqzPl2K+QH0BAixMT4zKwnOhTFi
TeMy6xEbnNwBx4Moz+NgTJSy2s2omaRHbAGgvMuZpkXPJAW6ylJ7jtuhWm8ssbU9
T9iWCbYLJJC4axakWiTBpSMsSz86M8ixka0CAwEAATANBgkqhkiG9w0BAQsFAAOC
AgEAxZpLxl4tf2itJOrKAMTAV0ou/WXewML5HAzt6Gg+zkWrXoDsMoNwrOOXo+UE
IKI9sxKI2h9SscPrCZ25IoG/ryWV8oMuypKIFeVlWBvhuE+dEinAfNahTXWLu9hE
EPVEffh62xxx5/PAsUNw8+Pjh2lBMOuHvABwWPpCcJLbBGZCzaafq7BQ3bXDpvA8
qw4PWlm2OkMO1ltv19q/uVaOYI7EpAvQRV0OM7zGZIeUbSejemeg9b4aMlp/94VS
IlMz/J3yfAEvXfUvv5u1mOl0gfhVPy+7Dr0p6teoSjbAKgl5AGwzru6hQqG/SJ+q
zwWM4pwSQW1vOb8GAMgibMxRmZqs+xzY5H0LygOD5GUTC2eK2XxxeGdjHzuDFvuz
K/hPzKP6m9STf36kC3+Q8niD7MZY7kxlUc4GF3fpjuxQyu9atnaLGIkHI7+qlOOI
okrLdfFT0s7OJUzOeJoGkT8BGCaFz5+0QvwNQcPKoiSTUx4j4Qo0KixK5IRCTdoC
zxl3NxXdHe37ODxJ/OJwz8hYLyAAd4PbfiHWA0Y3QCQmqWkAtrB84FcOQWrPltT6
kpAKlv6Pt3Vdr92pkF8qV2jkdKjnfbg1hFTpwO2rati0XxlblF5xm9FTYt/5nwjg
wJEiIqJdzpNpRa+aNyLnxmy2KjA99KdB8hv1iFarPbncVyo=
-----END CERTIFICATE-----
```
