### ISSUE TITLE
audioplayer_sonos

### ISSUE THREAD

**Issue by Rello** [owncloud/appstore-issues#155]
https://github.com/Rello/audioplayer_sonos

-----BEGIN CERTIFICATE REQUEST-----
MIIEYTCCAkkCAQAwHDEaMBgGA1UEAwwRYXVkaW9wbGF5ZXJfc29ub3MwggIiMA0G
CSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQC/85UkjmS+df/SsiQhdZCYBkczE9uB
bjdPdRK5K3Dc/NYcm0EY84i2l/qB9WgBEI0ULbrmK3bozqO8yi1huv5vQ17uiAEC
enNehztmRtFZOJeQSRDxFccn9G9FpcX7cCXlrkW9lJw3aj5Ispg2xcDCErVKlOEr
RPnd1tVTVXLhuRLP595zAqP1iv6qrn38PMigVpnzhGMvU6jm3ifw6Uf5yd+aVYeQ
sqHiVWgvZ0cR8uZMiaEP4/pL7uB3ojBahm2fJtYdw3w+EhacK0dIO2RausgO0xe4
p8KXz3CkjMxNVICEShE9JqTAWCzLy5fe0ebgnC7IYPFjNa7u9oHMDW+FdzmP4Qs0
8DAwxhxMhOq/8/jFjb8s1kdcVeDdiEufJKpfy7A1ySX5OcsaJjqL0RUzJV5K0AMw
InuyxTRfV8IQHljHEmIsqfU/qBme4J0HsrixPRAN7IRxhUQNGFFKZvgiwbEbQYyW
VOg0psS8o++Wi3cINlLZxLUdaBSAQG5/Nnsg54wSP8hosHeuTLTLfYOIuM3Bf1hQ
I89qIcAfRiQ3BdwVwdprmsXJi3dSj1Xw6dyIQqchX3buyQXmCzvUXg7Rsb1ztu9k
Ov6B3F7zcutA8OR4V0hiSUk1MxprmcierYPreGf5THlx4tWy/UX8ELeOHsSoznc2
zKbDKZeoV1aNFwIDAQABoAAwDQYJKoZIhvcNAQELBQADggIBADcwBCoG3EcxLSom
YKsjfk2VVYoAzpht4nXW7Dr8QIpl1lteLri+v7DrjRR6slR0DGKvGOXwElRKqQ8P
dpEazRLJq447LLijmd7H5N2fhLOs0DzciV1rdh3HrnHM3hAHxZxfx32u19pJK6Ut
JEVHw4KT9+RQTGsyzoToEcJBQcMIDoNtAb4nExjpzJ81Cb9VzuXkrrjtGrBqpW2u
HobLcIn5c6Uk+1LHnAsYoxrLi4HcF2PE90ewkBsVTiNud+prtPxroKxsGSKr+FbC
FPCkT43I2sZjFSwyV8IudGXOr6TTR2xwyIoNxuWj5stO+ALrmKt5VhBZ2DpJChlm
gr9dDO1M3rthYrowbJeSEsRHmXieII2IbOpcYaLfrhaA0kU/memovmDp/T3hyfNQ
F+ogFDPfMcclZJ7hfBsPydi1IKzQEwJF0MHtu4Mr1hcVLE0CfM+FEslGkLiZGzMe
mErMc0/1M2TB1+NNL57qbjooTGERe8nmFVXSqKGmdGJN3XMGbuVRKkL/R5RL84Hr
z/ZH4samAqwRrbI4Q3RrgFBkbzf8b7rR+4+F91D3zo62b+pmJryT9mQeiA8xGqK9
WXJcbWEvsVwcd/O+2E74c1pmjOlxX13LjuMpYa7KROTWo15kW0kyCMOC6gskEZYT
Uz+vRh7E8BlMATsDF8GFUY6J5Zis
-----END CERTIFICATE REQUEST-----

**Comment by DeepDiver1975** [comment]
```
-----BEGIN CERTIFICATE-----
MIIE/jCCAuYCAhCAMA0GCSqGSIb3DQEBCwUAMG0xCzAJBgNVBAYTAlVTMQ8wDQYD
VQQIDAZCb3N0b24xFjAUBgNVBAoMDW93bkNsb3VkIEluYy4xNTAzBgNVBAMMLG93
bkNsb3VkIENvZGUgU2lnbmluZyBJbnRlcm1lZGlhdGUgQXV0aG9yaXR5MB4XDTE5
MDcxMDE1MTY1NloXDTI5MDcwNzE1MTY1NlowHDEaMBgGA1UEAwwRYXVkaW9wbGF5
ZXJfc29ub3MwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQC/85UkjmS+
df/SsiQhdZCYBkczE9uBbjdPdRK5K3Dc/NYcm0EY84i2l/qB9WgBEI0ULbrmK3bo
zqO8yi1huv5vQ17uiAECenNehztmRtFZOJeQSRDxFccn9G9FpcX7cCXlrkW9lJw3
aj5Ispg2xcDCErVKlOErRPnd1tVTVXLhuRLP595zAqP1iv6qrn38PMigVpnzhGMv
U6jm3ifw6Uf5yd+aVYeQsqHiVWgvZ0cR8uZMiaEP4/pL7uB3ojBahm2fJtYdw3w+
EhacK0dIO2RausgO0xe4p8KXz3CkjMxNVICEShE9JqTAWCzLy5fe0ebgnC7IYPFj
Na7u9oHMDW+FdzmP4Qs08DAwxhxMhOq/8/jFjb8s1kdcVeDdiEufJKpfy7A1ySX5
OcsaJjqL0RUzJV5K0AMwInuyxTRfV8IQHljHEmIsqfU/qBme4J0HsrixPRAN7IRx
hUQNGFFKZvgiwbEbQYyWVOg0psS8o++Wi3cINlLZxLUdaBSAQG5/Nnsg54wSP8ho
sHeuTLTLfYOIuM3Bf1hQI89qIcAfRiQ3BdwVwdprmsXJi3dSj1Xw6dyIQqchX3bu
yQXmCzvUXg7Rsb1ztu9kOv6B3F7zcutA8OR4V0hiSUk1MxprmcierYPreGf5THlx
4tWy/UX8ELeOHsSoznc2zKbDKZeoV1aNFwIDAQABMA0GCSqGSIb3DQEBCwUAA4IC
AQCAYjvq0M939p0ae/NMjiT0XcGYxdaZuVh4SE1vbT0XS//7F5Z9OXy3AzJCD3HI
vmiC5rfmsBhtPFEh7c1PmiI/dIRuUmEQ3wjSgmo0E4xeTIrQ3s0wlsebDQHwMM04
bMozexdCDp7bzm2yT45XhJ6Sgr5oGIlkdkzQrucA1akGoOtRbhiZ6bzeheg4t5YS
ihvauiTWtixyqRHeUtIRFNRUMkgbpUhzmusMssnH7N4M2qXPyjJXiH0vrKcVxvS1
0tGLrZjEtAMfIAspiR07LbSKhvk1EOLhHuPcMviIjBLqG4F13eIMGU5cnNQkTbhr
mCa3k6l1WZYBMaukZCtUc4N41KVV2p/3spRis0M9d5PmRc3OmMXsajEMpQxlaT1O
XRyOhF2atquckl9Aw6ENwPsizs4Ll77aMo6sy2tRE4Oh/Wn7CF3byZfrguyfFmcI
Mz+gMk2jbAdz7PZrPOIDMIqPGVmugAAlS8lcWuehj7U7MK3unOcJdR/rdicg7Uuh
d1ieVCDV7wkgYeD5IUzS8fU43kP1oeOHM3A+kllvcb+yyN3qAuaamOnlZGz5ibu+
2Tgt77ab89zYF/zLxjCOVknu0bnkCLP0u0bhXAj2A9R5dG5lCJcQ40K0Td/SZ4pT
WZm9JHOsLvyEX02beQFwlmKVtdIxQnwvH4U+CYTQ0+ywNw==
-----END CERTIFICATE-----
```
