### ISSUE TITLE
files_audio_converter

### ISSUE THREAD

**Issue by prsnbrg** [owncloud/appstore-issues#156]
[https://github.com/prsnbrg/ownCloud-files_audio_converter](https://github.com/prsnbrg/ownCloud-files_audio_converter)

-----BEGIN CERTIFICATE REQUEST-----
MIIEZTCCAk0CAQAwIDEeMBwGA1UEAwwVZmlsZXNfYXVkaW9fY29udmVydGVyMIIC
IjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA2CL5VLHSUbv3xnjCgl4BeHVJ
siwShgsHCKjG9IHiaxVTqME92lDGdiM5fzfJSbfXEi51OP1pBVJ6cQbKJWin0OBj
Am6XeP7rhaw26zxquYF6P+oecsni6we2cYWlKwb3GWACmBV07gNpIHERoWYoDcSv
TIuUPwm1/OVOGJfiMrfMBDO4b1w98+TjgTWyAy7RHcRK07de75lgjh2AEOLzjqi1
RpyZ9YkYvKSCUZ5HMhn19tcy40UCgCbR8/obVBLQdP6gXzEU7xxpGY4w3kqG85ze
0n8UCeeJXsmsNJSJ43eTZNd9IP5eGXOCz5ya3tgqvEIwL2nQRcjUoda4/8bvdH73
fV6p0pH0ESZTHTXz6pFEuYt1hiN2mrQhzRcmkbVioY3Z61DiHI/l7FdtH9xok1IW
qTqqdUkwwYEcM2jH29LZQvoFilxrGQf43io7O96HYB5lrbRkDgTzG1FZG4n3MuxJ
cR9HNpRYJJmSKP1gxwiOxolUkNoaG4ZnM8I3pDD+DQLZuP5j+Y/At5cjl/QyyvqZ
kjbtRsgt+IJI0r1cYGJ25V4vvhnsepO8j4zv3AdAHE/554+TDVRZqHcS7+gShm/7
OhAty4W2BWRS3OjPStpZvmvxfS0yO7oZrTN3xgpudiD8c1R9O9jPX9bIzmSJjSd2
kEbIuDyBcmkTTDTylgMCAwEAAaAAMA0GCSqGSIb3DQEBCwUAA4ICAQBSemmOUpb4
jbZaN+UIfKX/u57K/s1Wcxe2oNduxa3pzqPgw/Mh/iFpmM4/bIwiKi+3O1Kh4OEs
aBlDShlysEQyozLEZKhXkPX//lwAkZE7lRC1ohYvHUeCaY+rvJvs7Xm+sEppiTH7
lz+eao9qVBIwDVTJnKMXG+VjC8tKyr8IXcfRETrKvrJ8h/hsEDeL3TfHUUqwIsDp
pbh5ousn2eLy9jrpdQrT/oIPPPsnAajbNjlCJeVjQydhniOL38gp+d8CUYpWdGd6
GTf3bqYf9oKoggaQVU67GHrx5d4ftxnoj6IzEQyiY+VQnRBxvXEEXJAf6MmJZtRW
MwsoOoHCE3+N+J1/Sv+/qX8Zfa9Vsy/9axO0BzvgP9vMR8CC3yI6Js8NR/Xm/m1p
piIVO+Za0yYtSN1DNZWPPoYhgLugl+5aRCKt6GtRTUlTgI8iGyftbtidt2Zpz0lW
MAEWzPGvVD2nZAfSfGJid1GJRb5WR15t945xX0cy0tBZzTHvHf+1TrOVuuX/8bqr
4/bLKyb5iPHC6TBdBQTPUM8ltswJOsC8ICSw1eFircpMAMsJUtqwurefsh3W8Qsr
+mGd+qLxOQOUzjWgxbqURJAicEBKxfgI3kGBXgUygeetW7NUnHgMx7YoErww0urT
sYIdqeUcoCGPCt9m1BnXd33B1HxJ7JOHKg==
-----END CERTIFICATE REQUEST-----

**Comment by DeepDiver1975** [comment]
```
-----BEGIN CERTIFICATE-----
MIIFAjCCAuoCAhCCMA0GCSqGSIb3DQEBCwUAMG0xCzAJBgNVBAYTAlVTMQ8wDQYD
VQQIDAZCb3N0b24xFjAUBgNVBAoMDW93bkNsb3VkIEluYy4xNTAzBgNVBAMMLG93
bkNsb3VkIENvZGUgU2lnbmluZyBJbnRlcm1lZGlhdGUgQXV0aG9yaXR5MB4XDTE5
MDcyNjA2NTAzNFoXDTI5MDcyMzA2NTAzNFowIDEeMBwGA1UEAwwVZmlsZXNfYXVk
aW9fY29udmVydGVyMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA2CL5
VLHSUbv3xnjCgl4BeHVJsiwShgsHCKjG9IHiaxVTqME92lDGdiM5fzfJSbfXEi51
OP1pBVJ6cQbKJWin0OBjAm6XeP7rhaw26zxquYF6P+oecsni6we2cYWlKwb3GWAC
mBV07gNpIHERoWYoDcSvTIuUPwm1/OVOGJfiMrfMBDO4b1w98+TjgTWyAy7RHcRK
07de75lgjh2AEOLzjqi1RpyZ9YkYvKSCUZ5HMhn19tcy40UCgCbR8/obVBLQdP6g
XzEU7xxpGY4w3kqG85ze0n8UCeeJXsmsNJSJ43eTZNd9IP5eGXOCz5ya3tgqvEIw
L2nQRcjUoda4/8bvdH73fV6p0pH0ESZTHTXz6pFEuYt1hiN2mrQhzRcmkbVioY3Z
61DiHI/l7FdtH9xok1IWqTqqdUkwwYEcM2jH29LZQvoFilxrGQf43io7O96HYB5l
rbRkDgTzG1FZG4n3MuxJcR9HNpRYJJmSKP1gxwiOxolUkNoaG4ZnM8I3pDD+DQLZ
uP5j+Y/At5cjl/QyyvqZkjbtRsgt+IJI0r1cYGJ25V4vvhnsepO8j4zv3AdAHE/5
54+TDVRZqHcS7+gShm/7OhAty4W2BWRS3OjPStpZvmvxfS0yO7oZrTN3xgpudiD8
c1R9O9jPX9bIzmSJjSd2kEbIuDyBcmkTTDTylgMCAwEAATANBgkqhkiG9w0BAQsF
AAOCAgEAT7DquUZYrAgzmAQus9P44Tq3ehAC5SX2LiTiwvioChM80WQlOqSTU4mz
bGYpG5wNqhtv07uHRu1jLp8AEKpCERxNjbEQLgQjVxYhiLN6NsNsXeF5UKjSYN3r
OgCC/WrXzcqFaWpx2oqWdpzGHShni2ezN7Fpwm70RLRHKtyputWua4GS2OocteeY
WPD9Ahmx53h3aOtLWwXLM6MLprmZ0sIZaEb4c7gcvav546Ni+EfmNpRHhFrBfVVP
Skj2AjjXIf0UZbtvDfPcyDRFdZH8Pne9XpRit+n5nrlFGWDzpMgOD3wVB1UT+jIh
mmx8Go5sJMvpWMNT3nCtZC2ek3+SbmcohUzcRo9IPHtZqkOtbxhWtQrkkkW25ipR
mx0hEuKII15Uy1aVTQJxnoOCsaur/feTNqcDrmqIlLtQga2YwdHhQXj92NXoaqNC
fZc1eRMbd+FHtxNzAUzb0A1cF4QcQZWQeKKbUTxEt2MvuazbfXeW/uaD00pH2U7c
chJmSsi6gnh/tOKLBh0lEdtt+wrZB+lBAItS7StNLamYol/v7camMtCqtZYUZXt4
i3cKQw2k/CDXpd/5o+xEHtXmx0lLliYPUQKGbRWYrnFANub4/XW1E4Wa0UPSHqqX
xt5BYCs54IDJbjJKz9NG011oNwgNY9TBBPdSQFmwaKTvEBtPczQ=
-----END CERTIFICATE-----
```
