### ISSUE TITLE
Certificate request for Metadata app

### ISSUE THREAD

**Issue by gino0631** [owncloud/appstore-issues#157]
https://github.com/gino0631/nextcloud-metadata

-----BEGIN CERTIFICATE REQUEST-----
MIIEWDCCAkACAQAwEzERMA8GA1UEAwwIbWV0YWRhdGEwggIiMA0GCSqGSIb3DQEB
AQUAA4ICDwAwggIKAoICAQCvU8isW6sDrmKUfG7Cpwm5DmxOVvoXKdZZBD4fkXRb
UxCMuf5MLiTikgdNBQObkNOL2dDM6zDitNQH6e9YQ2hv4wRgKeE0UGuZxYkFJhhH
SaZcjmXNLFKUi0EQ6rZ0gu4H3BrGUNKRCUTfCo+k3sz8vxaEGfnUsA0F9Dt0U+yh
vmWGxLeZ+5gJCZcM691ZqbwfQ9n22cpNjs6/Ti8lyd2wKE+mOaqs71OWiy7tf8lq
RytbV56Xi1u5SehO6GY8NlIoTBrBGQiCYLyEx9JdJh/jUzOtZkcIyPkH6QtfDBMm
hz6LDikdsxXDPHPUkg6dl9Xp5DMd0hwNXllHpckDD/iEXZ5OpVik3qmI9Ja1hPch
JUI5Gcfi4r3bowISkGrLGYYvLgVztVNKF8YphEkRAmGPza4vKFLpQJG5nSKT0WKF
e+/KRonAbF3+nPkNrrQ2wiFtNCZ4i9vGo4db8mdYPrRj7CTC+CcymACBtxdE5wqM
Srhp0AK+tmgVIWuMf9M02O9X8sT1L3XbrjCohdV0D/8TJwWDtU2UzYrCD+PSEa8y
USTeUI8YGj7sGBcSGYkJl3aShSEmh2VcN6qO8TXNJtQNsxkqerWB8Nxjobehg1Ih
dZx+R4N6ip60rNCwy/TWCUZ5qZpTadUvl2Ff67PpTmr2z68DLrgb1844SO9XlLqX
fQIDAQABoAAwDQYJKoZIhvcNAQEFBQADggIBAJb+DVCGJk1mn6cgVDcFAdrQhbia
WZanagJLiXNKxcVWeHJsJSf4MVmGqVsZWbBnixBoN+kLt/6BYGxVQBVduvbkNfmr
gpKbUlWeEbIQ5raPh6mZBfl+LsgU7wiGZh6A+1JriGPe3KuECOFfB+ssDbgCXRlv
mlzsau5eedkroSUWFbT16MirfEiqGI2d0iSYUwqI2ZhuO5IBlTjl2zap6SRe5cFH
bB6OjLp7ZBP2pMnmYc6d/8DT7Rwlwmk074qquMGYzT0sDI3ZKHrCqp+KXG2AlY5w
NywTmZ8ToEr2/IMTwaTKBFFP1f0SFvxHOeSdVeZxH8v7xtfF57kcK28elLuEehza
lgZGP+dCC/BmcWpuAhHS0M6TR0kWVW+c7/nHdVyHZW+5kOMZ3kqVUHYWSV059SAP
VtPy0oYuefxYQaAa5Imca2GO08YL7OExW57gGspb8BdryPiCGnHclg3xb+ej9b24
pP+Bg+PxdXgrMaaNYQrfQcwTy1OQOpZ7oBwvuqld4Z4P+bd4tCwOS4vnqNTxFjNW
GxT0Y3IXto9yTnA2pW8sn1FkwOgrW6JH4nnfEUTXzAoNAX0GpySJ5fWu5BqnjRsu
6sdIARPu87/Ee6EgBHlxRuGXxAC7ZR/d2r0KEnKDanD+NAzppBuT6FwDTd74sOey
FgghEVUHKAmia5vQ
-----END CERTIFICATE REQUEST-----

**Comment by DeepDiver1975** [comment]
```
-----BEGIN CERTIFICATE-----
MIIE9TCCAt0CAhCFMA0GCSqGSIb3DQEBCwUAMG0xCzAJBgNVBAYTAlVTMQ8wDQYD
VQQIDAZCb3N0b24xFjAUBgNVBAoMDW93bkNsb3VkIEluYy4xNTAzBgNVBAMMLG93
bkNsb3VkIENvZGUgU2lnbmluZyBJbnRlcm1lZGlhdGUgQXV0aG9yaXR5MB4XDTE5
MTAxNDA3NDYwOFoXDTI5MTAxMTA3NDYwOFowEzERMA8GA1UEAwwIbWV0YWRhdGEw
ggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQCvU8isW6sDrmKUfG7Cpwm5
DmxOVvoXKdZZBD4fkXRbUxCMuf5MLiTikgdNBQObkNOL2dDM6zDitNQH6e9YQ2hv
4wRgKeE0UGuZxYkFJhhHSaZcjmXNLFKUi0EQ6rZ0gu4H3BrGUNKRCUTfCo+k3sz8
vxaEGfnUsA0F9Dt0U+yhvmWGxLeZ+5gJCZcM691ZqbwfQ9n22cpNjs6/Ti8lyd2w
KE+mOaqs71OWiy7tf8lqRytbV56Xi1u5SehO6GY8NlIoTBrBGQiCYLyEx9JdJh/j
UzOtZkcIyPkH6QtfDBMmhz6LDikdsxXDPHPUkg6dl9Xp5DMd0hwNXllHpckDD/iE
XZ5OpVik3qmI9Ja1hPchJUI5Gcfi4r3bowISkGrLGYYvLgVztVNKF8YphEkRAmGP
za4vKFLpQJG5nSKT0WKFe+/KRonAbF3+nPkNrrQ2wiFtNCZ4i9vGo4db8mdYPrRj
7CTC+CcymACBtxdE5wqMSrhp0AK+tmgVIWuMf9M02O9X8sT1L3XbrjCohdV0D/8T
JwWDtU2UzYrCD+PSEa8yUSTeUI8YGj7sGBcSGYkJl3aShSEmh2VcN6qO8TXNJtQN
sxkqerWB8Nxjobehg1IhdZx+R4N6ip60rNCwy/TWCUZ5qZpTadUvl2Ff67PpTmr2
z68DLrgb1844SO9XlLqXfQIDAQABMA0GCSqGSIb3DQEBCwUAA4ICAQAh84eFmgza
lopXp79AY00ge70/uVYZ330a1ELZf7cA/f+poxCKsTwuQVokS3g29nJ1a2uZ9UBZ
8PCykEoUA9pKxBOnzdcMnpHObXdsc4ojQYduZZXJLmARpCL2gSxc6cMzGXiFE4Dz
SCIVVk5tJLm40EJmtp6n/ToeDddM8GceQ7oZ9XQDDPB4vR99DC540kUtzA9pHJBK
cuj/GSnz2ZuWX11NiyIsVxkpTuF28kWiLlonWPv/DR/0GHRGwZQh1UdlmrVBDRWT
ni3Xd8/1pe5qH1kKnkb8OSh2c3Pu3H6wojFEOTsUOlYZib9FsVGwaVyC8N4uY25M
ONjy9UF/oWzj6OGpXzl2REqegft5/HNrqURnzujou30gHx8PtPshKusP4ngDXXMx
I+9qa28Mo1dGiMsBMg9QZBMVBlYSQKFxqtxfxw0bxXKpmHi8fu0l4cXhcYmTcbr9
hOfFJu+Np1eLv4YHxeyPpciuEYmh0XT+ybI7uv/Khj6zW6bcx3qxhGEEKgsx4X69
lmWALsQxVLPcVzEqAHvNHI8g7eHgtCGn4MeXILOzMslWV7vYFGJWjfuFpIwoyBo8
SUihohxxobdD1z6fNuaAh312RKvi8E+VLLSl3ddEbh4EHaRtrvknP3qQYoK+PZ1K
wF8w9yLtEk2aEkwaD/gLPtj3B8Ytqd/aMw==
-----END CERTIFICATE-----
```
