### ISSUE TITLE
Signature request

### ISSUE THREAD

**Issue by MageBlack** [owncloud/appstore-issues#160]
-----BEGIN CERTIFICATE REQUEST-----
MIIEXTCCAkUCAQAwGDEWMBQGA1UEAwwNYW50aXZvcl90aGVtZTCCAiIwDQYJKoZI
hvcNAQEBBQADggIPADCCAgoCggIBAPp7ZYruc0BlI8G+At8T/+m9bqNXFg5JQWwl
HLYejq5OyOinhgYUZNtNK75OF7oy7Q41ZwkgGhTDxD8uo24pdW8QSneyvVqWQ0S/
OpIU5oMiB3RP+f4NploCP2BDE1Q0AxHfjpFtO3tVwe0ZWb/SSMIhzUxumQBzqCcP
s8Wgw7JTtDz7YYjnogAHeTPXCBWLnGCq26ps+sJir+0ci1M2sUJRgXtgMPkP49OY
yo9zXHNAgrBMk+SftINTQffVgSFFJrUqlPq+HsfqWX6liCEGDZ+14aeYkb2QRNCc
4nIugQThtQT0mfDTx7NJNCxTaODbls596r7+RH4OCMftwzz5zsPrEgLsKAqoQiYk
sTm0mEdAUqvZoKPVz3CzBdq1rUHKZH4IsfpJzBEYks62H4s4N8/Ly8IZOxEOq7QH
eYhTwrLwU1U2Cj3Y58Fx2wGeMU17EjPj/DD80MpqPJBeVicok2b9zBQMallNLsuC
xuuANWjDiHXPCf9uNRavSxO4kJi8O1IhZ8RmB0bHlO8X5FvZ9UOKobREwEDseGDQ
Vth5fs8xGeX8wpPvkFR9rHsDPju8S7q9YtjnaD2aiPqDGDPQOFzYPPDTxtAxbO5B
y7F8HB5VSAygxYh3+zRwYCeg3QpE+cditS/V4S7DnRsse9pqxW7evdEAfrXXXaQH
YBOa5dbtAgMBAAGgADANBgkqhkiG9w0BAQsFAAOCAgEAcAf6LyapnQTlQJxcF6Ix
tzku0zw08wpjRJzPlUKVZcsJYxIG1Bu1RqWCdX67tR0YP9s9J29n4dzwFYa/wRL9
w+UKy+MY9WMOpJLP5Drh7Imi72i4nhs05jpkvD2miIyx1crje2yEOx1cVSTZDML/
DqAv6wviEJ/E75RlTAZybIymtoBH+NzBIClPjePiXWBp1UM/3Bk2pOOn2mIyadtT
gr5hou5fknjw6cdsaj0J2C2uZ375aJRotE0cMrBf9R/dIN+h4pBeDtDKf9Np2IVx
mW0X24KJue42WOQFfpINk1Pd8YVfuVlg3DK7kZWI9PQgib8DjND6G8C0aSA6CSwx
lKrCB3cRMBIvNp+Iak/zLyk8rMX8K42MwFkF/6Io9D5B1Uzkull6D6ns2PyYOqy9
W88rd6TEq/UDpKp8WGwio5PjvtijlG1/R/osGXQ897YSTmDEbDK2TNwyg0DhlOnm
6MhJYwSy7wN3w/C+9tu1rZ6aroTKncumPtq+PmbeDhMTUK6IrY2ohyaKLnVSb1B9
UEOU3te9QjcJJjO1eLmmuTcWEdqQ5m1WbeYvVDyjVTKJ9W6MuEBMK3v68JoHwb4V
zVThcWwkWyfBqUibyqck10t0s3+tfhGCYzXNSsvnr6IR8/69xFclaUQ4i03ijNLv
42fGgbKS9K6kRqODhPo5TSU=
-----END CERTIFICATE REQUEST-----

**Comment by DeepDiver1975** [comment]
```
-----BEGIN CERTIFICATE-----
MIIE+jCCAuICAhCJMA0GCSqGSIb3DQEBCwUAMG0xCzAJBgNVBAYTAlVTMQ8wDQYD
VQQIDAZCb3N0b24xFjAUBgNVBAoMDW93bkNsb3VkIEluYy4xNTAzBgNVBAMMLG93
bkNsb3VkIENvZGUgU2lnbmluZyBJbnRlcm1lZGlhdGUgQXV0aG9yaXR5MB4XDTIw
MDExNTE0MjYxMFoXDTMwMDExMjE0MjYxMFowGDEWMBQGA1UEAwwNYW50aXZvcl90
aGVtZTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAPp7ZYruc0BlI8G+
At8T/+m9bqNXFg5JQWwlHLYejq5OyOinhgYUZNtNK75OF7oy7Q41ZwkgGhTDxD8u
o24pdW8QSneyvVqWQ0S/OpIU5oMiB3RP+f4NploCP2BDE1Q0AxHfjpFtO3tVwe0Z
Wb/SSMIhzUxumQBzqCcPs8Wgw7JTtDz7YYjnogAHeTPXCBWLnGCq26ps+sJir+0c
i1M2sUJRgXtgMPkP49OYyo9zXHNAgrBMk+SftINTQffVgSFFJrUqlPq+HsfqWX6l
iCEGDZ+14aeYkb2QRNCc4nIugQThtQT0mfDTx7NJNCxTaODbls596r7+RH4OCMft
wzz5zsPrEgLsKAqoQiYksTm0mEdAUqvZoKPVz3CzBdq1rUHKZH4IsfpJzBEYks62
H4s4N8/Ly8IZOxEOq7QHeYhTwrLwU1U2Cj3Y58Fx2wGeMU17EjPj/DD80MpqPJBe
Vicok2b9zBQMallNLsuCxuuANWjDiHXPCf9uNRavSxO4kJi8O1IhZ8RmB0bHlO8X
5FvZ9UOKobREwEDseGDQVth5fs8xGeX8wpPvkFR9rHsDPju8S7q9YtjnaD2aiPqD
GDPQOFzYPPDTxtAxbO5By7F8HB5VSAygxYh3+zRwYCeg3QpE+cditS/V4S7DnRss
e9pqxW7evdEAfrXXXaQHYBOa5dbtAgMBAAEwDQYJKoZIhvcNAQELBQADggIBALIu
mR4/tHav+IV8Yz1iShEYPC/hNjJEHHgRui8i9r3RurYoPMfyE7hYGGJGmEK73nB/
fNvnpXWmS1LMwqb8isRTrddx4mDVrg6i7B3DsigSOh6uySIVPZ0AE6Kz7CQd+SEN
DSJSpJQk5p5p7zWqGHTJX/Lkr67Ppr8DPTq88199ObaU0W8pnFLeBwtcaNYi1xDg
UIjYMwPfd6+h1Q6InFYZbet9+gPH7KboQpRt/VyQ6qgPCfYzz0kfVjXn98d4RFCF
3qL1KFdEVgRMS/6cX7DK51ICX+de1X+HpDyzfuhKLVD11hYRIfMUj7hZMb1eUUCG
zGROqHOciFHLWTBgTEySz4pS9euGGaWIFmSbmiVkY/1t/zThWi+56lEg+nlleAxe
NajsH+grndVwhaZksuOGSAeZQpggMF1WplrWM9XjfTmyZH1txxSbyhXfrhp7DKg0
nmaQ/be6XAN5IRizSIbZB98dj8gpl/F73P4SIEKIiQFgIam0izdmbTKx08W5XmUq
08r8LSLzLAiUsJ5p1y1StovN0Wn9EgYrsZoPC1+p/exixKaI4yS902LlX1Z2cUEP
z2oQp0JCvFpTnliSU/dR2iausJc3YKJ3LJcXzZsPLaPbU56Q3kSKL09CEWeEvd8K
zRctqkR8Ul4vd7fJwCPCw3yU5K+ellEaJuKoA/g7
-----END CERTIFICATE-----
```

**Comment by MageBlack** [comment]
<3
