### ISSUE TITLE
Signing request

### ISSUE THREAD

**Issue by everscreen** [owncloud/appstore-issues#163]
-----BEGIN CERTIFICATE REQUEST-----
MIIEXjCCAkYCAQAwGTEXMBUGA1UEAwwOcmVja21hbm5fdGhlbWUwggIiMA0GCSqG
SIb3DQEBAQUAA4ICDwAwggIKAoICAQC9upxG2LXlOVstEeEwKqzYT4CNX0MRnNGl
NlxDAuDbrkNYuMPJn2cZIlGuzM1xaux4KqbaqJIBW2tXyK9jQHLbqToj27H9pcLK
W7bP1CpqvfYBL5OpV6B5ZNzPUnHPvvNIm3Y3aXZ1u8J9bf5klO9r2+PA6O+W4/tv
dCKHoDkmNxiNo1mvpoeewemq6K9Q5Nj2xh6zM3k+bqedp9FS5t6eBlFNAJeMQhHl
q0zHaoQqQVJ4g2MknaYoUHafyuqvPghKxITRPnY34sWmpEOD9EE7vSx0NPffyMVE
0TktaP7Efu1Z8jr4lN/6r2zSqNc2FDjjSDXx3r5iFiFUlSpcS7Q4bDHsi33VBMvW
+yS3KF+HCsQ2cu4i7AEhHL93YKkOGev9OSKtLDWtaEPN1bFttl6EdRMvDqrvfWUx
6HkxE7LbpCfudoYu4s1fgaGK3XiXztOBAMCHTrP+lvwArR8/SLEbih9h/pLmCliF
B9fuO7oFlNAIGyBCGgOuehtthNtUIgTOV5CEAs5WDq/2xFG2Kv44zLw29u+O+aQs
dGOzZFmjZy47vL1n71mkClf16ttp2IVn/gXO3vVtuWhfqxNgHiSEb13o/RxENnmS
3Y6+kk90Z2v8Yz58M7Perv85LVVsGnA7NhzK5P0X1XLEu+AGeRIiTvRwK0jveP94
dsXo96patQIDAQABoAAwDQYJKoZIhvcNAQELBQADggIBAGKbGBOlbO3/aaT4Qoi3
0Px84TzvcZJEpjU+HKo3IA02w++/BPlMMv5LQbW7nzbZNYJIrFxP7dpw7Jz69gs3
pdcuoAQFhRi0Bl2TNdp63c39H8oIDjQLrw4Uty61utQDtNGw623DrjbKb/gFXrVn
y4/4vGiQEpE+o9iCjHWhcXh/G/DOtLcLDazvfQEPRtJ2MtOVFZib/lhJZoY2cSdg
M5MGv+6QjqiXPrEqHzb2pjwSWzTxhzz4/8tLGcr+ON5gjtLd2129wntkR6joW903
lDhoHdMPPwcyI+4VIvKKHlfV6XqAWM9Jobfhoik97oVaZl/z9+OA3pUSzHZGHc6J
3M7ORfvBrRV5y8BzR8EmOgO4WtFc+1vOaCMDSvN1Ot6HRXHb5VeQfwrlII+Cjm/u
PIqXlQdorjf2VnWCsoUylor8TYocLMl1Nd+00XoPG0rnNZa4FE7NdTytnGzBchXu
Oac2VtMos8mqSXXXhwcAgb2N5QDwZ6cwJtoIhuQ5J+ItRia8/yT7LV2Mc/X0C6vp
4hKEK2HYgMxijAVZe5YGmFLZyzZ94ZgVa7nB6D27PA6SDkE0iyD7PVQjmrPA7wJi
8kk/w3rrrKS02pzMAarXEUAcCxNYIKUXLBqt2VBHd2DybFsExVfjpBVUrk3YZp4P
DcFT5I2/LKpQhkKNpeYHtvdo
-----END CERTIFICATE REQUEST-----

**Comment by DeepDiver1975** [comment]
```
-----BEGIN CERTIFICATE-----
MIIE+zCCAuMCAhCMMA0GCSqGSIb3DQEBCwUAMG0xCzAJBgNVBAYTAlVTMQ8wDQYD
VQQIDAZCb3N0b24xFjAUBgNVBAoMDW93bkNsb3VkIEluYy4xNTAzBgNVBAMMLG93
bkNsb3VkIENvZGUgU2lnbmluZyBJbnRlcm1lZGlhdGUgQXV0aG9yaXR5MB4XDTIw
MDQwNzEyNDA1NVoXDTMwMDQwNTEyNDA1NVowGTEXMBUGA1UEAwwOcmVja21hbm5f
dGhlbWUwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQC9upxG2LXlOVst
EeEwKqzYT4CNX0MRnNGlNlxDAuDbrkNYuMPJn2cZIlGuzM1xaux4KqbaqJIBW2tX
yK9jQHLbqToj27H9pcLKW7bP1CpqvfYBL5OpV6B5ZNzPUnHPvvNIm3Y3aXZ1u8J9
bf5klO9r2+PA6O+W4/tvdCKHoDkmNxiNo1mvpoeewemq6K9Q5Nj2xh6zM3k+bqed
p9FS5t6eBlFNAJeMQhHlq0zHaoQqQVJ4g2MknaYoUHafyuqvPghKxITRPnY34sWm
pEOD9EE7vSx0NPffyMVE0TktaP7Efu1Z8jr4lN/6r2zSqNc2FDjjSDXx3r5iFiFU
lSpcS7Q4bDHsi33VBMvW+yS3KF+HCsQ2cu4i7AEhHL93YKkOGev9OSKtLDWtaEPN
1bFttl6EdRMvDqrvfWUx6HkxE7LbpCfudoYu4s1fgaGK3XiXztOBAMCHTrP+lvwA
rR8/SLEbih9h/pLmCliFB9fuO7oFlNAIGyBCGgOuehtthNtUIgTOV5CEAs5WDq/2
xFG2Kv44zLw29u+O+aQsdGOzZFmjZy47vL1n71mkClf16ttp2IVn/gXO3vVtuWhf
qxNgHiSEb13o/RxENnmS3Y6+kk90Z2v8Yz58M7Perv85LVVsGnA7NhzK5P0X1XLE
u+AGeRIiTvRwK0jveP94dsXo96patQIDAQABMA0GCSqGSIb3DQEBCwUAA4ICAQAG
mcOdP3l7Jc2Tyf/JpU6WOUdNP3osXxYf+fnb+aBor9BPmCTMYUUtMvhvz7gUEldL
Ev7A8sptj1wjNbvZMGmqkfUMq0h4loJX8CUkECX9uMERTffiOUFmRtkjuK6a7Mmh
7w4icetS4sV3/Ijtl2ueXuWiiV++6EAFbI6Eriwr89LVneHq5zUdl3ovPuIMOWRV
yJKvjU9BF/bOh6mFhrp716PvV6j4SH2H7v33RpNtvv36yjeBW85F3mhixFb9w9am
WB6++GgiqEj1FP7lsMw+rua3D4XMSA4/pVF6Fvfi2/W5trlWOKYX/f5EeQitOjX+
8lD+en/4v1GD4cqC/EZwO8tSsSJe+R1IUGpf191LdjhX+OtEM0v1s3W2cstG79vr
w8eCiuiHGGBnG+cQMl8DHzWgd6VqTs81GgcnaToNEPKkFKf1x7sMTnBHeI5reP6F
XwLOHYa/JU+y4zHdy6AWtZbnb28+2JPm0hfSf/d/A2Tx43ijhLuE2A2e9E/wtGxp
7t3lhvsL9qBSKl16x37K+9CRQsZVHCOyjxaQTQt/S1Go2JkEOIWp2F4nwm2jKzDN
/sULYa9CiSTH7Rf76Sztv0wZHTnmm6h/IG8Ho+LBhq+ZWGprSpV8DEldZzZAs3Qu
oyHnTHQZfEjAh7YOq6U9pw17YWLRi+JH5e4UJbeB6w==
-----END CERTIFICATE-----
```
