### ISSUE TITLE
Signing request

### ISSUE THREAD

**Issue by hurradieweltgehtunter** [owncloud/appstore-issues#164]
-----BEGIN CERTIFICATE REQUEST-----
MIIEXzCCAkcCAQAwGjEYMBYGA1UEAwwPb2NvX3NlbGZzZXJ2aWNlMIICIjANBgkq
hkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA3R/FCTB5JAOGkMd4pgKW5hkrH5WwPOO8
XBdX6WRvMPrxsWrnjyXViH5oNae2g9fEWokJotFOpio+ku244glOFVYzgJSy2ZtK
4swwlHK+R8Blgv/NvLUZqcoD8K+YPrInf61JujdqaJgz67RZ8CynhW+UN6KV6Mp0
qyDlfPpeQIrDRWj5AgnJbbFN/KBS7s+0+XPN+IhHSNBMVqGTTbbgvnLLU/CfhHsu
F6aLNNRe+l60HEaPrJ5kKz9Y2hvNisA4y1rZShltfxBCWXJzav92cIYbiWTRP1WF
26PcD910G0bY/Tu4pPZgUWY6suf+qDpGqv/LqolFOrTfVIAYqSv+2Z1IsUgiEFW9
1C37aXA5MdVWxVj4FXLtDAe6dwiuH647/Osq4LiL/vL8WQ2KEuqS6Gyj1fLUPRgD
6OSzd1u1mcigDm7Jg6XU3KVBLLCOQB0hjIc7NI9Fc6OgzkgBB2eQroYTrJwK6dPB
1KxdYM7l6FE7laTtMSGQt7k8wJBwIZSsB5XKZrHXM4FS+W+YktZrpRvKggpR7NA8
MKUg0U0pCSNu5oGH5Xc+7tjEiejZuXvGU3yXD0j1Oq/VaNKLDCMxUVVvDQEzZ5FU
+NFIXNnlpbMj3wPxCvaAafKeepl7fGynkcEVwqaBq5aReS1LkVLsBIwdNzwiCw/G
uUF4wWP4gKUCAwEAAaAAMA0GCSqGSIb3DQEBCwUAA4ICAQBJaaRSHXuHLs9XnhCy
kQarAKHjncDwG4vsNbA0fufd/FN2E9ceb7xgLsH7KnxTUPOGFI1Vp43JFShlRkFu
PzgThDOqWDgmtGbySDphsiVpXJ3c4/RKFF9emVgJWFwt8OCbUZN0ccJPfnvZNhsd
4TGZRcZtc40vp9HyIRHA28NHUROhR/YV07nArRvOWNtzXBSnwtxgZ5ha1n8ql/7Z
FlZYqbNDTYG4u4gmiE8BktjwZTLMNvl+LwbULKEzWfwouWY8de7CdBjlXpDR4CGo
tHOGP28mEP/lbPAABOu5ssmX0WJ7/Bkzj5aKix3ccapme7r+SlRBoKDUeOLcH84n
pQNQEt5XbW5hIv7IrytVv4CBe7Ev785+vyDAtII1+oBe3V+12r9oSlOH2REB2H8J
ksq2Q7oT6E0PJDRBOzjZ7u92d/8wMoEQuT82pmOM/A2TW4zdDIVhTKKKwH8tQsZD
vjHgcNcxt/2Z9B/KuPidJliOANiI84GmhlzKW/1MUVEjidHvitgHX27u5OHj44ti
+4cjso09ZxELwB8rgA4dx34NBlQNo8wjxUHAulizvpZOIf99+UFPszyYMe2mO2TY
1Q03dpv4Mz+7W1Nt+0D9Ppxc7IKE/M1r4b/5iorwDnbA2gbsfsP/4kqP4ZyjEiOy
VoS5tNRTqrcA6ISqC/qMg7JnNQ==
-----END CERTIFICATE REQUEST-----

**Comment by DeepDiver1975** [comment]
```
-----BEGIN CERTIFICATE-----
MIIE/DCCAuQCAhCOMA0GCSqGSIb3DQEBCwUAMG0xCzAJBgNVBAYTAlVTMQ8wDQYD
VQQIDAZCb3N0b24xFjAUBgNVBAoMDW93bkNsb3VkIEluYy4xNTAzBgNVBAMMLG93
bkNsb3VkIENvZGUgU2lnbmluZyBJbnRlcm1lZGlhdGUgQXV0aG9yaXR5MB4XDTIw
MDcwODA4NTMxOVoXDTMwMDcwNjA4NTMxOVowGjEYMBYGA1UEAwwPb2NvX3NlbGZz
ZXJ2aWNlMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA3R/FCTB5JAOG
kMd4pgKW5hkrH5WwPOO8XBdX6WRvMPrxsWrnjyXViH5oNae2g9fEWokJotFOpio+
ku244glOFVYzgJSy2ZtK4swwlHK+R8Blgv/NvLUZqcoD8K+YPrInf61JujdqaJgz
67RZ8CynhW+UN6KV6Mp0qyDlfPpeQIrDRWj5AgnJbbFN/KBS7s+0+XPN+IhHSNBM
VqGTTbbgvnLLU/CfhHsuF6aLNNRe+l60HEaPrJ5kKz9Y2hvNisA4y1rZShltfxBC
WXJzav92cIYbiWTRP1WF26PcD910G0bY/Tu4pPZgUWY6suf+qDpGqv/LqolFOrTf
VIAYqSv+2Z1IsUgiEFW91C37aXA5MdVWxVj4FXLtDAe6dwiuH647/Osq4LiL/vL8
WQ2KEuqS6Gyj1fLUPRgD6OSzd1u1mcigDm7Jg6XU3KVBLLCOQB0hjIc7NI9Fc6Og
zkgBB2eQroYTrJwK6dPB1KxdYM7l6FE7laTtMSGQt7k8wJBwIZSsB5XKZrHXM4FS
+W+YktZrpRvKggpR7NA8MKUg0U0pCSNu5oGH5Xc+7tjEiejZuXvGU3yXD0j1Oq/V
aNKLDCMxUVVvDQEzZ5FU+NFIXNnlpbMj3wPxCvaAafKeepl7fGynkcEVwqaBq5aR
eS1LkVLsBIwdNzwiCw/GuUF4wWP4gKUCAwEAATANBgkqhkiG9w0BAQsFAAOCAgEA
Uuaz874qJPkocmsV1BU8s+2Pk6W2gTZT8o/RAPcPTZLVZkB64QzUtJtZwNjLJ4kA
3Pu8ltmsFrRMjIXAOTKFreOQQC7rHgRI0+w8W7GCxNDUv2HqUEUbiZ4XeuWwkGwl
AqGonpMDmxr4XPN92uyb8/cLEGz8vbiWWK+XErTk/kh4TOlL7ANn6JxF5aYMjcFq
XDM4oecNflKpbiN6dWijQtk4feBwMZM2rhfPyPkDDJXVglPKRXY508oSWz9cPTaB
qrN2gOh4Jx9ZJXLJf9vZ8/GsPq1SrexPBFEilaToPqnPd3maXrf11cHC7lOCyGCU
mUhT/NHa5RyMTGsAgFV9UiQkyzpYPFgxPcW+aOrJhTm3rRztK9JgAQcKplr7gSKw
e1uznyF6SHsj0vM8db/tNJck7kaqX6Lw3LJxIF4gTmMobL+BblZa+ZtINpLXicIo
p2iWRjDhKXz4dpZMEEic6yPveTFzsRFNtchtYXzMHUcIsXffyTOH0VbeZIDPC8Li
EmjL4YmXh9LGHrC1RDANVjPO53KxK74tyk/CcLrC41eS2WfhTHMbhQQDpS5eicj8
fSszXofbyEYwxgpnjHYtdBrtogSSlElJhJnroyc/5b+8cDvCcP4WdfIQCmhciyRl
epIo1fwCDku6wh+gFNUnHfJ/0QeTdGAJowMSijAu3to=
-----END CERTIFICATE-----
```
