### ISSUE TITLE
Signing request Sciebo RDS

### ISSUE THREAD

**Issue by Heiss** [owncloud/appstore-issues#165]
https://github.com/Sciebo-RDS/Sciebo-RDS/tree/master/plugins/ownCloud

-----BEGIN CERTIFICATE REQUEST-----
MIIEUzCCAjsCAQAwDjEMMAoGA1UEAwwDcmRzMIICIjANBgkqhkiG9w0BAQEFAAOC
Ag8AMIICCgKCAgEAn5arodvQJR/D4fJkLv/+BsoLw5JOFhiPgXlSf5BLHceMSL72
iYIxGsL+EsNj1oMfW/qPtt7s5pjybVk1ko4V3M+FWcaZO+Yi+gZsnD/RemyJNgG9
E6N5Nv82jX/ZOBeZxqzFcB2Qd6X6lqKw7i+l5RVTCBb4v7rrl6bexl+Bp5wRz5uN
fr3xSSyWM9d87/OpT8oyg4wdEKG7q/jreqc7tB0E+MjtqaI1wlwT3LrTX5bmKBL8
VWjiMffj9A7OcZDcIOWtp3fkc6+RYOTU7N8SmzYU397iFpeNVgTF8hiqmg2Eb8sH
FKDviJSPvatM3WmYucqNLSm99YTTS+uVJAL7fr+DNY1/uPjd7Q2yK1dDekfFMh+n
G4a5H7nfHw5XgS853UBQ9Y4/v7asrVgI1JeXIJppN+1yLXz2+fck/fC1ilfr+c6x
JAWVu9/BJuTgj8EO8ZFFVi8iXIhU9/Ae5QotKE5mn7fkxtjOr3mwDnVdW8JXnFnk
AhoF1pzWppA54OEjHEjPLFrvqBE+CB+diH177Oc45QbsiS779jLYRmg2ji5EDeiZ
rGWQnB4rNrME+49mrcWSeQ6IQTtPg9IKB6A/3+6OvfOHQ1NVeAUctBNGVF7MxvQZ
IFh+AVmwktkM7Wj6dvaaH0LYyxuVp9QA+k2aOXLnANPhiCLQAjeU5AsXjhsCAwEA
AaAAMA0GCSqGSIb3DQEBCwUAA4ICAQBp1qYs3T9w3mxzACZyU8MZGZ0LW1pK/h/s
IjKTq10hbB5gQHxZ8ZG+weCWWALsW6+KUHlKEczZBZKqQq3tQKvvCieav+EVeYT1
FJZ45hIquUnmWNAInoAfrVgypK2NLgYwl8w3NTbLseuiD3o4jvTdyr8+Ozb3pP3u
21Jw9t59aK7nlDAwf140dqxGlsXEdr5UIgOXAAcWiTrsklw7ACXziwkKOjDYBRW+
CHtZnAvDm7Sjleg8Q6nn9mHR45CTuPOzOJS75QKYiToKTLAipzGulxESN2SVgxQ4
2TWZbKwAwqgbEEj80N9F/dpIiFmIsIScldaA2TJp9r0bHpMardXlLcWn8/sluslx
wA3rClmy8zd/EZLNA8DwNs6GYQ9R8b6VLZtN3O3bSGW/ACjNWG2XPumiQL2K+IZ2
2T/vLOdeKC05tNd0SGFRbLWB0UTxlt/wRxASmbNhaJK9ZE7BxB/VzHpTHcOBEKKj
wyL+i3habRPHm1quDdxzxY1rKSDwJRLgaYQNaukkw0EoNFxrhg3LPFzYOfKUfH0l
M8i6vUvviNtJ8nAKUwpF1YJ/nHdX1LVn4PflpWBDFc141IStCqnBGiC9jViLy8pO
RQvrfeaQ+GABnMcJIAYTQUsbus4jDp10Zi+bSnUPWQ/5mOtqKTJ4nw+FWtRzHr5o
AbaY6JHFLg==
-----END CERTIFICATE REQUEST-----

**Comment by DeepDiver1975** [comment]
```
-----BEGIN CERTIFICATE-----
MIIE8DCCAtgCAhCPMA0GCSqGSIb3DQEBCwUAMG0xCzAJBgNVBAYTAlVTMQ8wDQYD
VQQIDAZCb3N0b24xFjAUBgNVBAoMDW93bkNsb3VkIEluYy4xNTAzBgNVBAMMLG93
bkNsb3VkIENvZGUgU2lnbmluZyBJbnRlcm1lZGlhdGUgQXV0aG9yaXR5MB4XDTIw
MDcxNDEwNTczNloXDTMwMDcxMjEwNTczNlowDjEMMAoGA1UEAwwDcmRzMIICIjAN
BgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAn5arodvQJR/D4fJkLv/+BsoLw5JO
FhiPgXlSf5BLHceMSL72iYIxGsL+EsNj1oMfW/qPtt7s5pjybVk1ko4V3M+FWcaZ
O+Yi+gZsnD/RemyJNgG9E6N5Nv82jX/ZOBeZxqzFcB2Qd6X6lqKw7i+l5RVTCBb4
v7rrl6bexl+Bp5wRz5uNfr3xSSyWM9d87/OpT8oyg4wdEKG7q/jreqc7tB0E+Mjt
qaI1wlwT3LrTX5bmKBL8VWjiMffj9A7OcZDcIOWtp3fkc6+RYOTU7N8SmzYU397i
FpeNVgTF8hiqmg2Eb8sHFKDviJSPvatM3WmYucqNLSm99YTTS+uVJAL7fr+DNY1/
uPjd7Q2yK1dDekfFMh+nG4a5H7nfHw5XgS853UBQ9Y4/v7asrVgI1JeXIJppN+1y
LXz2+fck/fC1ilfr+c6xJAWVu9/BJuTgj8EO8ZFFVi8iXIhU9/Ae5QotKE5mn7fk
xtjOr3mwDnVdW8JXnFnkAhoF1pzWppA54OEjHEjPLFrvqBE+CB+diH177Oc45Qbs
iS779jLYRmg2ji5EDeiZrGWQnB4rNrME+49mrcWSeQ6IQTtPg9IKB6A/3+6OvfOH
Q1NVeAUctBNGVF7MxvQZIFh+AVmwktkM7Wj6dvaaH0LYyxuVp9QA+k2aOXLnANPh
iCLQAjeU5AsXjhsCAwEAATANBgkqhkiG9w0BAQsFAAOCAgEABPNSny4kKIPh2Qii
XTIduGQxbSG2bNKaNILAndnEgC5/l0yVMHPVt+fhLfClUIRMxknkL3ZhNAKdzYQ6
70AwtnDhJJwuQSLbQhPjd0xjheVlQJ06JKuGdT9QXL3+ng+5gphdx4fQJkouypJq
c6Ipz50whd19jf/RlXyfcvt1gJU5xhvqOea64TFD5bjgvp3jH9BM9a9wYzyVpBW8
l7u1a+PX/kviwtZ4qNs15JR0x44LnDt8MPRUouXXeLy0tOzztW3xfFVsolEREYVw
8dAV8C3VAgtDx5FThavt8RHaAfctVZasr5YloEFrIpN+tmeqfdTTip8+XSM38p2h
IvtvPX7+nUynxNgIhKJxuxDLprEi7mKrbeCOb3AF0H8ELvpHi9LwvaHQ1UH2x3qM
nm/pBR01qxGaXBuMUZ34IebbGH9nJxsd1J+R3PPpIpE/5QJJExLBqBLRw9GPhKgQ
xci4gLfSYipmH0CjqrZd+2IjAp1Nb+7K0VMsLb5eg8QBSYuknwI4pjcsUy/B852T
E9dcBNHYDoWlOgc4GEheZ8vsNa4cThqP+urfHM4Lf5AY7qVchg8ehZ5vRBeTWv+0
6GEdpS0ZTuwNZQEMl6sYqVpHOFDSsWoJ2ByH/TT5P1Ho8AMK+GaSJTMNGaYDd648
vN4LrW0t1UWyy4vEafX/kU6YGSw=
-----END CERTIFICATE-----
```
