### ISSUE TITLE
Sign certificate for Sccuot

### ISSUE THREAD

**Issue by Daniel-WWU-IT** [owncloud/appstore-issues#168]
Please sign the following CSR for the ownCloud application **Sccuot** we (WWU Muenster) are about to publish:

-----BEGIN CERTIFICATE REQUEST-----
MIIEVjCCAj4CAQAwETEPMA0GA1UEAwwGc2NjdW90MIICIjANBgkqhkiG9w0BAQEF
AAOCAg8AMIICCgKCAgEAtaFxFpsUzTbJK99CaGK+yuW0iyhdUhGAr0YIAtGXXcwj
QcjBG7T3lULKLjTDs6G/QGY/jYLdfH9RQS5klB3Puy2m6uD+eqcqeKMNnfHiR6rm
2wSyWwPsNkCuoWHFtBWcR37xG5ksAkjc54Trkh5J1jH2u7pbvR5pMKuPYuBZ3DMy
0k/QTaVlcc6u+dFd9FbhBLfSqaQyMTyReWebJdrnlQqvE+UaURd6AnUfmooWNVJ6
4Y00iZcGPkv2JdFXf8e5wyzRzr04sIyVLod+pQRuIrGKTUkhUnmJV9zgnqPOAeb9
a69a0Lgqq/AWqvHUmrA0FJJ2fEaRsNyGfYkUmVbvfeyaH5xUPwVA441Lib1PHz4z
uR15m4Rd54iSZyE2xpJ2phA+ECZwQHkURfyWDLVaMonyqSSuSjHIfJpfzrZoBX2S
EV6FH1ThqsPaXP3zWTlU6o5nOSIP7Zaq/py+J1xgmratNQ525CywyYp9/LDcWx9w
bVcABiDbqP1+jg/hWx58xeYvZenJxnUuwInsJFCIoAVxPfprdAUL0A/WCaELmOC6
xmUITXt0GEODAcFVWUDjRl4SbnsQfIhVkx7XtCTyHEjwm/p+s4q/3ENVL2xEw03u
WirG7lL0MSdeWa80s6YqC1KK9pd8qfiRvmzK1rbJ27ChY1go5sNfSxLF4t5Wg/sC
AwEAAaAAMA0GCSqGSIb3DQEBCwUAA4ICAQA6XyE/yUVdF5z3Iix5zBgewuIyqh/H
3ZQBDERyW4dyW8/jUdzc7tuRDVxwu3muDJG8/kvS1EJrNCfQ4j+7y8ly7hqRxucd
Yxt/Ur0zcjRFPyKSiZymvGZUd0EQR7SlGts2oVCOzP3kH3bUX79G8OrGGs+b4noT
O4ssEB9al/Elwuv1BWmXMe5kQ08xN3Ae0FtKorugxKzq6XPGBi2ydCkgtW1EZsfx
hEp9y+WIcQBG7ndAHQ8jQdLuuMdCZFMPdDpD8+IaDZ/cEujKRgOEkfDPq68439rL
50PuwgC2CG8yUA0crHzjUxMp5NQTNSBam5es3VdRnQ2ywEqyt5s+Mc+5GUQXUNhd
7WYs60Hzbv0lZlHo47ypR5iKRwKGNgIBx6iNAB3fxNIwHqKOLvBQQT5yuOfdWcAZ
FxlCC93pjVdzjSZd1hLYkObIPpkFaa1jrSNbhDxqgwEc3ACp4itGGQpgdz/hRU2k
dGV2mrrgzC6kPiOCIGPaOGBCW1c+ykWl5b2Vewqapd7vn3h6jNDGI3ly4tDFFQdM
hEWnsoayByY9dxIOK0iDKJWonhjT4437LkdUtNdJneTERH0Pk1Wc2pzj2l7cNnPd
fJy4HrJVYOyZdYRvltb6NgxXiqKO9LAwhhfEW4DLJCbTaqEYj2q8ni0ld2UGXNuY
K42uJLhaDeXC+w==
-----END CERTIFICATE REQUEST-----

**Comment by micbar** [comment]
how is the appid of the app? needs to be exactly matched from your info.xml file.

**Comment by micbar** [comment]
@Daniel-WWU-IT

**Comment by Daniel-WWU-IT** [comment]
The appid is **sccuot**.

**Comment by micbar** [comment]
```
-----BEGIN CERTIFICATE-----
MIIE8zCCAtsCAhCVMA0GCSqGSIb3DQEBCwUAMG0xCzAJBgNVBAYTAlVTMQ8wDQYD
VQQIDAZCb3N0b24xFjAUBgNVBAoMDW93bkNsb3VkIEluYy4xNTAzBgNVBAMMLG93
bkNsb3VkIENvZGUgU2lnbmluZyBJbnRlcm1lZGlhdGUgQXV0aG9yaXR5MB4XDTIx
MDEyMTEzNTk1OVoXDTMxMDExOTEzNTk1OVowETEPMA0GA1UEAwwGc2NjdW90MIIC
IjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAtaFxFpsUzTbJK99CaGK+yuW0
iyhdUhGAr0YIAtGXXcwjQcjBG7T3lULKLjTDs6G/QGY/jYLdfH9RQS5klB3Puy2m
6uD+eqcqeKMNnfHiR6rm2wSyWwPsNkCuoWHFtBWcR37xG5ksAkjc54Trkh5J1jH2
u7pbvR5pMKuPYuBZ3DMy0k/QTaVlcc6u+dFd9FbhBLfSqaQyMTyReWebJdrnlQqv
E+UaURd6AnUfmooWNVJ64Y00iZcGPkv2JdFXf8e5wyzRzr04sIyVLod+pQRuIrGK
TUkhUnmJV9zgnqPOAeb9a69a0Lgqq/AWqvHUmrA0FJJ2fEaRsNyGfYkUmVbvfeya
H5xUPwVA441Lib1PHz4zuR15m4Rd54iSZyE2xpJ2phA+ECZwQHkURfyWDLVaMony
qSSuSjHIfJpfzrZoBX2SEV6FH1ThqsPaXP3zWTlU6o5nOSIP7Zaq/py+J1xgmrat
NQ525CywyYp9/LDcWx9wbVcABiDbqP1+jg/hWx58xeYvZenJxnUuwInsJFCIoAVx
PfprdAUL0A/WCaELmOC6xmUITXt0GEODAcFVWUDjRl4SbnsQfIhVkx7XtCTyHEjw
m/p+s4q/3ENVL2xEw03uWirG7lL0MSdeWa80s6YqC1KK9pd8qfiRvmzK1rbJ27Ch
Y1go5sNfSxLF4t5Wg/sCAwEAATANBgkqhkiG9w0BAQsFAAOCAgEAbjF3Bbbh324Z
c4CCe2TCn+ggCd3Q3grM0WobP8H8Q9rr+PrWPHgtfa5zXq4T6wa1RR4e0SJbejX2
zropAd7yY+ALRbABhQ7JNxVib/GlEF4t1LAfgz7PgFZIEs+gbfF45So7tJit84S3
U+CuKZCwvEfI9HKnReX+xQdoPz6f8+X8G1RaR60ngqMnoS6Cpc3sw2wq4zB/LIyB
aizUFQmF8dsP9gFNo7s6OGmxXNbDqWeGgm53k7dRsTbcAIPgfipW521kQWSHKI+6
3D6YaLY6Nqt3vhYQXBu+kXBrL5b+L9h1UJ0UPX1TPZ3WgQx5qBmHcbd38iAyUy6y
qEVf1Wn/tG1+C7UsqfdaQsPKZ5e5TMVj2Xe05Lb0n9aUU7H1YAopAFG42mmPHH8C
R/6f/ZoFcv+rcueDVcFVpxnd0S0vRFdLGR5s54rBAqVlcmz6RP3RMAqRV74nNsEM
Wu+S8/WCaArlmdoXrYiNgh0SeeC9qf9LNSQ/bVc2iAmtgGdFK1E73rHNwDYcKdqp
ofDBHA2yjFvhIi5z3d9mENDLFpsBMflFeJ+c3mk9V0aTnJsUEhH8LeNRIp3C9yYp
FB3IVTut4p6fV6hRApIN7gxQKPAPAuW6wzKVTsDBGSU9i9De7TVDinmzZ8NkOOyG
2efO+Foog1WqMR+F6pmj5WBLhGFA5Lw=
-----END CERTIFICATE-----
```

**Comment by micbar** [comment]
@Daniel-WWU-IT Should work.
