### ISSUE TITLE
Allow app devs to delete comments

### ISSUE THREAD

**Issue by cweiske** [owncloud/appstore-issues#17]
I have comments that are duplicates or outdated since the errors reported there are fixed with the latest release. Also, the comments should not be the replacement for the issue tracker which some users use it for.

I'd like to be able to delete comments and their replies.

See http://apps.owncloud.com/content/show.php?content=166654

**Comment by DeepDiver1975** [comment]
appstore is dead - long live the marketplace!
For suggestion please head over to https://github.com/owncloud/marketplace-issues/
