### ISSUE TITLE
Sign up request

### ISSUE THREAD

**Issue by traien** [owncloud/appstore-issues#171]
-----BEGIN CERTIFICATE REQUEST-----
MIIEVzCCAj8CAQAwEjEQMA4GA1UEAwwHd2ViaG9vazCCAiIwDQYJKoZIhvcNAQEB
BQADggIPADCCAgoCggIBAMqUysqvGe1vYZde/IuMOtDTz660UCPzadJYxazTzS4P
QIK68Rd6hquvRtpqhvx0ajr8KxKGrrUcIFq6rXiMheuhKF34DU0onZazdbLMzOwr
aH02z0PSvlkKRskwyJS9GTJPrmixA35CWjrarTxso6xHytDCd+VyfSo1UeYuaXKG
8ekpEdTXXRaHpR8drINf/DFO3iaa3KqbcQIEyJArbBgIG6NJ6/oWp0Fk/exT80Ex
2GJa1+jTB7TFqeQAadgFv1HfvWlUsXvtz4PYjSEE2yZd0yV1W+liPJiGvSw12lI8
HfvercbNeGjljoHfaUdCiB+38dC+lMz0uwzKHVXmFZDZjvIXBDvaDkmMIfOVi0b5
V2hKrBiXVUSnWmxZj2ce5PjL3J8WizTzX+BepwpteTVbI1imKQDKDDyXcYNAdw+S
zW9x/KNl4/EZguwGRpjSqi6d5KKIbTwOMQUn0GHZyRhuv1ZSbtgGz+Czpi0mIHTo
oltJuU0y/h/FUGynAksdhpsGW60VOSAmL4T/7tohQtSaC9+SrriXB4fMRXFlyEDX
I/RlINRDm8fU7n6hgxptpikOSbAaKM+xUguqLAXU2//RhSeKc9FjZ7RFP0ptqKHl
c2impeWFsZ0+gSAUWis7rUiQ29hhnKyeAsLcBLmHw6sLgDD8hgy62FVqfoyhXw9F
AgMBAAGgADANBgkqhkiG9w0BAQsFAAOCAgEAbG1k3AaE/24DhoNBOZA1V/It5Qj9
fcN5WzNRfa6Gj81ZsQArfaTC3bBUb7WMrCIeWbHBPrE/EgQJyAYtd0TanT1/GYxU
t/zZFXXfvUA4wICFjgy9TcWoCqz2AKCCNP2EzILHSWInF3b9kt1ua1s4Sr2mXUB6
AXLj/hugwb++PMDdL+6Lw57ndM13yZhik3BzKWk8I1J+Kf3ms6K1dLRyaj6VX7rd
LQErBdzhd+R+hns6AuHfh5RyQHsL8dc0d95NXGH2hGNRSjeO0V4nGnPwJXi88530
v6dzScFsFmvagB4oEcJpDiCZfTjrpSMPMLPzaJKWml44IKmYws1RKAtOimFRQy6b
ct/yh2bjk0F9J92/72PbtQ/p1XtySZS9K7lwrAqP2UQfyEcvyV4eKsslH0GtpcHF
tTeX5Seryv0JEAJ5UeBKka9++WEThSv/aAAx0VmSp4FV7Z8fRG6w7LiTGC85NYvA
dcrTY9HzvYI6Dg8gqQ9VQjce8sG27+07+RGewMfqirUQh6AIywBIRJHjBRG3j5/K
kvW0/ScdeW6Rdz5lPcI0Ir7cr8zNIj18ODnL2wiXSxTI4o6P1rFq2FazdkHQDdOn
FARjbDR0MxWD0yq7yOCO9yrCTOowQCwQ99DplYpp6tsR+fw90rjw8n6EVKB8ocsz
KmGn6haPOEGVhfg=
-----END CERTIFICATE REQUEST-----

**Comment by traien** [comment]
appid = webhook

**Comment by micbar** [comment]
```
-----BEGIN CERTIFICATE-----
MIIE9DCCAtwCAhCcMA0GCSqGSIb3DQEBCwUAMG0xCzAJBgNVBAYTAlVTMQ8wDQYD
VQQIDAZCb3N0b24xFjAUBgNVBAoMDW93bkNsb3VkIEluYy4xNTAzBgNVBAMMLG93
bkNsb3VkIENvZGUgU2lnbmluZyBJbnRlcm1lZGlhdGUgQXV0aG9yaXR5MB4XDTIx
MDUyMDA4NDAzMloXDTMxMDUxODA4NDAzMlowEjEQMA4GA1UEAwwHd2ViaG9vazCC
AiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAMqUysqvGe1vYZde/IuMOtDT
z660UCPzadJYxazTzS4PQIK68Rd6hquvRtpqhvx0ajr8KxKGrrUcIFq6rXiMheuh
KF34DU0onZazdbLMzOwraH02z0PSvlkKRskwyJS9GTJPrmixA35CWjrarTxso6xH
ytDCd+VyfSo1UeYuaXKG8ekpEdTXXRaHpR8drINf/DFO3iaa3KqbcQIEyJArbBgI
G6NJ6/oWp0Fk/exT80Ex2GJa1+jTB7TFqeQAadgFv1HfvWlUsXvtz4PYjSEE2yZd
0yV1W+liPJiGvSw12lI8HfvercbNeGjljoHfaUdCiB+38dC+lMz0uwzKHVXmFZDZ
jvIXBDvaDkmMIfOVi0b5V2hKrBiXVUSnWmxZj2ce5PjL3J8WizTzX+BepwpteTVb
I1imKQDKDDyXcYNAdw+SzW9x/KNl4/EZguwGRpjSqi6d5KKIbTwOMQUn0GHZyRhu
v1ZSbtgGz+Czpi0mIHTooltJuU0y/h/FUGynAksdhpsGW60VOSAmL4T/7tohQtSa
C9+SrriXB4fMRXFlyEDXI/RlINRDm8fU7n6hgxptpikOSbAaKM+xUguqLAXU2//R
hSeKc9FjZ7RFP0ptqKHlc2impeWFsZ0+gSAUWis7rUiQ29hhnKyeAsLcBLmHw6sL
gDD8hgy62FVqfoyhXw9FAgMBAAEwDQYJKoZIhvcNAQELBQADggIBAAP/mbV8wDH0
g1uyPxgsTMzfjAYWeXBoc1VH7vI914FSo8jELO1M5bb9J4fSMXfvPJ3AX1ciKLOo
YApenU7oZE6NvbKqMMoymCn6gKUHw73LcvKRJ6Y5+zVCF+bDgryeDNhkP+gkkb/x
HbKovVi8k4u6uN7ylzGutZakIsHkKdNDGMX+68ww3M1wWIabHtG6DLzsRKALG58H
mAqIXRSZBUSGc+uCxcHnSE9//0lBwsRbXxW5j7ijS3xxclQimQLSXKdr0yMzBHNk
SFn/GokKMZUTZIm0Qv1iT3vjWe5XKBtKlx27HXKQ2qQOV+pG6pq4/EpcNK+FIOH2
BzsslesmnNdD3mz5jlawyiVIhIwPvFpZYlFoox4k8t4lCYKzIbyI2C0Qw16Gy1Dq
CsUguapC5I/9k5A1a3VSHpuam8Zkv2Sx78mFZNJFAT3HVBZgjv5Dy41Mz/4gVkTJ
XitcW87wFfIm8nbtKdVSLj0pqbdnGWVETxYolFWM99umOgLwqnZSYnWeITSwl51d
OGBwZw9fwqexodSHQX77Qk2MhktMg1tXnw/RNK6jm54ru8owoipj3YrXzP1Ec/cQ
idEXjZhQlSnN97hv0an09eJ+686IZQ9rEGHGRq4VCe14OHvuQMoNLJT6BwKpgiKu
JIERadpzPji1cLhdnGR5hlkmIPMkW8nG
-----END CERTIFICATE-----
```

**Comment by traien** [comment]
thank you
