### ISSUE TITLE
Sign certificate for Overleaf app

### ISSUE THREAD

**Issue by Daniel-WWU-IT** [owncloud/appstore-issues#176]
Please sign the following CSR for our Overleaf integration app for ownCloud (appid: `overleaf_owncloud`) we (WWU Muenster) are about to use on sciebo:

-----BEGIN CERTIFICATE REQUEST-----
MIIEYTCCAkkCAQAwHDEaMBgGA1UEAwwRb3ZlcmxlYWZfb3duY2xvdWQwggIiMA0G
CSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQCwsKUWA73MSamlfgKzqHH7W5d5eY5+
unJYtNMWlWXyhEVfjtgj4aR9GxDSjEQKZQlM5RRhq3O/nNEAmmgs4lhfcWEnSsVs
DiZ27K+7PPhsnMDaWLsiWB1XIf3du/+KP2ipg+Ullnv6MmVVlv01+Znaj0WhCmUF
77agPpGbLPHSOzlFK2L1zawyME+zv346KfTENisAYP+RuQ0+Tu9rKsIavm/oJZUG
9b9OjAjx+gou3T67caVT9TL6Mdsp1yfd6fwN3mM0NMEEvSPRmwGYuhfH2K3YWO4h
vTwrE8Qk3CY7j6bgUBsG8yI5U5YxvI2m/1yyAEjlnTlzBMeReSjrZYTIWIk+Sydd
QjfTtwwaJrRZSLISYF38mWSH4sVasllycDH3rx6wd0FRNNK/RRf45s6p+e3KbVie
3RKRZPCLRiWEq4i+BhSEZm+4azMxMsg/t7WOB68fLVWNu/XzO35vK4YhE/MDNqhM
RY++BloU8gfjy5HccQH8/nlabItscbW84A8GZXdJBuhKfaG1nOeePRGibaDEmCoM
bj4znA/lf3j+Mx/XkOsYw5UAFVkH+8ILlzlbQTPLoOLM9mY6QFF3wSim+Lns5CiA
RRueW+fmQI9zUqI3x3PZKQHQKGV/UKTxUEoLnRrwYd4MAr882iB0eRus5FFsVG9x
e8YBDUnTAj1hxQIDAQABoAAwDQYJKoZIhvcNAQELBQADggIBAIzYh5LPN/p5GbfA
1Z4c1O6U62Jeh3Cp2OFe0DiS1YnJOoFOqsdzObMxE94tAmEpdT9dMgt/btdMr8oo
6QlrICMGdSqn9osmPF3ZA3QCox7rRYDXJ1iBSgxnqbsd1tq2qQW42zcj51EmLmBZ
BBtsKm8WtAGkwPhAmjfCsfj7XGvLZJnsV9tCi5lWIgoUqSFqZkbA3cCNbrj1yDr6
Qw0taIa+L3CeCn0XvUWCYlec9xLxK2WOKvpej8PU8jSecpm24K2m1yEk7m/tXrBs
SIu3qyGwRbGmW2oNI58EweR5NgBMUaWx+sNoGNeNEjfWlR1B6f78zIgqNajvO/dT
tAXGEWKo6AToIoOD4zis7AuG9IXiSdyFQ89dvxPk4nWuElJIvGw9/ZAcLrSrz1Xb
7aYCfM4Hmk/SsNA8YTkXQFnM7WTzjNWPdXXKI9VhlzTUQ5Xf2TORrHyWBWtDdPJn
Am5zYnMEvIEtxVo2IKicotP4v87flv0lKk+2N06sq1IHe9FfGF61re26FQYZTCag
8WM0jBxN7FM5zIGeL/aI5N/GUXKdnvmC0FezjiKylZOBnQ1DQ7WWMoONA3Y0Icyf
nA+PbeimMDnXdX5LgBsNlAzCBlaH9D2MG21SZ4MxGBgrx90BMmvTumEPWh193gdI
Yd0cGXrveeb8wY0YRA2s2CSxLXTw
-----END CERTIFICATE REQUEST-----

Note that this won't be published, it is an internal app but needs to be signed to avoid code integrity check failures.

**Comment by jnweiger** [comment]
Signature ok
Certificate Details:
        Serial Number: 4257 (0x10a1)
        Validity
            Not Before: Nov 21 14:34:07 2022 GMT
            Not After : Nov 18 14:34:07 2032 GMT
        Subject:
            commonName                = overleaf_owncloud

```
-----BEGIN CERTIFICATE-----
MIIE/jCCAuYCAhChMA0GCSqGSIb3DQEBCwUAMG0xCzAJBgNVBAYTAlVTMQ8wDQYD
VQQIDAZCb3N0b24xFjAUBgNVBAoMDW93bkNsb3VkIEluYy4xNTAzBgNVBAMMLG93
bkNsb3VkIENvZGUgU2lnbmluZyBJbnRlcm1lZGlhdGUgQXV0aG9yaXR5MB4XDTIy
MTEyMTE0MzQwN1oXDTMyMTExODE0MzQwN1owHDEaMBgGA1UEAwwRb3ZlcmxlYWZf
b3duY2xvdWQwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQCwsKUWA73M
SamlfgKzqHH7W5d5eY5+unJYtNMWlWXyhEVfjtgj4aR9GxDSjEQKZQlM5RRhq3O/
nNEAmmgs4lhfcWEnSsVsDiZ27K+7PPhsnMDaWLsiWB1XIf3du/+KP2ipg+Ullnv6
MmVVlv01+Znaj0WhCmUF77agPpGbLPHSOzlFK2L1zawyME+zv346KfTENisAYP+R
uQ0+Tu9rKsIavm/oJZUG9b9OjAjx+gou3T67caVT9TL6Mdsp1yfd6fwN3mM0NMEE
vSPRmwGYuhfH2K3YWO4hvTwrE8Qk3CY7j6bgUBsG8yI5U5YxvI2m/1yyAEjlnTlz
BMeReSjrZYTIWIk+SyddQjfTtwwaJrRZSLISYF38mWSH4sVasllycDH3rx6wd0FR
NNK/RRf45s6p+e3KbVie3RKRZPCLRiWEq4i+BhSEZm+4azMxMsg/t7WOB68fLVWN
u/XzO35vK4YhE/MDNqhMRY++BloU8gfjy5HccQH8/nlabItscbW84A8GZXdJBuhK
faG1nOeePRGibaDEmCoMbj4znA/lf3j+Mx/XkOsYw5UAFVkH+8ILlzlbQTPLoOLM
9mY6QFF3wSim+Lns5CiARRueW+fmQI9zUqI3x3PZKQHQKGV/UKTxUEoLnRrwYd4M
Ar882iB0eRus5FFsVG9xe8YBDUnTAj1hxQIDAQABMA0GCSqGSIb3DQEBCwUAA4IC
AQDE54rkDgktJieQs42afgvuA+Kh7kBiJGNY1hGXF1hy99IM7YM8qg545QKc+dsi
RAW9RBEo77HNTC37J68PmddEJChInBlVAIJGaatWooyLnF3WllNs/Cy+hvwWl+44
B4ucn3XWQ+6cEt0Zb1cb65l4FsENjzrBx3qo14H7Si+/uEoxwIZ04kWhYeysWnsD
2R8ztIE7Mrb6/v9vDgONMxMgLENF6mRLEFrS3qwYRpf0ZD2Dvr4dbbsAymWXLkJG
nr+P+tKEvRn/kjkZ/Iem+tjYaSJTvDeV015sBve/k4Zj3/pLYbSpI4OrKVXvZaiN
SQROceGPtOCRaOKhON1csGVVaUkd3as3r7M5BW5JIpl6iZ+ZwqvU+BX4HNwaDUcQ
vrAhYClPffaQ5tFQKHye9ki37qTd+kr1rD1/4yCQ9oSCAzJPsmRjy2xQjvr04TFm
xV+JUNNxLiNqY067fTXJD6WBZUVXGm1bzhyBXjoDikNKp3etRk8Q3UP6DmNzd+wU
MxIamubNE4LWXaejAtkAfX+L8+Fs3jfbWcxWv5llKRCIzIU3AXNQbjeyhwyeR04O
PKo20hCdTjFYfPKlQ1LUbUUsKQ8e4cUvEIqDpKc+/9ddWzSJjIlUDAhHd0plW/Nw
SROzSqwVYc9qHtSGWA2szJnBs51jKNj6c3HBoaxycnsAKw==
-----END CERTIFICATE-----
```

To get your app uploaded into https://marketplace.owncloud.com/,
- save the above certificate as a file with suffix .crt
- follow the next steps ( starting with `occ integrity:sign-app ...`) as explained in
  https://doc.owncloud.com/server/developer_manual/app/advanced/code_signing.html#how-to-get-your-app-signed
- reopen this issue, if you have questions.
