### ISSUE TITLE
CSR for the "opencloudmesh" app

### ISSUE THREAD

**Issue by MahdiBaghbani** [owncloud/appstore-issues#178]
-----BEGIN CERTIFICATE REQUEST-----
MIIEXTCCAkUCAQAwGDEWMBQGA1UEAwwNb3BlbmNsb3VkbWVzaDCCAiIwDQYJKoZI
hvcNAQEBBQADggIPADCCAgoCggIBANKZ1zo8Pp81vraajvZKQinFLBO6HVWoruy6
OGtFQ46fnDL6vfXZIWetx7VtE9QVlziY0tEC9/x5qQIvs7oU0aLDNZv3PrRHUAMc
6G6BJwHl1LgcVNE7ByTKGIdkR/V7X09GJnM6khsrCOBEM7FPEPy002+HMTLCFzbZ
9S7LIGi3bIMigEf6UiDln04hZrvpR977WIREZ6Ilk4/SYQXLqHJ5BaWYIdWqSOcz
J+MTPaaWcEcR0zCTAnsqmvJC5e0fzEI1iwmFfO/OwvtX1XY5cNdmHl+MPj6npuI/
J2bUu6Yq9Y0RRQs+LxEqQkQqIKRC4Wjm6t8dTtnmlk+MJbCDPQNNCJBH20Qu3bBo
VCrsKAy1zuNP9LymjyS5nBwqsASopNdwCDi+qBsa23SvTJXZahYHoIBldOP6U9G9
QG3izIt8YDTFp1N7Kq2yi0WwqbpwsbjmrToRqSSLC3uc/06a5Vw90qEGwMOwhRRT
j2QJx5Hkt99FDFaD6hZZ7nCLq4QpCCsiw/xfrMHL9h7fnu4K2t8crJBxE1Ap2E/p
d5D8vQpvvg3xjwQI1QSTFdaw72Wltgd5EVAhOC6ErvTiLJ8BuYmhsH/haeGgHBm6
VW7D54eCBLq9D7BuinTVwzEyiYMxd0j8ySW3gXPjSJKOi4+ouWXK8c0Z/0NwET4L
sIJgCSkNAgMBAAGgADANBgkqhkiG9w0BAQsFAAOCAgEAJ1Gkzl1FH8qJU9yGqWYR
XfAPz0d4yiTWPtMMVde95Ddr+R3Bo3daW55Eh50Jg9w+qcn9yuzARCqy7cHZEFsQ
iDGkKuC2ie2inqI3c8pV0G05hwSM+sMOerx8dTUfy0V+orXwVGyLVEbEAKGXIFdC
q7wBpKTAT394TOKbQBnG7CY7AnXU5GTQI0GURA2bwn2EMj6rqkjCqNr+OlWLUAoB
DUpGxXX3xZaRfeJjGJRscQxqycxUKhWkzPW11PQ5KTFJp9b8sDVG4VUpjKxy0A25
RjeVR1VOf1Z4cpgiD452XQLNFnBmhz8QKeMqigzt/hdAPkXan4seoy7pTp72N+yE
vPErcXZdZyrYk3QIAdmqFhiU4Iqo7QR8BXFJ0aw5vbwm5jhHecSsnLzUE9dYOWTN
mRk5W7n8bOAMzSUurpL0yE1MzlbACC89klOSr0u8I03WB6AIn1+gsK0nHlMBS7XP
h75bbADM7IXJXGbwgXsIPGMWGdtZ7y1hic/4dw4MsikNg8kdLhJ0mJgSCiG9WSSy
imVW81kwlurxdjXTNjvd0DH4iVzurW6mmvdIegROOew/lQXinfymDOsiYvgoKLfj
GrXXwlADz74Kmydnp0Y8Nl4YuQ3EUJUIg1nB4KYvEFJdogHZc2LrXaoIHhxjPtsZ
YupfoPdyzcKVjNNAvlu8tt4=
-----END CERTIFICATE REQUEST-----

**Comment by michielbdejong** [comment]
@DeepDiver1975 can you have a look please?

**Comment by michielbdejong** [comment]
Anyone?

**Comment by michielbdejong** [comment]
@phil-davis or @jvillafanez do you know who we can ping for this?

**Comment by DeepDiver1975** [comment]
@jnweiger

**Comment by jnweiger** [comment]
Certified until Jun 27 18:26:08 2033 GMT (3650 days)
```
-----BEGIN CERTIFICATE-----
MIIE+jCCAuICAhCkMA0GCSqGSIb3DQEBCwUAMG0xCzAJBgNVBAYTAlVTMQ8wDQYD
VQQIDAZCb3N0b24xFjAUBgNVBAoMDW93bkNsb3VkIEluYy4xNTAzBgNVBAMMLG93
bkNsb3VkIENvZGUgU2lnbmluZyBJbnRlcm1lZGlhdGUgQXV0aG9yaXR5MB4XDTIz
MDYzMDE4MjYwOFoXDTMzMDYyNzE4MjYwOFowGDEWMBQGA1UEAwwNb3BlbmNsb3Vk
bWVzaDCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBANKZ1zo8Pp81vraa
jvZKQinFLBO6HVWoruy6OGtFQ46fnDL6vfXZIWetx7VtE9QVlziY0tEC9/x5qQIv
s7oU0aLDNZv3PrRHUAMc6G6BJwHl1LgcVNE7ByTKGIdkR/V7X09GJnM6khsrCOBE
M7FPEPy002+HMTLCFzbZ9S7LIGi3bIMigEf6UiDln04hZrvpR977WIREZ6Ilk4/S
YQXLqHJ5BaWYIdWqSOczJ+MTPaaWcEcR0zCTAnsqmvJC5e0fzEI1iwmFfO/OwvtX
1XY5cNdmHl+MPj6npuI/J2bUu6Yq9Y0RRQs+LxEqQkQqIKRC4Wjm6t8dTtnmlk+M
JbCDPQNNCJBH20Qu3bBoVCrsKAy1zuNP9LymjyS5nBwqsASopNdwCDi+qBsa23Sv
TJXZahYHoIBldOP6U9G9QG3izIt8YDTFp1N7Kq2yi0WwqbpwsbjmrToRqSSLC3uc
/06a5Vw90qEGwMOwhRRTj2QJx5Hkt99FDFaD6hZZ7nCLq4QpCCsiw/xfrMHL9h7f
nu4K2t8crJBxE1Ap2E/pd5D8vQpvvg3xjwQI1QSTFdaw72Wltgd5EVAhOC6ErvTi
LJ8BuYmhsH/haeGgHBm6VW7D54eCBLq9D7BuinTVwzEyiYMxd0j8ySW3gXPjSJKO
i4+ouWXK8c0Z/0NwET4LsIJgCSkNAgMBAAEwDQYJKoZIhvcNAQELBQADggIBAD6M
iFFlFbn7saJQ+TedDeCng4Zu2bBGEqJS2FuaqKInH5bBdJo6t0w/GctPl5vYAHuc
g46XphokoR2qGIeHYgg6h2Bpy0USKN7WbXkO/LqcIfwXAh4yhzS6Q8kQs9JQ0N0F
QP75RfpAN9ZYfdSkhI35sR6Ym4ItRuaghwMo2Fy15Wj2/yssaEU0MOCdh4IPRMRj
Z8o6ajDxJo8WzIkPENr4FP0IRbsnUTa5HPJPYWLoMU9S+gaBUyDeZZR+TShfPxt+
fC/hu1XeYD/FVvHaUImMEeu84kN1/sAPAPgweO0ZVZI+sawColUkcVeWy2xH+Kkh
S5UsufciarAZreBp5C9p3ht/n6Ukc+3TTzajV/26Xm36RKPkmDWmXMggmojnFEzN
tudKkVSG9QT0yPj4Lu2+zKZBmukQDwn7KeGuZ+38THTzefJMS2qQE5oZ3dU9Y0dg
Nne5FzC4+1gVC+fYjZIosAVDjI8zUlOuaXYap3rIl0vQElNSUVqMaWMENZLaqPSY
7msubZ1C6t3oNtB08dHBvWEgO7JcZkgj30RtQrCIfSxAbmNnlFBpcGk/42BBav3I
VDRpGw0DYfCMh8qW4WoP/xJWamUllbSZ5NKEIqKBDSFTS2JHREyYglrI/zgvRJQ4
MbrJ9ir3q3o/8ygQBomQ1aaHG5ba9EvsSP2SbZW2
-----END CERTIFICATE-----
```

To get your app uploaded into https://marketplace.owncloud.com/,
- save the above certificate as a file with suffix .crt
- follow the next steps ( starting with `occ integrity:sign-app ...`) as explained in
  https://doc.owncloud.com/server/developer_manual/app/advanced/code_signing.html#how-to-get-your-app-signed
- reopen this issue, if you have questions.
