### ISSUE TITLE
CSR for the "federatedgroups" app

### ISSUE THREAD

**Issue by MahdiBaghbani** [owncloud/appstore-issues#179]
-----BEGIN CERTIFICATE REQUEST-----
MIIEXzCCAkcCAQAwGjEYMBYGA1UEAwwPZmVkZXJhdGVkZ3JvdXBzMIICIjANBgkq
hkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAublagXSKqrf0d//Dls0elYxo5y56e2IG
LJkpAZM+ibnrYKdTQkzCWQTzG+NIJfj72DcgbkAU4GV5ET45/qHlcvl//vQlLuAw
SyyxnzKeewWYEvDEPDYboKdLuddORfAFQE+JOUpTFafSp02lYMtHiE8q0pL5fpUc
seY97uEmjtIVgqB2DIlTZMfIbCrYd1vaawjw2Iq6SSccNkPq7EBzv3SyOiXJVXQ6
4QqK8FYOeLRnUPSXE80pIhLt6Av+3y0ICQounlrqWBJkODUDCe24mWri2t/fMcjL
r8SzgO1TdTVRi+rx/fH//0xSwkou5sqRpuOxvbY2YbwIYYp98fpL01tozbqa3NSr
JbySApWFJoWeg8t00HweFbxdG/BFWYASqZ8N95cb91OVXBv7FUz+lUGvF0P+Wjhn
NNqMjejXcn2E8gDbfQiBEBfgual+K3FrAmbpZMe+AwdehokZ6AgabdCAYLQXu1Z+
Ak3DEta3y4iO3c7kqucHaDytKxeUTMTxYeBGS3apbQfhdsjWGZ+v26si8X+zJQXY
9jFW+ZzsFsk1lqlyjnR7ZNA3EIdcJpm272bNtcUALQ+eRoPAh6ygczIMKN7jG9jM
nNIgI2SDxwAMrIznAk73K7vzXshpC9Bl+LkgJ6IOK56SpAFJxLQuwV+wpQAi0KUF
dvPynzi4CB8CAwEAAaAAMA0GCSqGSIb3DQEBCwUAA4ICAQC5X0xTXBaLGDw56O7v
wnIs+lxdX50tqovsuFu0KpYqDD39MwhCfhaqSWOK7vOQOKzjMq02LSnEWxFe97TL
SM9CRyZrqxTMSbb7EjwZbkl34KYhOFGTB6cyqch/dEzv0m5KaQQwXiRy5bOdl+ja
gZ3c5O//IBofLEkiFn5G4Hdk7oA9aZDnk+dq7uLcOlFiIokWl+sdk+VKV7y3gEiR
rjW43zO5nMxNnpWTNP/vS+yqrvihHmgsfJ/PAq8gTor8OLwSZj/8uDri5EjvwKgA
GcjaSVKZY5fTgjTVWHyiDr5btJOFrifENgTS4wmxSsswioYIX2xsVeS72i8Ugriy
nF2v8ffdvw41SjRW6OAwmcdfddz/gbfM67ziQ8/QQRJLNzyuwumbOi+ivgSrH2QK
U86uJPaTif+i8wtErDbVAC+Mm2JLEimkTOyTwu6Mlvc8dx224iUUpU/NF/ZOKcoK
vgip12tYqHsAakhJYLVdafHLkq8qDhuYbkD+a76GmYyLSbA3n6S2Ko3ZQ/f/InuQ
a6JC8gdYXZQF7qX6Ke+E3PX11xDizqZ2CpCG/okaT9BUJUH2UlhaTj5Wdvwpd98K
VNEg2sJASmfpbWgWvarOrKgYfEjemaRfFGv/BiOHL2hTzR2UYR6N5WQv+SrUZy9m
4E9lOfMY1lhahL5RefxDH/aR7A==
-----END CERTIFICATE REQUEST-----

**Comment by michielbdejong** [comment]
@DeepDiver1975 can you have a look please?

**Comment by michielbdejong** [comment]
@phil-davis or @jvillafanez do you know who we can ping for this?

**Comment by DeepDiver1975** [comment]
@jnweiger

**Comment by jnweiger** [comment]
certified until Jun 27 18:32:07 2033 GMT (3650 days)


```
-----BEGIN CERTIFICATE-----
MIIE/DCCAuQCAhClMA0GCSqGSIb3DQEBCwUAMG0xCzAJBgNVBAYTAlVTMQ8wDQYD
VQQIDAZCb3N0b24xFjAUBgNVBAoMDW93bkNsb3VkIEluYy4xNTAzBgNVBAMMLG93
bkNsb3VkIENvZGUgU2lnbmluZyBJbnRlcm1lZGlhdGUgQXV0aG9yaXR5MB4XDTIz
MDYzMDE4MzIwN1oXDTMzMDYyNzE4MzIwN1owGjEYMBYGA1UEAwwPZmVkZXJhdGVk
Z3JvdXBzMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAublagXSKqrf0
d//Dls0elYxo5y56e2IGLJkpAZM+ibnrYKdTQkzCWQTzG+NIJfj72DcgbkAU4GV5
ET45/qHlcvl//vQlLuAwSyyxnzKeewWYEvDEPDYboKdLuddORfAFQE+JOUpTFafS
p02lYMtHiE8q0pL5fpUcseY97uEmjtIVgqB2DIlTZMfIbCrYd1vaawjw2Iq6SScc
NkPq7EBzv3SyOiXJVXQ64QqK8FYOeLRnUPSXE80pIhLt6Av+3y0ICQounlrqWBJk
ODUDCe24mWri2t/fMcjLr8SzgO1TdTVRi+rx/fH//0xSwkou5sqRpuOxvbY2YbwI
YYp98fpL01tozbqa3NSrJbySApWFJoWeg8t00HweFbxdG/BFWYASqZ8N95cb91OV
XBv7FUz+lUGvF0P+WjhnNNqMjejXcn2E8gDbfQiBEBfgual+K3FrAmbpZMe+Awde
hokZ6AgabdCAYLQXu1Z+Ak3DEta3y4iO3c7kqucHaDytKxeUTMTxYeBGS3apbQfh
dsjWGZ+v26si8X+zJQXY9jFW+ZzsFsk1lqlyjnR7ZNA3EIdcJpm272bNtcUALQ+e
RoPAh6ygczIMKN7jG9jMnNIgI2SDxwAMrIznAk73K7vzXshpC9Bl+LkgJ6IOK56S
pAFJxLQuwV+wpQAi0KUFdvPynzi4CB8CAwEAATANBgkqhkiG9w0BAQsFAAOCAgEA
Zgp+LA7w/UzRJPD/CLuwabUurKVBqalJKaYEiY5glw4I+74OANB9JrzAdaBPKz3w
VePF7mNq3UDMeTurfv19yKhdxb9ZPAImN2p6EAMe/5wvznmIcBgYerFL5LfNtBnk
KzlqKH303G58khF0OEFpClKsLnU7VcVfhdZ7njbGOEzeY9IoCW6W/g8jCglNAPIW
gMWgvfhdXDZ06Fzxf9TiGzErM8yZ9tiPs/82ctv9A2S2ZmWPDjXnTWawZZkK9N56
P0ZXETkQ/zONJ2Cl7ktSXw/qIgvT75Ahg9iHg6DdIYzmPfB5D8Bt4tr1pHwIRepV
F0T0oUu7dna6VLV2d/8xIL4ldWsGKeRDd6s368XuUjUGHRXlkfOx/R1SPD7KpBTQ
tbTGXF5r1L0ogkGwLmVff5B15x3MVnCCCAJPOXK/i4WhiilQVjDxTQgaRNSKdP5s
4bOd12u44JBcwVd0gveS52GydysMoBHftQdNFhtLDIXoqoZ/HSMwixOhBMGFSubn
nXRIue5ga65bc99UiA86fl2FBc3r0Kd5cz8jcYFjs17joDUUVzi3Ks2+fK1ovONi
NebuC1+Fk0exOcM5vaQVCPWcWpbUGdlZ2ytdzweBK54HT4yGMXspvdrPhVdO2GUZ
c0kjuZypCORqSTDHs3VTodrFakhV/IJIClnZqeItiMc=
-----END CERTIFICATE-----
```

To get your app uploaded into https://marketplace.owncloud.com/,
- save the above certificate as a file with suffix .crt
- follow the next steps ( starting with `occ integrity:sign-app ...`) as explained in
  https://doc.owncloud.com/server/developer_manual/app/advanced/code_signing.html#how-to-get-your-app-signed
- reopen this issue, if you have questions.
