### ISSUE TITLE
OCS API /content/add returns HTML

### ISSUE THREAD

**Issue by BernhardPosselt** [owncloud/appstore-issues#18]
when posting to https://api.owncloud.com/v1/content/add with a basic auth header set, the result is HTML and no app is being created. 

What should the header and type be for the parameters btw? application/x-www-form-urlencoded? application/json? application/xml? application/x-www-form-multipart/form-data?

What is type? An integer like 920 or a string like Multimedia?

Both are not documented on the OCS api page

@karlitschek

**Comment by karlitschek** [comment]
Can you try again please? Maybe this problem was caused by a https problem at the time.
type should be an integer like 920

**Comment by BernhardPosselt** [comment]
Ok, I use POST to https://api.owncloud.com/v1/content/add with my login data as basic auth headers, content-type application/json and the following payload: 

```
{"type":920, "name": "abigtest"}
```

It returns the website and no app has been created with the name abigtest. The same happens when i pass the parameters as form-data or x-www-form-urlencoded

**Comment by BernhardPosselt** [comment]
Any progress on this?

**Comment by karlitschek** [comment]
working on it. Sorry Sorry for the delay

**Comment by BernhardPosselt** [comment]
Thanks!

**Comment by DeepDiver1975** [comment]
appstore is dead - long live the marketplace!
For suggestion please head over to https://github.com/owncloud/marketplace-issues/
