### ISSUE TITLE
CSR for custom app - opal

### ISSUE THREAD

**Issue by l0ckm4** [owncloud/appstore-issues#186]
-----BEGIN CERTIFICATE REQUEST-----
MIIEVDCCAjwCAQAwDzENMAsGA1UEAwwEb3BhbDCCAiIwDQYJKoZIhvcNAQEBBQAD
ggIPADCCAgoCggIBAL+p4xfb/SacxhKkH+J/o7wyxZy1WojAuX2w2G1o4kzfl2z2
jEDzL1/uuutdnFlTe0r5xjnNtjczlndZK947+U2tzIt9wE5jjuHKwwasImlzKcWM
iHiGZVvyzv1D5DSs/Y3InfNpWl+V6j9cw7XSJxkAzNhOFmCQQflfUA4eG5p62DbL
Uz7rZi+BuNFcPa25vyCC/PlPkEWvYOvEE/4cPND3x4J8nM90EQ3kutEiWdG39zZe
xwss/oKw7lCqWMnhrXgY5gILB4dq90abGoPSmxIOL7EVxGYDARzVUsodwTQ6jXGO
hzohTEQpwNBctkmSb3GMxwHAFz9SM6wV9jMl1O1zMmWKfknvh+fx0ciCg7VCpVB7
BoZN9f+VTDa6CDTf8IB8ndBX0wGSN67uH4wMxDBBYlvG2drwvixlz9h0MaQOPk7P
yPU+Jw82JQIgBYX0yUovwDowLLv7oMxZjEG7pvlmn/OzS3hMDeEhop4E+SCGUOKv
Z4fS1nDbnd+CY+wkfkMREf1CN3n8EIcfBW5KPaTAFo2njqCEZ+p2UQ/QnVj1EiNk
JBsebf4AV111gHAWx5ZXOxUx5vGDXAfHmMEfcxsefBsbIHKQnvtksmJtY89gqY70
01XXARRoa+uMh3Z4uSvCcFjbSq+oRse4rWi1oFVoKrtreni5R4lAy4A7fIwnAgMB
AAGgADANBgkqhkiG9w0BAQsFAAOCAgEACim262VlX4wvKxjqs8DyweLzVe1jCzWy
XF8SVjjiRKisYm3uZTFva3xlhdII0LEXe/Zk4kc1SgP9d6TDlWACRWLGrsCI8o7v
ADhnptJNRq2KajVLKuFpToTYw4vE4jTu8Tm1BFCE0+JWGOu49Bw3ZH+H9eRFNvgZ
zPT5+0tDUYXW7YE6NJKolf0vPawkOH2yLWZr6C+TPgfrtK+XZF4WrRgMN+1yz98G
Axy7DIjE826lgPnCe9XGzy1Rw635xEHDVIw3SPNcOqYLCafWYQ/r70a5QH/cE8RG
+o68JhGz1iNW0JxMmuZ7tUO5dn89yY3ZMwY342B5JaxBeLdwUzH2r1Png6l7osRl
fOT4mbjHd6YiaQza4C5MngRZeKpHyYkSCJIpBDkm2ima3KVt1P16YBOl6hx3ICPo
lFd22hzZnjqu3dMdTRepBrwKJ2hWoVOUbKL1upca4xkZnv59Vp7xnGk+CK6LTQoS
4Z/5BbyDoFZuwMu+b1ISukEc3Z/CLS9bkpOW090p2BhcDZMnttfhxaLD4sWQ58DM
YX4aPWPwdWhCCMI9oiNnKm9dHEBJmXLLVxtP/7u2iS2StN7UIzrEdJI1Qs46tOpf
NcoThV1TgxrgaIxXx66b0//h2dc8729JcQPY30C4ACvv0pOSV72Yg4ZNm4zCNUIs
OqjyjRNxXhg=
-----END CERTIFICATE REQUEST-----

**Comment by micbar** [comment]
@jnweiger please 😍.

**Comment by l0ckm4** [comment]
and thank you

**Comment by jnweiger** [comment]
Certificate Details:
        Serial Number: 4266 (0x10aa)
        Validity
            Not Before: Aug  6 16:32:32 2024 GMT
            Not After : Aug  4 16:32:32 2034 GMT
        Subject:
            commonName                = opal

Here is the cert:
----
-----BEGIN CERTIFICATE-----
MIIE8TCCAtkCAhCqMA0GCSqGSIb3DQEBCwUAMG0xCzAJBgNVBAYTAlVTMQ8wDQYD
VQQIDAZCb3N0b24xFjAUBgNVBAoMDW93bkNsb3VkIEluYy4xNTAzBgNVBAMMLG93
bkNsb3VkIENvZGUgU2lnbmluZyBJbnRlcm1lZGlhdGUgQXV0aG9yaXR5MB4XDTI0
MDgwNjE2MzIzMloXDTM0MDgwNDE2MzIzMlowDzENMAsGA1UEAwwEb3BhbDCCAiIw
DQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAL+p4xfb/SacxhKkH+J/o7wyxZy1
WojAuX2w2G1o4kzfl2z2jEDzL1/uuutdnFlTe0r5xjnNtjczlndZK947+U2tzIt9
wE5jjuHKwwasImlzKcWMiHiGZVvyzv1D5DSs/Y3InfNpWl+V6j9cw7XSJxkAzNhO
FmCQQflfUA4eG5p62DbLUz7rZi+BuNFcPa25vyCC/PlPkEWvYOvEE/4cPND3x4J8
nM90EQ3kutEiWdG39zZexwss/oKw7lCqWMnhrXgY5gILB4dq90abGoPSmxIOL7EV
xGYDARzVUsodwTQ6jXGOhzohTEQpwNBctkmSb3GMxwHAFz9SM6wV9jMl1O1zMmWK
fknvh+fx0ciCg7VCpVB7BoZN9f+VTDa6CDTf8IB8ndBX0wGSN67uH4wMxDBBYlvG
2drwvixlz9h0MaQOPk7PyPU+Jw82JQIgBYX0yUovwDowLLv7oMxZjEG7pvlmn/Oz
S3hMDeEhop4E+SCGUOKvZ4fS1nDbnd+CY+wkfkMREf1CN3n8EIcfBW5KPaTAFo2n
jqCEZ+p2UQ/QnVj1EiNkJBsebf4AV111gHAWx5ZXOxUx5vGDXAfHmMEfcxsefBsb
IHKQnvtksmJtY89gqY7001XXARRoa+uMh3Z4uSvCcFjbSq+oRse4rWi1oFVoKrtr
eni5R4lAy4A7fIwnAgMBAAEwDQYJKoZIhvcNAQELBQADggIBAHN7HkHAqE5lnlDx
fIFncsNKKjpSP8u6sM8YiMHVASNUlogUJxD2q74jUYvbxVKkNHodx2+2JSF3aggT
MgauS6ixzSRRzxBsZwvnoBYfTWpHiVgP5RpSDmPXB5ORjkOF3OJ/858o9eVsl2jA
GyEKGy44SsgyZ+jEWKncTvbOeHa0+zwK0BKtJzpdP/+0gScWJj9c3VDGjJbwyxpQ
ah8qyvzyvA2KosV5qOA+5IyryX5LNTel+wxeocl7YRadLMjwexSXKOdGP5pO9+Ry
PGMBwo7rpX992z6olRBYxZmj6KNwk5U/xGMn/eWLkoGqyC7lMnwiDO1kySKRHXc6
sO09IfsQidWZzqRiZ72wMyMyB8HESEosmFVpWSBNddeYTmKWKGMlxDF7XdZDQD1A
54wN6sqtqY5enJc/aAqR8JLsCLHaw0qaukqLb3DivWMLHEq1rZdIhL4QCEsXJ1Pd
YoHZ7n+NrnII4lTZTsne8hLS0If6WeS+GmnsT2dov7keCbgNGi4dyXQ2JGa5Ca8T
GypIlySIidOrcRKnsIw8FtIbvUvYJhXzrVBEdf0ZlUnrMYcw+mhCvTzWJyh3pPdp
l43qRaVnOHnbuN32E6YAIvCaBKBJzhcUlJEfQnwMq+ODxTuKzpkuilVQvBBlCT0s
g6SoQQjTqCjJqpBbfRWN0m5rP/IJ
-----END CERTIFICATE-----
