### ISSUE TITLE
Add flattr button to app store

### ISSUE THREAD

**Issue by PVince81** [owncloud/appstore-issues#2]
To make it possible for devs to receive donations more directly :-)

As discussed with @jancborchardt @schiesbn before

**Comment by oparoz** [comment]
Cool suggestion :)

**Comment by jancborchardt** [comment]
Honestly, Flattr is not very popular anymore. If we’re really serious about growing our app developer community then we should have an actual payment mechanism.

**Comment by oparoz** [comment]
Or simply let the developers add a link to their donation page. The cool thing about systems like flattr is that it's frictionless. You increase the rating and the donation is made.

**Comment by jancborchardt** [comment]
It’s not frictionless – people need to sign up for it, and barely anyone uses it anymore. ;) It would be a very weak statement from us as ownCloud to say »here you go folks, have some tips«.

**Comment by oparoz** [comment]
frictionless once you're signed up, unlike something like Paypal where you have to log in or fill in your details every time.

**Comment by DeepDiver1975** [comment]
appstore is dead - long live the marketplace!
For suggestion please head over to https://github.com/owncloud/marketplace-issues/
