### ISSUE TITLE
Remove »PIM« category, move apps to »Productivity«

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/appstore-issues#21]
Currently we only have 3 apps in the »PIM« category. Likely to the name being not understandable:
https://apps.owncloud.com/index.php?xsortmode=new&page=0&xcontentmode=921

I propose we move those 3 apps to »Productivity« and just remove the »PIM« category altogether. It just is a too technical term, and close to Productivity anyway.

@karlitschek @LukasReschke

**Comment by jancborchardt** [comment]
@karlitschek? I’d just simply move the existing PIM apps over to Productivity, but we still need to prevent the category from showing up there and in ownCloud apps mgmt. cc @LukasReschke

**Comment by karlitschek** [comment]
done

**Comment by jancborchardt** [comment]
Great, thank you!
