### ISSUE TITLE
Apps in ownCloud web interface should not be approved without description

### ISSUE THREAD

**Issue by sudhirkhanger** [owncloud/appstore-issues#22]
Documents and Bookmarks app in ownCloud web interface or on apps.owncloud.com have no description. Apps should only be allowed in App store if they have description, screenshot, contact information, etc.

https://apps.owncloud.com/content/show.php?content=168710
https://apps.owncloud.com/content/show.php?content=168711

**Comment by DeepDiver1975** [comment]
appstore is dead - long live the marketplace!
For suggestion please head over to https://github.com/owncloud/marketplace-issues/
