### ISSUE TITLE
Deactivate knowledgebase

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/appstore-issues#23]
https://apps.owncloud.com/kb – no one is looking at this and no one answers the questions there. It’s misleading to still have it there, and a beyond frustrating experience for people who get 0 reaction there.

The forum https://forum.owncloud.org/ has replaced the need for this entirely.

@karlitschek can we disable that? cc @DeepDiver1975 @LukasReschke @jospoortvliet

**Comment by karlitschek** [comment]
@jancborchardt I know that not a lot of the core people look there. But we have to plan the infrastructure and communication structure for 10x the number of 3rd party apps as we have today then we can´t direct all the users to github. I´m also not sure that we want to have a section for every app on the forum

**Comment by ghost** [comment]
If you could allow that only questions for specific apps can be asked at the kb its fine.

But the current state is not sustainable in my opinion. This was also discussed longer time ago in https://github.com/owncloud/appstore-issues/issues/1

**Comment by jospoortvliet** [comment]
I think it'd be nice to have a knowledge base, the forums aren't that great for it... I didn't even know about this one, though, and the ui is... meh. Although it works, I just answered a question :boom: 

But we have to decide to either promote it (and then we need to improve the user experience - this is not very good) or remove it...

**Comment by ghost** [comment]
We have already too few users at the forums giving support. Splitting them to another place is the worst thing which can be done here in my opinion.

**Comment by jancborchardt** [comment]
For individual apps there’s already the comment section which is used by people. If an app is more popular and that doesn’t scale, they will most likely use an issue tracker anyway (in the case of the Roundcube app for example).

Also agree with @RealRancor that splitting it up would not be good. If you remember, we had the knowledge base inside ownCloud back in ownCloud 3 or 4, and no one really answered questions either. I assumed that when removing it there and moving to the forum, it was also deactivated on apps.owncloud.com/kb

**Comment by DeepDiver1975** [comment]
appstore is dead - long live the marketplace!
For suggestion please head over to https://github.com/owncloud/marketplace-issues/
