### ISSUE TITLE
Stop downgrading approved app unless the archive was modified

### ISSUE THREAD

**Issue by oparoz** [owncloud/appstore-issues#24]
Looking at the ["The Appsreview Archives"](https://mailman.owncloud.org/pipermail/appsreview/), I can see that apps are downgraded whenever a change happens on the app's page.
- It wastes approvers' time
- It confuses users as some will swear they saw the app where as others will not see it

It should only be necessary to downgrade an app, if ever, if the archive was modified.

You could take it one step further and only manually downgrade an app, when there are complaints, or for any other valid reasons.

**Comment by karlitschek** [comment]
Can you please explain a bite more what you mean with downgrade? What exactly happens where when you do what?
Thanks a lot.

**Comment by oparoz** [comment]
Sure.

Take a look at this message which was automatically generated.

```
App updated: "Gallery 8.1"
User: "interfasys" (normal user)
Link:
http://apps.owncloud.com/content/show.php?content=169939
Status: approved => not approved
```

https://mailman.owncloud.org/pipermail/appsreview/2015-June/002699.html

All I did was to add some links to the app's page on the app store. The same happens if I edit the description, etc.

So, by downgrading the app from approved to "not approved", the system removes it from the apps page in all instances of ownCloud until someone approves it again (burden for both the users and the approvers). Given how little time approvers have to approve and review apps, the system should avoid creating unnecessary tasks.

**Comment by karlitschek** [comment]
Ahh. Now I got what you mean. :-)
It is on propose that an app that was approved but then changed falls back to not approved status. 
I think the solution for trusted developers like you can be to become an admin so that you can set your app always to approved.
What is your username on apps.owncloud.com?

**Comment by oparoz** [comment]
So, what's the rationale for switching to "not approved" when the description has changed? It has no impact on installed apps which only see the description from the package and the app itself hasn't been updated.
Are there guidelines somewhere for approvers, so that we know what to look for in such cases?

I use "interfaSys" in the app store.

**Comment by karlitschek** [comment]
There is no difference between small and big changes.
Yes. All of this needs to be explained better. @jospoortvliet Is working on that. :-)
You have approve rights now and you can approve your own apps yourself.

**Comment by oparoz** [comment]
OK :)
Thanks for making me an approver!

**Comment by jospoortvliet** [comment]
Yeah, see https://doc.owncloud.org/server/8.1/developer_manual/general/publishing.html (this link will probably stop working soon, as I moved the location of it in the index)

For 'normal' devs, every update has to be checked and approved. Once you're a 'trusted' dev, that is no longer the case.

If this isn't explained well enough, let me know (or do a PR on the documentation :D)

**Comment by oparoz** [comment]
I think the key is to give approve rights to all devs of approved apps. That way that back and forth dance never happens and it doesn't even need to be mentioned in the documentation since it has no effect on experimental apps.

So just something to add to your reviewing process map :)

**Comment by jospoortvliet** [comment]
@oparoz if you give approve rights to all devs of approved apps, they could sneak evil stuff in the app store. We trust you and some other ppl we know not to do that and thus you get approver status - a separate thing for security reasons.

**Comment by oparoz** [comment]
Hmmm... But if they're approved, they should have been vetted according to your doc:

> Approved apps are developed by trusted developers and have passed a cursory security check

**Comment by jospoortvliet** [comment]
@oparoz pffff, looks like there's a detail off there ;-)

@LukasReschke what exactly should this be - can only trusted developers make 'approved' apps? Then they shouldn't require any more checking...

**Comment by LukasReschke** [comment]
> @LukasReschke what exactly should this be - can only trusted developers make 'approved' apps? Then they shouldn't require any more checking...

Cursory security check = The code does not look that bad that it explodes on the first sight ;-) - Who can mark apps as approved: No idea :speak_no_evil:

**Comment by DeepDiver1975** [comment]
appstore is dead - long live the marketplace!
For suggestion please head over to https://github.com/owncloud/marketplace-issues/
