### ISSUE TITLE
Every app store comes with stats

### ISSUE THREAD

**Issue by oparoz** [owncloud/appstore-issues#25]
It would be very useful for devs to have access to some stats.
Piwik would be nice, but at a minimum we should have access to 
- the number of downloads from apps.owncloud.com
- the number of downloads straight from ownCloud. (Currently not counted)
- a breakdown between versions

**Comment by DeepDiver1975** [comment]
appstore is dead - long live the marketplace!
For suggestion please head over to https://github.com/owncloud/marketplace-issues/
