### ISSUE TITLE
First run experience: Empty »Games« category, strange »Other« category

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/appstore-issues#26]
So we have a category called »Games«: https://apps.owncloud.com/index.php?xcontentmode=923 – no apps there. Since the category comes up empty we should remove it before the 8.1 release.

Also, the nondescript »Other« category is a strange catchall. https://apps.owncloud.com/index.php?xcontentmode=925 – the few apps actually in there can simply be moved to the »Tools« category.

@karlitschek can you do that? I think this makes for a cleaner appstore. We should only introduce categories which are reasonable and where there are apps for. cc @LukasReschke @DeepDiver1975

**Comment by karlitschek** [comment]
You don't like my awesome pong game? :-) https://apps.owncloud.com/content/show.php/Pong+Game?content=166942
We can discuss the categories for the future but definitely no last minute changes now.

**Comment by LukasReschke** [comment]
> You don't like my awesome pong game? :-) https://apps.owncloud.com/content/show.php/Pong+Game?content=166942

The one that can't get installed because it's announcing to be a ZIP while it is actually  a gzipped file? :speak_no_evil:  – Thus the category actually is empty.

```
➜  ~  file /Users/lukasreschke/Downloads/166942-pong.zip
/Users/lukasreschke/Downloads/166942-pong.zip: gzip compressed data, from Unix, last modified: Tue Sep 16 21:48:22 2014
```

**Comment by ghost** [comment]
Its not even listened because it has an Maximum required   ownCloud 7 set.

**Comment by jancborchardt** [comment]
Ok, so can we now please get rid of the »Other« category? It’s nondescript, empty for ownCloud 8.1 and 8.2 and all apps categorized as it in the appstore should be moved to the »Tools« category.

**Comment by ghost** [comment]
With experimental apps on oC 8.1 you're getting two apps in the "Other" category:

Old Menu
videoStream (3 times)

**Comment by jancborchardt** [comment]
@RealRancor just moved Old Menu over to »Tools«.

And videoStream seems to be a reupload of someone elses content, as all other apps from this person – all without description and just registered 2 hrs ago –> deleted.

**Comment by ghost** [comment]
Great, thanks.

> And videoStream seems to be a reupload of someone elses content, as all other apps from this person – all without description and just registered 2 hrs ago –> deleted.

Ah, yes. Have seen something like this in the past. No idea if those are bots trying to spread malware?

**Comment by ghost** [comment]
Another app hit the "Other" category:

https://apps.owncloud.com/content/show.php?content=168132

Probably better to put it either in the "Productiviy" or "Tools" category?

**Comment by jancborchardt** [comment]
@RealRancor thanks, relocated to »Tool«.

@karlitschek can we please remove the »other« category, move all of the apps still in there to »Tool« and rename »Tool« to the more correct »Tools«? Thanks! :)

**Comment by ghost** [comment]
Another one: https://apps.owncloud.com/content/show.php?content=167919 currently shown in oC 8.1:-)

**Comment by jancborchardt** [comment]
> @karlitschek can we please remove the »other« category, move all of the apps still in there to »Tool« and rename »Tool« to the more correct »Tools«? Thanks! :)

**Comment by karlitschek** [comment]
done

**Comment by jancborchardt** [comment]
cc @msrex @cmonteroluque who also noted the empty »Games« category in the update process. We should not show it when it’s empty, and maybe disable it for the enterprise edition anyway. @karlitschek @schiesbn?

**Comment by karlitschek** [comment]
@MTRichards and I discussed this lately. The AppStore should be disabled for Enterprise except it is explicitly enabled in config.php 
This should be in 8.2.1 Enterprise already. The current 8.2.0 is Community only of course.

**Comment by jancborchardt** [comment]
Ok, that works as well.
