### ISSUE TITLE
As a user i want to have an overview of apps to which i'm subscribed

### ISSUE THREAD

**Issue by ghost** [owncloud/appstore-issues#27]
Until core has implemented an overview / notifications for apps which needs an update its nice to have the subscription function available on the appstore. Unfortunately the appstore doesn't provide an overview over all app which i'm subscribed to.

**Comment by DeepDiver1975** [comment]
appstore is dead - long live the marketplace!
For suggestion please head over to https://github.com/owncloud/marketplace-issues/
