### ISSUE TITLE
Overhaul and align the app rating system

### ISSUE THREAD

**Issue by oparoz** [owncloud/appstore-issues#28]
The current rating system is "broken", because it sends the wrong message to users. It's not aligned with what you find in other app stores and is confusing to users.
### Problems
1. Apps start at 50%. It makes zero sense
2. You're trying to match stars (in `settings/apps`) with a rating system with an entirely different scaling mechanism (app store). Another fail
3. It doesn't reflect the truth. An app could have gotten 30 votes 3 years ago and be half-broken today. People install it only to realise it's doesn't live up to its rating
4. Now that the app store within oC is working, people don't have a reason to visit the app store and thus won't vote for apps unless devs start adding reminders in their app or heavily promote them on social media

**With 2.5 stars, is the heavily promoted Documents app that bad?**
![documents_rating](https://cloud.githubusercontent.com/assets/323220/8683443/2e728ffa-2a73-11e5-998b-87963a678277.png)
### Solutions

The best solution would be to fix the app store to use the same stars rating used inside ownCloud and to let users pick how many stars they want to award. That's how it works virtually everywhere else.
It would be great if you could even let admins vote from within ownCloud, but that would mean tracking userid@instance to make sure they can only vote once.
And of course, there wouldn't be a rating, unless 10 (or more) votes have been collected.
Current votes can be converted to a 5 and ratings can be modified at any times. There is no reason to leave an app at 5 stars if you can't even install it on the latest version of ownCloud.

People are usually looking for 5 stars apps in mobile app stores. When you see 4 or less, it usually means that something went wrong.
Companies behind large app store have taken a lot of care to improve their rating system in order to make it easier for users to find the best apps and have per version rating since everybody knows a lot can happen over time. It would be great if ownCloud could follow their foot steps.

If it's too difficult to change system in the app store, then at least fix how you present the information there. Show the number of :+1: or :-1:, not a percentage. And fix ownCloud itself https://github.com/owncloud/core/issues/17629.

@karlitschek @DeepDiver1975 @jancborchardt @libasys @nickvergessen @Raydiation @jospoortvliet 
And forward this to as many devs as possible to get some feedback.

**Comment by RobinMcCorkell** [comment]
I agree - this behaviour irks me about the app store.

**Comment by karlitschek** [comment]
It's not perfect and should and can be improved. But calling it 'broken' sounds a bit harsh to be considering that it is used for 15 years by over 2 million happy users. :-)
Let see what we can do to improve.

**Comment by oparoz** [comment]
I agree, it's harsh, but I really think it's of very little value to users and bad for developers. The fact that KDE users have not complained for 15 years is not really a benchmark in my eyes ;) . kde-apps.org suffers from exactly the same problems. It's difficult to discover fresh, good apps. You have to look at the dates, read comments, read the list of issues, etc. Only a determined user will do all this. Some will trust the rating and miss some of the best the store has to offer, others will just ignore the rating and take a chance.
But the biggest problem is that it's badly translated into a stars rating system on the ownCloud side, so it would be good to know if things can evolve quickly on the app store or if ownCloud itself has to be modified.

**Comment by jancborchardt** [comment]
> The fact that KDE users have not complained for 15 years is not really a benchmark in my eyes ;)

I will frame this quote and put it on my wall. ;D

Totally agree with @oparoz btw. We need to improve the app rating system as well as the way it influences presentation.

**Comment by BernhardPosselt** [comment]
Let's get the formula first then :) any ideas? Reference work?

**Comment by oparoz** [comment]
### Ultimate goal
- Stars rating 1-5
- Give breakdown per level ( 3 x 3 stars, 7 x 5stars, etc.)
- Breakdown per version. Only worth it if people can vote from ownCloud since top apps never seem to get more than 50 votes over many years.
- Comments with rating (important!)

![google_rating](https://cloud.githubusercontent.com/assets/323220/8676939/b054ab74-2a4c-11e5-839e-659f9e2b85eb.png) ![amazon_rating](https://cloud.githubusercontent.com/assets/323220/8676942/b474b96a-2a4c-11e5-8f1a-fbd26fb95c07.png)

### 1st step
- Introduce a simple 1-5 stars rating in the app store
- Convert :+1: into a  :star: :star: :star: :star: :star: 
- Convert :-1: into a :star: :star: 
- Modify ownCloud to retrieve the global rating (i.e. 3.75) and convert it to :star: :star: :star: :star:. Use half or even quarter stars if you can.

I'm not sure the conversion can happen, it depends on whether or not you keep track of individual votes or if you just save the total.
What should be done if we only have the total? I have no good idea yet. Let's first see if that's the case.

Per version rating is important. It would quickly show what works and what doesn't for the current version of ownCloud. Just because it's official or approved doesn't mean it doesn't have issues and some users might prefer an experimental apps with 15 5-stars instead of an official one with 25 3-stars.

**Comment by jospoortvliet** [comment]
Looks solid, @oparoz

**Comment by RobinMcCorkell** [comment]
:+1: for @oparoz's proposal

**Comment by ghost** [comment]
Is this a good Team Week project? (for the next one)

**Comment by jospoortvliet** [comment]
@cmonteroluque this would be about changing apps.owncloud.com - part of a series of websites ran by Frank. I don't know how feasible it is.

**Comment by BernhardPosselt** [comment]
We'll need to rewrite the app store at some point anyways to remove redundancy and make it work on git repos like any other package manager. The way it is now is simply unmaintainable because the code is not open source. I also doubt that the situation would improve if it was open sourced because the code has probably aged quite a bit (same problem as any other long going software project really)

**Comment by DeepDiver1975** [comment]
appstore is dead - long live the marketplace!
For suggestion please head over to https://github.com/owncloud/marketplace-issues/
