### ISSUE TITLE
Make privacy policy mandatory and force devs to divulge how they use cookies

### ISSUE THREAD

**Issue by oparoz** [owncloud/appstore-issues#29]
Most app stores force developers to include a privacy policy as they often have access to personal information.
So just like most ownCloud apps are labelled experimental because they can potentially destroy all data, app devs should be forced to include a privacy policy describing how they use the data they're processing.

At the same time, app devs should be forced to reveal if their app sets cookies and for what purpose. There are quite strict laws in the EU regarding getting a user's consent to use cookies or to simply let them know you're using some.

**Comment by DeepDiver1975** [comment]
appstore is dead - long live the marketplace!
For suggestion please head over to https://github.com/owncloud/marketplace-issues/
