### ISSUE TITLE
App store not returning updates

### ISSUE THREAD

**Issue by PVince81** [owncloud/appstore-issues#3]
From OC 6.0.4 I don't get any upgrades.

```
$ curl 'http://apps.owncloud.com/updater.php?version=6x0x4x1x1406140131.3933x1406140652xstablexx2014-06-24T15:11:49+00:00'

<?xml version="1.0"?>
<owncloud>
  <version></version>
  <versionstring></versionstring>
  <url></url>
  <web></web>
</owncloud>
```

Or are only minor upgrades supported there ?

**Comment by PVince81** [comment]
@karlitschek @VicDeo

**Comment by VicDeo** [comment]
Feed will be updated with  7.0.1 release

**Comment by MorrisJobke** [comment]
same on ownCloud 7 instance

**Comment by VicDeo** [comment]
Duplicate of https://github.com/owncloud/updater/issues/21

> Feed will be updated with 7.0.1 release

This is done intentionally. Closing
