### ISSUE TITLE
Adjust the design to fit ownCloud

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/appstore-issues#30]
The design of the appstore arguably looks out of place and different than the rest of ownCloud. It would be good if we can adjust the style, and even better if we can integrate it into the https://owncloud.org website.

cc @karlitschek @jospoortvliet @DeepDiver1975

**Comment by jancborchardt** [comment]
Btw also to answer the question about why we need this to be a nicely designed public page, instead of just the apps lying around on Github + the ability to install them from inside ownCloud:

Lots of times I want to link people to a specific app and say »hey, ownCloud also offers this«. These people do not necessarily have ownCloud installed. Just now on a Hacker News thread on self-hosted alternatives I wanted to recommend the Documents app to someone there: 
- Do I link to https://github.com/owncloud/documents/ ? – nope, that’s a dev-focused code page and doesn’t even have screenshots. Different target audience.
- Do I link to https://apps.owncloud.com/content/show.php/Documents?content=168711 ? – no way, it might have a screenshot but it’s ugly as hell so people will not even consider it.
- Do I link to https://doc.owncloud.org/server/8.2/user_manual/documents.html ? – no, too much text because it’s an in-depth documentation, not a simple short presentation of the app. Different target audience.
- In the end I linked to the blog post at https://owncloud.org/blog/owncloud-7-sneak-peek-online-collaboration-with-documents/ which is outdated, also has lots of text and just one screenshot of the overview.

cc @DeepDiver1975 just because you often state that a public appstore is not necessary. ;)

**Comment by jospoortvliet** [comment]
@jancborchardt I have the same issue frequently, both on .org (I want to link people to a place where they can see how many awesome apps we have but apps.owncloud.com is NOT nice) and on social media.

Now I agree with @DeepDiver1975 to some extend - from my perspective, 'just' having a read only view of our available apps on owncloud.org would suffice. Accounts which allow commenting, rating and all that stuff can be built into ownCloud itself (would be great!) but doesn't have to be accessible by people from the web. Would probably also avoid an entire class of potential security breaches making @LukasReschke happy.

Of course, we'd still need an UI for app authors to add their apps so I'm not advocating to kill apps.o.c - but having a good looking view on our apps you can link people to would be nice.

**Comment by jancborchardt** [comment]
I would say that the location for viewing apps, rating, commenting, and submitting should be the same though. We don’t make it easier on us nor on developers or users if we split a »read-only« page and then a separate appstore.

The question is how we go forward. Do we improve apps.owncloud.com? Do we use another system like the Firefox OS appstore as base? How do we make sure it’s nicely integrated with owncloud.org? Something completely different?

@karlitschek @LukasReschke @DeepDiver1975 @cmonteroluque I’d like to have a healthy discussion on this because it sticks out in our UX and developer experience.

**Comment by karlitschek** [comment]
there will be significant improvements very soon. please stay tuned

**Comment by vascowhite** [comment]
I would like to bump this. 

I have been using OC for over a year now and I love it. I would have been using it for longer, except that the app store looked amaturish and has an 'abandoned' feel to it. Probably because it doesn't match the slick design of owncloud.org at all. 

@karlitschek Any sign of those 'significant improvements' yet :)

**Comment by jospoortvliet** [comment]
The 'significant improvements' was pretty much the fact that it is sold - and the new owner has plans, not sure how that's progressing... See http://karlitschek.de/2016/01/opendesktop-org-changes/

**Comment by jancborchardt** [comment]
Just for the record, here’s how the Sandstorm app market looks like: https://apps.sandstorm.io

**Comment by DeepDiver1975** [comment]
appstore is dead - long live the marketplace!
For suggestion please head over to https://github.com/owncloud/marketplace-issues/
