### ISSUE TITLE
Missing data for Calendar app (id 168707)

### ISSUE THREAD

**Issue by marcinkoziej** [owncloud/appstore-issues#33]
Calendar App has an id of 168707 as shown here https://apps.owncloud.com/content/show.php/Calendar?content=168707/content/data

but when I try to install the app, I get the error:
Unable to parse OCS content
Invalid OCS content returned for app 168707

This is because there is no data in under the app data url my ownCloud tries to fetch:
https://api.owncloud.com/v1/content/data/168707

```
<ocs>
  <meta>
   <status>failed</status>
   <statuscode>101</statuscode>
   <message>content not found</message>
  </meta>
</ocs>
```

**Comment by karlitschek** [comment]
I think this request is incomplete. For example you didn't include the currently used ownCloud version.
