### ISSUE TITLE
Remove "Placeholder for future updates" apps from appstore

### ISSUE THREAD

**Issue by ghost** [owncloud/appstore-issues#34]
Hi,

currently the following apps are found within the appstore containing a "Placeholder for future updates":

https://apps.owncloud.com/content/show.php/Tasks?content=166058
https://apps.owncloud.com/content/show.php/Videoviewer?content=166054
https://apps.owncloud.com/content/show.php/Filesharing?content=166050
https://apps.owncloud.com/content/show.php/Documents?content=166045
https://apps.owncloud.com/content/show.php/Contacts?content=166044
https://apps.owncloud.com/content/show.php/Calendar?content=166043
https://apps.owncloud.com/content/show.php/Bookmarks?content=166042
https://apps.owncloud.com/content/show.php/Admin+Dependency+check?content=166041

As those just looks like dummy apps without any use to me consider to remove them from the appstore.

cc @karlitschek @LukasReschke

**Comment by LukasReschke** [comment]
Done. THX.
