### ISSUE TITLE
cert expired

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/appstore-issues#36]
https://mailman.owncloud.org/pipermail/devel/2015-November/001772.html
https://forum.owncloud.org/viewtopic.php?f=36&t=31723#p102123
https://github.com/owncloud/core/issues/20779

@karlitschek

**Comment by danimo** [comment]
@karlitschek talk to markus or me about where to get the updated cert.

**Comment by ghost** [comment]
@nickvergessen @danimo The cert is renewed so this one could be closed.
