### ISSUE TITLE
Updater URL is pointing to 8.1 upgrade manuals

### ISSUE THREAD

**Issue by ghost** [owncloud/appstore-issues#38]
https://updates.owncloud.com/server/?version=8x0x0x7x1382907615.86x1435439812xstablexx2015-02-07T02:34:55+00:00

is currently pointing to https://doc.owncloud.org/server/8.1/admin_manual/maintenance/upgrade.html

I don't know if this is used somewhere but still makes sense to use 8.2 instead.

cc @karlitschek

**Comment by karlitschek** [comment]
fixed.
