### ISSUE TITLE
Differentiate update candidates by version

### ISSUE THREAD

**Issue by VicDeo** [owncloud/appstore-issues#4]
We use current version in the request to appstore and request contains current OC version.

In order to support correct mugration order it would be nice to respond with the different  links: 
- to the latest  OC7 for 6.x 
- to the latest  OC6 for 5.x 
- to the latest  OC5 for 4.5.x 

etc...

**Comment by VicDeo** [comment]
There is a little sense in providing a link to OC7 for OC5 instances as we don't support direct 5->7 migration anyway.

**Comment by tflidd** [comment]
Why does the update-app do upgrades in the first place? In the documentation (for OC 6 at least), it says that it is only supposed to do updates. A lot of people are running into problems, can't you put some message like "you are on the last release of your version, if you want to upgrade, you need to do it manually -> link to documentation"?

It's a nice function to do automated updates (including backups before) but only if it works properly. Don't get my wrong, I appreciate your work and the update app works fine for a lot of people. But if the updates risk to fail, not so experienced users are easily discouraged.

**Comment by VicDeo** [comment]
@tflidd it's dumb and uses a link to a package provided by appstore. 
And the link is always pointing to the most recent version (to 7.0.2 currently) for _any_ owncloud version

**Comment by tflidd** [comment]
@VicDeo Unfortunately, there is nothing about that in the documentation! If Firefox suggest an update to a never version, I will use the update function and expect it to work. Imagine you do an update, it fails and after some research you find an entry on their bugtracker that updates from version 28 -> 31 are not supported.

For the documentation, I already submitted some remarks for OC 6: https://github.com/owncloud/documentation/issues/424, the new documentation is even worse because it mentions the manual and "secure" way very late. And the difference between update and upgrade isn't as clear as before.

**Comment by ghost** [comment]
@VicDeo 
Think this can be closed as you already had added an check to avoid skipping versions in https://github.com/owncloud/updater/pull/35 ?

**Comment by VicDeo** [comment]
@RealRancor no. this is about the upgrade path
Check prevents from skipping major versions in emergency cases but the appstore feed should suggest the correct candidate for each instance (e.g. do not offer OC8 sources as a replacement for OC4)

**Comment by ghost** [comment]
@VicDeo So how can we pull some one in here to fix that issue? Had a user asking again why the updater is trying to jump over major upgrades:

https://forum.owncloud.org/viewtopic.php?f=29&t=31336&p=101229#p101224

**Comment by ghost** [comment]
Honestly, this should be really fixed. Its now open since more than one year. I think it shouldn't be that hard to implement that the updating URL is responding with the correct version.

**Comment by a-schild** [comment]
Just stumbled into this one when going from 8.0.4 to 8.2.0

**Comment by ortonomy** [comment]
Yes, had an issue with this going from 8.0.3 to 8.2.1. Can't upgrade because of major versions. Didn't warn me in the updater.

**Comment by ghost** [comment]
Ref: https://github.com/owncloud/core/issues/20640, https://github.com/owncloud/core/issues/20660

Probably will see further issues like those if the updater url is not getting fixed.

**Comment by MichaelSp** [comment]
> Probably will see further issues like those if the updater url is not getting fixed.

True. Here we go again. (Updating from 8.0.3.4 to 8.2.1)
How do I repair my screwed installation now?

**Comment by ghost** [comment]
See the issues linked one comment above yours

**Comment by mzaian** [comment]
Guys after facing all the related issue i just need to upgrade my current version 7.0.3 to the latest while i have the opensuse repo configured but when i try the apt method its downloading the 8.1.4\* version and i cannot upgrade from my current version to it.

Do you have a guide to perform the upgrade to the versions one by one using the repos or manually, i was reading many documents in https://doc.owncloud.org/server/7.0/admin_manual/maintenance/upgrade.html but its not clear.

Thanks

**Comment by ghost** [comment]
@mzaian This is unrelated as you shouldn't use the updater app with repositories. Please also use the forums for such support questions.

**Comment by mzaian** [comment]
I Tried on my cloned test instance the updater app once and it broke the installation, later i started using the repos from command line and i was facing the same problem.

**Comment by ghost** [comment]
Just use the forums for more discussions / support. It is known that this is broken and needs to be fixed

**Comment by karlitschek** [comment]
@LukasReschke can you backport the change of the updater url? after that we can implement the proposed logic here.
What do you think?

**Comment by ghost** [comment]
Are there any backports needed to fix this?

From my understanding oC 8.0.9 for example is calling:

https://apps.owncloud.com/updater.php?version=8x0x9x1338030373.1628x1373617342.3379xstablex

which currently returns 8.2.1 as the latest version. The whole problem here would solved if the updater URL is returning 8.1.4 for that 8.0.9 version (that info could be gathered from the ?version get parameter.

**Comment by LukasReschke** [comment]
> @LukasReschke can you backport the change of the updater url? after that we can implement the proposed logic here.
> What do you think?

Done in https://github.com/owncloud/core/pull/20808, the URL is used starting in 8.1. As stable7 is security patch only I did not open a backport, but we can do a cherry-pick if we want to.

**Comment by VicDeo** [comment]
hm. New URL still reports 8.2.1 regardless the current OC version and channel
At least
https://updates.owncloud.com/server/?version=6x0x0x0x1423763974.698x1446495849xstablexx
https://updates.owncloud.com/server/?version=6x0x0x0x1423763974.698x1446495849xproductionxx
are both 8.2.1

**Comment by nikogh** [comment]
Just ran into the same issue :(

**Comment by nikogh** [comment]
Thx to RealRancor for the following workaround! This helps to get rid of the error message and restores the installation:

> 1. Remove all files and folders expect /data/ and /config/
> 2. Download 8.0.9 from the changelog posted above and extract it into your install dir
> 3. Run the update via the webgui
> 
> Repeat those steps with 8.1.4 and 8.2.2

**Comment by LukasReschke** [comment]
@karlitschek I've written a new update server which is completely integration- and unit-tested using Behat and PHPUnit. Let's talk about this today. This should finally resolve this issue :smile:

**Comment by VicDeo** [comment]
@LukasReschke any chance for me to have look at it?

**Comment by LukasReschke** [comment]
@VicDeo https://github.com/owncloud/administration-internal/pull/12

**Comment by ghost** [comment]
Is it really true? The update server is finally shipping the correct versions :rocket:

https://updates.owncloud.com/server/?version=8x0x0x7x1382907615.86x1435439812xstablexx2015-02-07T02:34:55+00:00

**Comment by LukasReschke** [comment]
Yep. We just deployed my new updater server 😉

**Comment by ghost** [comment]
@LukasReschke :dancers: 

However it seems that 9.0.2 is not provided to 8.2.4 users as this:

https://updates.owncloud.com/server/?version=8x2x4x7x1382907615.86x1435439812xstablexx2015-02-07T02:34:55+00:00

is returning a `XML Parsing Error: no element found` where:

https://updates.owncloud.com/server/?version=8x2x3x7x1382907615.86x1435439812xstablexx2015-02-07T02:34:55+00:00

is providing 8.2.4

**Comment by LukasReschke** [comment]
Yes. We are at the moment by intention not serving updates to 9.0 for the stable and production channel. If someone really wants if they can switch to the "beta" one:

https://updates.owncloud.com/server/?version=8x2x4x7x1382907615.86x1435439812xbetaxx2015-02-07T02:34:55+00:00

I don't feel comfortable to serve this broadly yet as a lot of users have a misconfigured overwrite.cli.url setting, once https://github.com/owncloud/core/pull/24540 is in we can enable that for 9.0.3 for all users.

**Comment by ghost** [comment]
Ahhh, good to know. Then this blogpost probably should be updated:

https://owncloud.org/blog/maintenance-releases-9-0-2-8-2-4-8-1-7-8-0-12-and-7-0-14-out-time-to-upgrade/

As it is talking that releases should be available at the end of the last week.

Cc @jospoortvliet

**Comment by ghost** [comment]
But just wondered, 9.0.2 is provided to users of 9.0.0 and 9.0.1:

https://updates.owncloud.com/server/?version=9x0x0x7x1382907615.86x1435439812xstablexx2015-02-07T02:34:55+00:00

So 9.0.2 is definitely shipped, but not for users of 8.2.4

**Comment by Akhenaton** [comment]
Yeah, i was on 9.01 and the repos for Ubuntu 14.04 provided me with the 9.02 running fine actually !  :laughing:

**Comment by ghost** [comment]
@Akhenaton This one here is not about the repos. :-)

**Comment by Akhenaton** [comment]
Ooops, sorry, i've just had a too good lunch, really sorry.....   :zzz:
