### ISSUE TITLE
Support single-step upgrading from any version to current version

### ISSUE THREAD

**Issue by jernst** [owncloud/appstore-issues#40]
Upgrading while skipping a major package version currently is a lot of manual work. ("Download; install; upgrade; uninstall; repeat" per [forum post](https://forum.owncloud.org/viewtopic.php?f=17&t=32087).) This should be automated.

Many users have run into this, as the many duplicate bug reports related to "Exception: Updates between multiple major versions and downgrades are unsupported." [show](https://github.com/owncloud/core/issues?utf8=%E2%9C%93&q=Updates+between+multiple+major+versions+and+downgrades+are+unsupported.).

Mediawiki has one way of doing this kind of thing. At every release, they add whatever migrations needed to be done at the end of a long upgrade script, which grows with every release. As a result, the script can upgrade any old version of Mediawiki and installs of intermediate versions are never required.

This is important not just for people who don't upgrade ownCloud every time a new version comes out, but particularly for being able to restore old backups.

We just ran into this issue on UBOS where users may end up with partially non-functioning devices as we cannot invoke any code (unless we develop it ourselves) that migrates and will work for all possible ownCloud installs. See also https://github.com/uboslinux/ubos-owncloud/issues/9.

(I just added this here because lots of the reports point to https://github.com/owncloud/appstore-issues/issues/4, there may be a better place where to file this.)

**Comment by karlitschek** [comment]
I assume that you are talking about ownCloud upgrades and not upgrades of ownCloud apps?
If this is the case then this is the wrong repo. This is a core issue but also a duplicate.

**Comment by jernst** [comment]
Moved to https://github.com/owncloud/core/issues/21859
