### ISSUE TITLE
QOwnNotes isn't a ownCloud App

### ISSUE THREAD

**Issue by aspdye** [owncloud/appstore-issues#41]
Hi there,

Why is it allowed to publish QOwnNotes in the ownCloud AppStore? It isn't a ownCloud App - it's a desktop Tool ;)

https://apps.owncloud.com/content/show.php/QOwnNotes?content=168497

cc @karlitschek @MTRichards

**Comment by aspdye** [comment]
cc @karlitschek

**Comment by karlitschek** [comment]
Not sure if this is a problem. It is still something that belong to the ownCloud ecosystem

**Comment by aspdye** [comment]
Yeah. Android Apps for CalDAV and CardDAV belong to the Ecosystem too - but that still does not make them to an appstore app :wink:

**Comment by spoorun** [comment]
Perhaps they should be in the appstore, but in separate sections: 
Apps for Desktop, Apps for Devices.
