### ISSUE TITLE
Appstore version filter is broken for 9.0

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/appstore-issues#43]
The [Announcement Center](https://apps.owncloud.com/content/show.php?content=173921) clearly states that it has downloads for 8.2 and 9.0,
Both downloads work manually.

However the app does not show up for 9.0, only for 8.2
Filter 9.0: https://api.owncloud.com/v1/content/data?version=9x0x0x0&categories=922 :x: 
Filter 8.2: https://api.owncloud.com/v1/content/data?version=8x2x0x0&categories=922 :white_check_mark: 

@karlitschek would be nice if you can fix this, so people can test the app for 9.0

**Comment by LukasReschke** [comment]
Yup. Would be awesome. Especially as @nickvergessen just tested signing his app so we can test the signing in a real life scenario for apps as well :rocket:

**Comment by nickvergessen** [comment]
@karlitschek any chance?

**Comment by karlitschek** [comment]
yes. i will definitely have a look later today

**Comment by karlitschek** [comment]
fixed now.

**Comment by nickvergessen** [comment]
Thanks, works :)
