### ISSUE TITLE
apps.owncloud.com down

### ISSUE THREAD

**Issue by robje** [owncloud/appstore-issues#44]
Currently apps.owncloud.com (resolves for me to IP address 85.25.74.45) is down.
IP address is pingable, but both HTTP (port 80) and HTTPS (port 443) are unresponsive.

**Comment by karlitschek** [comment]
fixed. It took serverloft 19 hours to reboot a server. :-/

**Comment by matthewprenger** [comment]
~~Is the server down again? Getting a connection refused on both port 80 and 443.~~

Edit: Seems to be back up now.
