### ISSUE TITLE
Appstore shows apps in 9.0 that are not tagged for 9.0

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/appstore-issues#46]
@danimo just noticed that the appstore shows entries for 9.0 that are not tagged for 9.0

For example https://apps.owncloud.com/content/show.php?content=168708 is displayed in https://api.owncloud.com/v1/content/data?version=9x0x0x0&categories=922

cc @karlitschek

**Comment by karlitschek** [comment]
fixed. thanks for noticing.
