### ISSUE TITLE
Proprietary apps are available in the app store

### ISSUE THREAD

**Issue by oparoz** [owncloud/appstore-issues#49]
Last time I checked, all ownCloud apps which install within ownCloud have to be compatible with the AGPL, but the license dropdown has an entry which says "Proprietary license" and people have started publishing proprietary apps.

So has anything changed and apps are studied on a case by case basis or was that license entry a mistake and those apps have to be deleted?

@karlitschek @LukasReschke @jospoortvliet @MorrisJobke

**Comment by karlitschek** [comment]
We are trying to find a solution for this problem. Ideally we would be a bit more flexible regarding licenses of 3rd party apps. But this is tricky. Let's see.

**Comment by oparoz** [comment]
I'm glad to hear it. License compatibility issues aside, having proprietary apps in the app store in not necessarily a bad thing as it can still helps promote the platform AND it's very convenient for users to find new apps.

**Comment by karlitschek** [comment]
Yes. I have no problem with someone making a living with ownCloud apps. Actually i think it is a good thing. but we have to sort out the licensing question.

**Comment by DeepDiver1975** [comment]
appstore is dead - long live the marketplace!
For suggestion please head over to https://github.com/owncloud/marketplace-issues/
