### ISSUE TITLE
How to provide apps for multiple versions of ownCloud

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/appstore-issues#5]
I can select for my app following versions:
- stable5 or higher
- stable6 or higher
- stable7 or higher 

But if my app has "stable6 or higher" selected it isn't listed in owncloud 7. That's weird and annoying.

I need to change this to "stable7 or higher" to list that package on stable7 instances.

I have now two options:
1. change the old package to oc7 (upgraded instances will get the newest app version, but people who wants to stay with oc6 will need to remove the old app and install a new one)
2. create a new package for oc7 (vice versa as above)

Both solutions are bad and weird.

cc @karlitschek @VicDeo 

There is also an open issue in core: owncloud/core#10164

**Comment by karlitschek** [comment]
Hmm. Have you verified this lately? Nowadays you can set a minimum and a maximum version in the app store. Or do I miss the point?

**Comment by MorrisJobke** [comment]
I just added a breakpoint here:https://github.com/owncloud/core/blob/master/lib/private/ocsclient.php#L115

Got following URL and this should contain at least two music apps (on I tagged with ownCloud 6 or higher [1] and one with ownCloud 5 or higher [2]) but it just retrieves the first one:

```
view-source:http://api.apps.owncloud.com/v1/content/data?categories=920x921x922x923x924x925&sortmode=new&page=0&pagesize=100&filter=approved&version=6x0x4x1
```

Response:

```
<?xml version="1.0"?>
<ocs>
 <meta>
  <status>ok</status>
  <statuscode>100</statuscode>
  <message></message>
  <totalitems>9</totalitems>
  <itemsperpage>100</itemsperpage>
 </meta>
 <data>
  ...
  <content details="summary">
   <id>166469</id>
   <name>Music</name>
   <version>0.3.3</version>
   <label>recommended</label>
   <changed>2014-08-12T20:32:12+02:00</changed>
   <created>2014-08-06T11:01:21+02:00</created>
   <typeid>920</typeid>
   <typename>ownCloud Multimedia</typename>
   <language></language>
   <personid>mjob</personid>
   <profilepage>http://opendesktop.org/usermanager/search.php?username=mjob</profilepage>
   <downloads>207</downloads>
   <score>50</score>
   <description>Music player and server for ownCloud 6</description>
   <comments>0</comments>
   <fans>0</fans>
   <licensetype>16</licensetype>
   <approved>0</approved>
   <category>1</category>
   <license>AGPL</license>
   <preview1>http://apps.owncloud.com/content/preview.php?preview=1&amp;id=166469&amp;file1=166469-1.jpg&amp;file2=166469-2.png&amp;file3=&amp;name=Music</preview1>
   <previewpic1>http://apps.owncloud.com/CONTENT/content-pre1/166469-1.jpg</previewpic1>
   <smallpreviewpic1>http://apps.owncloud.com/CONTENT/content-m1/m166469-1.png</smallpreviewpic1>
   <detailpage>http://apps.owncloud.com/content/show.php?content=166469</detailpage>
   <downloadtype1></downloadtype1>
   <downloadway1>0</downloadway1>
   <downloadprice1>0</downloadprice1>
   <downloadlink1>http://apps.owncloud.com/content/download.php?content=166469&amp;id=1</downloadlink1>
   <downloadgpgsignature1></downloadgpgsignature1>
   <downloadgpgfingerprint1></downloadgpgfingerprint1>
   <downloadpackagename1></downloadpackagename1>
   <downloadrepository1></downloadrepository1>
   <downloadname1></downloadname1>
   <downloadsize1>1439</downloadsize1>
  </content>
  ...
 </data>
</ocs>
```

[1] http://apps.owncloud.com/content/show.php/Music?content=166469
[2] http://apps.owncloud.com/content/show.php/Music?content=160485

**Comment by jancborchardt** [comment]
This was fixed with your recent change, right @karlitschek?

**Comment by karlitschek** [comment]
yes
