### ISSUE TITLE
Appstore shows update of wrong version

### ISSUE THREAD

**Issue by tflidd** [owncloud/appstore-issues#50]
Appstore shows update of the news app (7.1.2) for OC 8.1.6 although this version is only marked to be valid for OC 8.2 and OC 9.0.
See report: https://github.com/owncloud/news/issues/934

**Comment by ghost** [comment]
@tflidd Strange, the appstore is not offering news at all:

https://api.owncloud.com/v1/content/data?version=8x1x0x0&categories=920&approved=all

**Comment by tflidd** [comment]
I downloaded and installed the news app directly from https://github.com/owncloud/news/releases

Perhaps the update-checker of the app store just uses the app-name/id to check the latest version without considering the OC-version?

**Comment by ghost** [comment]
Seems now the appstore is offering 8.0.0 to 8.1.x users: https://api.owncloud.com/v1/content/data?version=8x1x0x0&categories=920&approved=all

I think its more related that the app has the "All version" configured at https://apps.owncloud.com/content/show.php/News?content=168040

**Comment by ghost** [comment]
@tflidd Not absolutely sure but it might be an issue in core: https://github.com/owncloud/core/issues/25782

**Comment by tflidd** [comment]
In the meantime, I switched to manual updates of apps as well. Would be great to get this fixed one day :D

**Comment by DeepDiver1975** [comment]
appstore is dead - long live the marketplace!
For suggestion please head over to https://github.com/owncloud/marketplace-issues/
