### ISSUE TITLE
galleryplus.csr

### ISSUE THREAD

**Issue by oparoz** [owncloud/appstore-issues#53]
-----BEGIN CERTIFICATE REQUEST-----
MIIEtzCCAp8CAQAwcjELMAkGA1UEBhMCQ0gxCzAJBgNVBAgMAlZEMRYwFAYDVQQH
DA1Nb250cHJldmV5cmVzMRswGQYDVQQKDBJpbnRlcmZhU3lzIHPDg8KgcmwxCzAJ
BgNVBAsMAklUMRQwEgYDVQQDDAtnYWxsZXJ5cGx1czCCAiIwDQYJKoZIhvcNAQEB
BQADggIPADCCAgoCggIBAKJOE+oqeg1BF1tfcWLye0hb0cfoflrevsSTT7V+spVC
rqwS223AJyIWrN8PgnRwmv1LYXNjTAmUPhGVdn455Hm7PRFWtX+rimfAF+Dp/Csb
uYvdaKTA6xsuAJNKbNPJyaMtcQ0KTwVAv16I8ll6mZiiYoWHZ0n1HnsF4yLKKoMF
CuzOUh9o4NB/lzfAzwJS+HW0sC9YyHnRGVoCVqm4YuNp/99PtO25JByzJn7+yiuI
LyE/evpUvk/y4mvTU78ozm478QbHhZqmeJiicc2NPp4ClxHA2zmoM9lmMv0fz8hM
BHPeaWHS/BXPLny+/0CSSzDd3iopYXjEfDOrkZsIWYh4mP/86bCLDqMGappAAL53
K8X56OxxaR1vIiHZKrSEIE/qnlYZpj3gY6JDZ5DwzFtNxWlvqOOe8HXsPpRlYQGm
zrBCWYbrMHgHm93Mfl5VHEuZMWHUX70Ha0IBSQXoqkrUu4UhpRx1uXS1oGbupUPm
YEzpLwWGVwdrZZz09s5S3h0roGCLK7h+2zVaSA/+lhe4JdzGRXvJJqIAohT1aUae
MeuYr3UNDNeAkK3xypS2OM9JFdwtmWirdBvmZixmfV/WTnHuM5Njudu1qh0G2S/3
haMeba+LwViCrL6XXMWhu/m4CwN0asxrcFWPGaCh/qwVkWTKQq/9oJiJLFoAMCVZ
AgMBAAGgADANBgkqhkiG9w0BAQsFAAOCAgEAPITtTnfYN8sEGIBt88v5w/n7zow3
oTckjlMRsXC/Apxg0Vq4RqQFaYhWyB4+jGW6l3PyD7cyBh5+R3Lw1YXOW7wWb6mB
mnN6SaWfVOXMeqRNdBL77HIvjymvDSro86lbnsFhkI1mNHL+WAR/H05mme3UUmz5
Em3lyPaVQaiCZWxcezZqFMug3ycyAH7/UMabDYbOKnFs0DsFjhMiK0e/O3TwCw02
fkE0xSMTkQpkOrJgbmawrn7epM5oTkuIygm0idCeKAZ9NMUgiczOVhnPyPHDYwZ+
e9CzjlXPOj9ThFbJVyRLioW7lByrBQoERpLjhPkPuXyDKa3leW5sGC14O0fTkQRS
RttIEc6z2xzpK4v4kt5k4J2hYkbe9GbERVAO3xekZZFPgi6kgbBv0dj2XaRrmjSY
RUyGSIgVwAX4TLuMCsIpBgt5Twf7MRU+PsUL3vKf3f5oLblXLZosm0+DbgHJk+N4
XralUtPWP2HBeYhuOs50AdFCY2S85Ps2Ik4hpu2aXtNO4cGrvJUHx/rKK48NkBTW
N04RQPkkzv7PltUMzgqSbHyiX7XIMtH2DZHA903ZYYWQZcDvwuyr8JiofDodJRhg
a3KAnukzU80E9svixOnacYv4REY7RJ2+x2JBvzpneGdGDJwV2LIghl+1Tugb1tjm
hAzZ9sWITvcVno8=
-----END CERTIFICATE REQUEST-----

**Comment by LukasReschke** [comment]
```
-----BEGIN CERTIFICATE-----
MIIFVDCCAzwCAhAGMA0GCSqGSIb3DQEBCwUAMG0xCzAJBgNVBAYTAlVTMQ8wDQYD
VQQIDAZCb3N0b24xFjAUBgNVBAoMDW93bkNsb3VkIEluYy4xNTAzBgNVBAMMLG93
bkNsb3VkIENvZGUgU2lnbmluZyBJbnRlcm1lZGlhdGUgQXV0aG9yaXR5MB4XDTE2
MDMyMTE1MDYyNVoXDTI2MDMxOTE1MDYyNVowcjELMAkGA1UEBhMCQ0gxCzAJBgNV
BAgMAlZEMRYwFAYDVQQHDA1Nb250cHJldmV5cmVzMRswGQYDVQQKDBJpbnRlcmZh
U3lzIHPDg8KgcmwxCzAJBgNVBAsMAklUMRQwEgYDVQQDDAtnYWxsZXJ5cGx1czCC
AiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAKJOE+oqeg1BF1tfcWLye0hb
0cfoflrevsSTT7V+spVCrqwS223AJyIWrN8PgnRwmv1LYXNjTAmUPhGVdn455Hm7
PRFWtX+rimfAF+Dp/CsbuYvdaKTA6xsuAJNKbNPJyaMtcQ0KTwVAv16I8ll6mZii
YoWHZ0n1HnsF4yLKKoMFCuzOUh9o4NB/lzfAzwJS+HW0sC9YyHnRGVoCVqm4YuNp
/99PtO25JByzJn7+yiuILyE/evpUvk/y4mvTU78ozm478QbHhZqmeJiicc2NPp4C
lxHA2zmoM9lmMv0fz8hMBHPeaWHS/BXPLny+/0CSSzDd3iopYXjEfDOrkZsIWYh4
mP/86bCLDqMGappAAL53K8X56OxxaR1vIiHZKrSEIE/qnlYZpj3gY6JDZ5DwzFtN
xWlvqOOe8HXsPpRlYQGmzrBCWYbrMHgHm93Mfl5VHEuZMWHUX70Ha0IBSQXoqkrU
u4UhpRx1uXS1oGbupUPmYEzpLwWGVwdrZZz09s5S3h0roGCLK7h+2zVaSA/+lhe4
JdzGRXvJJqIAohT1aUaeMeuYr3UNDNeAkK3xypS2OM9JFdwtmWirdBvmZixmfV/W
TnHuM5Njudu1qh0G2S/3haMeba+LwViCrL6XXMWhu/m4CwN0asxrcFWPGaCh/qwV
kWTKQq/9oJiJLFoAMCVZAgMBAAEwDQYJKoZIhvcNAQELBQADggIBABRHxKsqYScI
OJItL4dRR55UWIKnLGBjkdDG0eSXmfWWKCwY6SsqEZkkPLATrSmasBGGcE8YbgfW
Gv5uFxMGZ1sdXSzE8ELOa8m6vhzApd9krgc3cihOFVsLTF/L3ZegnEtey8gwonFx
lQPXvuqdS8GNCJjrY+ES6cSrtqfX7kiG5o8q62jCZdbyV56+TRrJ9rmYE4mv8oe4
A4gIWUZGXOQ1YTWfevz0QKsn6zMb2Q6drWn9smWdhOFBPEEbFszECbnHykFRwsz0
IFBLwXPp0bcCpE8AinYpNWmbAynr0VV7yLqu0BSschCwjEsGP9ntpz66NpXcDxAN
0acuDejEBbcS+5H9Akwo7KpYrXOBbNZFxUMCSQ3gU+3F/PNQmaZ/flRBDN4YoNYl
3tRw98fyVf53u9TmzgKkgbsShQngmLpZZBCIOAeN/gnK9oDdbeJxpyl0NUfu4Zj6
b4C1b/Hn68Ou9nN/vQpdkt6oJn2aXkGx1mtRlJUnN24vZgzmJ3fWDSQUHSoE/oRB
ZKJeAcJ4JNu8a25ctIKnT89Vr9idX1dxBfGb6FcD5up+w9HyJWFE2YTknde3PFa8
IS9U46Q/NSREzBpB2lV6G3xVSM3kV7eRCkLd9zSJcS707AsgpnUPupv6tJS3vkZS
XQMoV8lPT1XvrDbjbzfMY4x4BA9FpV3w
-----END CERTIFICATE-----
```
