### ISSUE TITLE
files_antivirus.csr

### ISSUE THREAD

**Issue by VicDeo** [owncloud/appstore-issues#54]
-----BEGIN CERTIFICATE REQUEST-----
MIICXzCCAUcCAQAwGjEYMBYGA1UEAwwPZmlsZXNfYW50aXZpcnVzMIIBIjANBgkq
hkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArAyR5IZMhb/LR/CCPdJ+Vs82HmrNCwBx
/1+qS1p8pmBu1FgbNz535I2ub0sfNLl2q21onmmkRr1mfuXNQrQmXvlwPCbhvIqb
bUVOwAK4m8/RjD4FMn0+kfKsJqYQrAzrbn2GLYU/dgMDSFk0f7RtOTjlXPN46Neb
haMIDpfxl6ujRfUAvylrb3Ff9osGrK1dH+XrwvEvzjt1XOcYwE9/ZYFye/fZMgX7
P8dFfzm09H8ETtTchUQ4s5vb5ckQ2w1J9Or6OT+ZnUUCf3Td6AYjAP6SpxujuZ35
OA2Jvn9mve1JJmx23JRelXfdaKTv1xXYnJS1qzplgvp89z6cB6cUyQIDAQABoAAw
DQYJKoZIhvcNAQEFBQADggEBAHXRl3o+puHYou2D2NSgYAUYLnwRRF+SVmsT0hzs
L4ZEoFnkQRJCPagEvmUYepzzSIIq8KylSZBCL42Ghnt0pX1XDu/yYzaTF6gXaUUk
6ru5Bl5ca6XpNTo6ljdalg6doRTP85V5xkuV6ZVP/DHad2x+FCHKlNL6XROBWHCj
7PdYSA3E+tibsc0Ei3FWIdHQr1fLZV3eSU18WtQFpu5daTrdwxgpAR9+k1/oNXLz
zlrQTUpCctFyLlPJLn14JuGlN709wpHBTGOF8YN9SC0Sbxw2ouzzAL2zX6AZg1Ip
LKWpxglySfeTwC65JkyN6anC3eLbDiBeM8LjZ8dG8M1OLg0=
-----END CERTIFICATE REQUEST-----

**Comment by LukasReschke** [comment]
```
-----BEGIN CERTIFICATE-----
MIID/DCCAeQCAhAFMA0GCSqGSIb3DQEBCwUAMG0xCzAJBgNVBAYTAlVTMQ8wDQYD
VQQIDAZCb3N0b24xFjAUBgNVBAoMDW93bkNsb3VkIEluYy4xNTAzBgNVBAMMLG93
bkNsb3VkIENvZGUgU2lnbmluZyBJbnRlcm1lZGlhdGUgQXV0aG9yaXR5MB4XDTE2
MDMyMTE1MDUwMFoXDTI2MDMxOTE1MDUwMFowGjEYMBYGA1UEAwwPZmlsZXNfYW50
aXZpcnVzMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArAyR5IZMhb/L
R/CCPdJ+Vs82HmrNCwBx/1+qS1p8pmBu1FgbNz535I2ub0sfNLl2q21onmmkRr1m
fuXNQrQmXvlwPCbhvIqbbUVOwAK4m8/RjD4FMn0+kfKsJqYQrAzrbn2GLYU/dgMD
SFk0f7RtOTjlXPN46NebhaMIDpfxl6ujRfUAvylrb3Ff9osGrK1dH+XrwvEvzjt1
XOcYwE9/ZYFye/fZMgX7P8dFfzm09H8ETtTchUQ4s5vb5ckQ2w1J9Or6OT+ZnUUC
f3Td6AYjAP6SpxujuZ35OA2Jvn9mve1JJmx23JRelXfdaKTv1xXYnJS1qzplgvp8
9z6cB6cUyQIDAQABMA0GCSqGSIb3DQEBCwUAA4ICAQAN2TuPzA4kPNKghx6qqMt1
wPO5ZbmGCYI7fB9JOj9ZpLa1lDbmTWOgQPQYKgkpvUsQ/ZU0oAlVZc0oPIoDG526
syZkeVUP6E+CVMbxKhYVt9AOm4fQ7U3AygNMUyW8JpAO679ueNQSaWSWJQ5pXOKr
0uQYCv77dEj5yOA4SA1sH3Lc9/E51p8YaI4xTw3duYtMpt0WAgsVoyGM69uHiz+q
oufE+B6pSaE4c5DUKPoHYxEabhnGCUwBfMAXZ6mDh3Phw8tx4s05P542tcesR92H
171N2IDU/+u7SzfJ/K3akAIYpeF+6eXeRhGNIR7KlNXEboaq4BpLCJDS5z6oidiZ
KbwVDM6cXjVbdOtgA1qn8vG48ZtQHJECKBipZ+bz/gxj8et3x/Hxl11Linkey/Ij
D7y2OLM9ODkBe3fFnFe//juLpp+6+h2ciBmm7VCpghILICuauHcG6eVQzriOW3zF
y4oW5iLQ+skKv/7L1IY75OPjDhSFik2U7IxP6EA1ETXGn6XdMfXpJZQmI5RR+rrN
GyxFGC0eMk2pD2CsX17oIwQcTYU+sMNFAdUE4dxKrD3uAlzEDweebh8m7/MiX0Co
Nq5soKpR9TaYWW4uUANcAVTzrjHJYBSgBsyJiJ1enauZDRHxHnpJtw20kJfspOmc
SLMdzoeBdqcuINdZs2ihiA==
-----END CERTIFICATE-----
```
