### ISSUE TITLE
Uploading archive does not overwrite old archive

### ISSUE THREAD

**Issue by BernhardPosselt** [owncloud/appstore-issues#55]
Steps to reproduce:
- Go to News app
- Click edit
- Next
- In the upload section hit browse, upload https://github.com/owncloud/news/releases/download/8.0.0/news.tar.gz
- Hit the checkbox and save
- Go back to the app section and hit download
- Downloaded archive is not the one that was uploaded

**Comment by MorrisJobke** [comment]
I also experienced this with the music app: owncloud/music#488

cc @LukasReschke @karlitschek

**Comment by MorrisJobke** [comment]
Also a reupload didn't solved the issue. I simply provided a link to the github releases instead, which then works fine.

**Comment by BernhardPosselt** [comment]
Same here

**Comment by karlitschek** [comment]
O.K. I think there was indeed a permission problem on the new server. Sorry guys.
Can you try again?

**Comment by MorrisJobke** [comment]
Tested and works now 👍
