### ISSUE TITLE
Download counter seems to be way off

### ISSUE THREAD

**Issue by oparoz** [owncloud/appstore-issues#57]
I might be very wrong about how users get their app, but somehow I don't see admins manually download or use scripts to grab releases off Github when an app is available from the appstore and can be installed with one click.

So, if I'm not wrong it might be worth investigating the huge difference of downloads I'm seeing when comparing the app store with the numbers provided by Github (not including clones). It gives devs the wrong impression about how poorly their app is doing.

An example with ShareLinks:
- App store: 625
- Github: 18137 <- That's the tarball Given to the app store

Known problem? A solution in sight?

@karlitschek @LukasReschke

**Comment by karlitschek** [comment]
Strange.
One thing that I discovered in the app store years ago is that people run automatic download scripts to increase the number of downloads of their app. They want to be on top of the high score list ;-)

So the app store has some protection against that. Downloads are not counted if they constantly come from the same IP.  I need to check if this anti spam download protection code counts the downloads via the OCS API correctly. Something to check.

Good finding :-)

**Comment by oparoz** [comment]
> One thing that I discovered in the app store years ago is that people run automatic download scripts to increase the number of downloads of their app. They want to be on top of the high score list ;-)

Interesting. Seems a bit pointless to do in an app store featuring free apps though, especially since apps don't come with ads...yet.

I've found one way the number increases outside of the app store. That's when people run scripts or use a VM, but ShareLinks is not in any VM I know of, so I'm still puzzled by the huge difference.

**Comment by DeepDiver1975** [comment]
appstore is dead - long live the marketplace!
For suggestion please head over to https://github.com/owncloud/marketplace-issues/
