### ISSUE TITLE
Make life easier for reviewers

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/appstore-issues#6]
To make it easier to review apps, I would suggest to add a Filter for »Unreviewed« apps.

Further enhancement to make clear what the reviews are actually for:
- Split the »Approved« dropdown in 2: Design-Approval and Security-Approval
- Filters for »Design unreviewed« und »Security unreviewed«

cc @LukasReschke @MorrisJobke @karlitschek

**Comment by LukasReschke** [comment]
+1

**Comment by DeepDiver1975** [comment]
appstore is dead - long live the marketplace!
For suggestion please head over to https://github.com/owncloud/marketplace-issues/
