### ISSUE TITLE
Mail Template not found

### ISSUE THREAD

**Issue by jochenwezel** [owncloud/appstore-issues#60]
![image](https://cloud.githubusercontent.com/assets/3033827/14816451/430d7428-0bb1-11e6-85ab-d1ea4413ebb0.png)
using OwnCloud server v9.0.1

all other templates are available, but the password-forgotten template is somehow missing

Hints: I was quickly updating all my mail templates with updated signatures and when I remember correctly, the template was there on the very first time; I didn't changed this template, but changed all other templates. And now it's missing.
Maybe there is a delete command before updating/recreating a template file on disk when saving the other templates but pointing to the wrong file (e.g. new user template accidentially deletes password forgotten mail template?!)

**Comment by jochenwezel** [comment]
Update: my last hint doesn't apply: I've installed a 2nd owncloud server simultaneously and the password forgotten mail template doesn't exist there, too. So, it's a general issue of owncloud server 9.0.1

**Comment by ghost** [comment]
@jochenwezel This is the issue tracker of apps.owncloud.com where issues with the appstore itself can be reported. The repository for the Mail Template Editor can be found here: https://github.com/owncloud/templateeditor/issues

**Comment by jochenwezel** [comment]
thanks for the hint! I recreated the ticket there and so, this one can be closed.
