### ISSUE TITLE
"apps.owncloud.org" has incorrect forwarding

### ISSUE THREAD

**Issue by aspdye** [owncloud/appstore-issues#63]
For a long time, "apps.owncloud.org" was forwarding to "apps.owncloud.com". Now, it is forwarding to "mailman.owncloud.org" 😁 However, I think the usage of ".com" is weird (because it is more of the .org - as i discussed in https://github.com/owncloud/core/issues/18201)  - but that is another discussion.

The Inc. guys are saying "apps.owncloud.ORG" by themself:
"apps.owncloud.org" is referenced in this graphic (https://owncloud.com/lp/community-or-enterprise/) so I think this should be fixed 😉

cc @jospoortvliet

**Comment by aspdye** [comment]
Correction: Does only Happen with https:// :grin:

**Comment by danimo** [comment]
Should this forward anywhere anyway?

**Comment by aspdye** [comment]
It is an given Link here: https://owncloud.com/lp/community-or-enterprise/
