### ISSUE TITLE
404 on some KB entries

### ISSUE THREAD

**Issue by ghost** [owncloud/appstore-issues#64]
From time to time it happens that existing KB entries in the appstore shown in:

https://apps.owncloud.com/kb

are throwing a 404 when opening. An example is:

https://apps.owncloud.com/kb/Are+private+and%2For+confidential+messages+supported+on+Owncloud+calaner/?kbid=5896

**Comment by DeepDiver1975** [comment]
I fear there is not much we can do ...

![05466030](https://cloud.githubusercontent.com/assets/1005065/20211170/8fe53716-a7fd-11e6-91ae-05fe7207b92f.jpg)

**Comment by ghost** [comment]
Yeah, then we might just close this. IMHO the people shouldn't use the KB at apps.owncloud.com in general...
