### ISSUE TITLE
request the signed certificate

### ISSUE THREAD

**Issue by Tracywang890810** [owncloud/appstore-issues#68]
-----BEGIN CERTIFICATE REQUEST-----
MIICWDCCAUACAQAwEzERMA8GA1UEAwwIY29udGFjdHMwggEiMA0GCSqGSIb3DQEB
AQUAA4IBDwAwggEKAoIBAQC7FgnN0Hycbz1fx3+2MTxzq27wQfUZob/wQv87RmsX
kOq757O0VlVIZ2iL7DMXGCesoQA/jC5BECVFXdJsibnaZPJMHSFEo666STLbkdzf
YgCB3uOez3QETkdY+9fW0JyhypdWt3744ewxlC98Zi17caxwVbgCgBnN4S2eOohB
gxuYJjJfbOIOteRwF1+ozJAwvB8fjUqm0XZ5ZvZhdDCyVzJo1bXn0mQdb44uMvZf
j26PGZecHe4j5fx+S6eZHM8sBkayK3aQG/j2+zzimb0XRG0IMmnQqHcypKWr1Zwp
yUZEwkiVIGBMQ4v2aLLKtGek1Rw2q2RPXjJFp8IpW1AnAgMBAAGgADANBgkqhkiG
9w0BAQsFAAOCAQEAAJMHu4DRdAMgWja9qRMvyo6sjfsKdgM6gme/3bnDiRc6Pquk
foNMEiAxikawJKj38CO/Nhk3ylBShjd3PWLhliwP09WOndecpITye3vETXXquD/1
Mqn6yt+GRTxNiejssdRd5zKoQusdP3+TayarDP8p0hdel/SJDrDGRf8E8cJDnQdu
VQ21eVd/rF/C8pDnErP66QO6umKVz9CwxPpMSdk6pYyFtiDbyt+88rKgwULyvjZG
qedQU5M6xJo2I64OoKUx27iZgop3gLPRQO8HAf8YdAbd3RdV6NlFwnWeZhbeh8lV
xAhwt2cVVacFIsZRT1wif0+vj48SIwJ3JIeEyQ==
-----END CERTIFICATE REQUEST-----

**Comment by danimo** [comment]
Please provide a link to the application that you plan to sign.

**Comment by Tracywang890810** [comment]
First, thanks for you reply.
I just want to konw what I can do to resign the code after I have change some codes, such as .htaccess.

**Comment by ghost** [comment]
Please use central...

**Comment by danimo** [comment]
Looking at your profile, I see what you are trying to do: You altered an application, and now you want the signing error to go away. However, we cannot issue a general purpose certificate to you for signing. All you can do currently in this case is disable code signing checks, contribute your changes back or for the application and request a certificate for that.

We should provide the option for users to roll out their own certificate next to ours so they can sign local changes, but that's not there yet.
