### ISSUE TITLE
Allow app devs to deactivate comments and knowledge base

### ISSUE THREAD

**Issue by BernhardPosselt** [owncloud/appstore-issues#7]
Both dupcliate the issue tracker on github and are spammed with bug reports

**Comment by vgezer** [comment]
What about this https://github.com/owncloud/appstore-issues/issues/1?

**Comment by ghost** [comment]
Still valid... People don't get it that the comments of an app shouldn't be used to report issues with the app itself.

I think this should go along with deactivating the KB as discussed in https://github.com/owncloud/appstore-issues/issues/23

The current state of the KB and comments is a no-go in my opinion. Really wonder why no one currently cares about this as #1 and #23 are still open.

**Comment by DeepDiver1975** [comment]
appstore is dead - long live the marketplace!
For suggestion please head over to https://github.com/owncloud/marketplace-issues/
