### ISSUE TITLE
Shorten.csr

### ISSUE THREAD

**Issue by Fmstrrat** [owncloud/appstore-issues#70]
CSR for the Shorten app:
https://apps.owncloud.com/content/show.php/Shorten?content=168591

[shorten.csr.txt](https://github.com/owncloud/appstore-issues/files/426741/shorten.csr.txt)

**Comment by Fmstrrat** [comment]
@danimo I'd love to push out a new, signed release asap :)
Thank you so much

**Comment by Fmstrrat** [comment]
@danimo Any news on this? :)

**Comment by danimo** [comment]
Nice try :)

> Subject: CN=core

This needs to be the name of your app.

**Comment by DeepDiver1975** [comment]
@Fmstrrat
