### ISSUE TITLE
duo.csr

### ISSUE THREAD

**Issue by elie195** [owncloud/appstore-issues#71]
-----BEGIN CERTIFICATE REQUEST-----
MIICUzCCATsCAQAwDjEMMAoGA1UEAwwDZHVvMIIBIjANBgkqhkiG9w0BAQEFAAOC
AQ8AMIIBCgKCAQEA3KIms6C+HtUHQrOSEubV48+8aFiysb/JrmFSQvqMPOTFSfsO
J6//eD1ylb70YnyWGQ3j6F5cy3ohwpsF3ohcYi1LaMQsJ+qRMVIwOktHYf3o0vzg
YopZFvxzJm9ffUz/+7qqauHYMKVDh/SjeEBsol6VvO7M4qivQ4qKFDgTCDgX1IV8
jnyEUcL7e72W4HIJN8TNpw8dbe6INlHq7771oECZkXvqUvlLgeE+SQCbE0mtGcYd
QX2XbsMlrJ1Z4zmQBtOTP8hTGcEMQZw2osFRd3RLvzQQlJacR26DTHQ+HnSXQohr
PBlQZWlb7Wh8cog5sCaHHylPLWgkw17eHRh0qwIDAQABoAAwDQYJKoZIhvcNAQEL
BQADggEBAKkt5vE/rp09pJbsSc5mZ7mEjdMRBdmM8vHdR81fY1BRHNOKXZolPVK2
ZKl17ZObN9l7RAm7G3j67WiSoGRfSsZzsJgL3c6czYkPw6BGzE/mlynGWJRBM79b
KI1/AhW4piUVwqFbAX3qK4CuXsRSAirQzwz3bkSmTeQVMqihdfhW7jK48LThkBax
nCWCclNtwM0uYNtA6ryMxbXObq11RjGCGswsRWRodRU/n3Clut4aRsEO5E7JKGtV
cIFU0U/Sct5SwT4Rf6SaFVuxwQLCqO6lHuHgSz0btizmR+yKmG5IwEukKGkLudOy
dRoZjImU4tUJCOSVnJ6g0YDT9gH/9AA=
-----END CERTIFICATE REQUEST-----

**Comment by danimo** [comment]
Which app in the app store is this for? Please provide more details.

**Comment by ghost** [comment]
https://apps.owncloud.com/content/show.php/Duo+Two-Factor+Authentication?content=174747

i think (developer name and filename is matching).

**Comment by elie195** [comment]
Yes, https://apps.owncloud.com/content/show.php/Duo+Two-Factor+Authentication?content=174747 is the app. Thank you for your time.

**Comment by DeepDiver1975** [comment]
@elie195 Thanks a lot for your work on this! What will happen if somebody enables your app on an ownCloud instance where the patch is no deployed? I assume it will badly fall apart - right?

We have to protect our users from crashing their systems - I guess I need to ask you to remove/disable the app from the appstore until the patches are merged and deployed.

Thanks a lot!

**Comment by PVince81** [comment]
@elie195 mind raising a ticket for the notifications issue so we can get it sorted out ? (feel free to ping me on it). Thanks :smile:

**Comment by elie195** [comment]
@DeepDiver1975 beat me to it! Wow you guys are great!

@DeepDiver1975 regarding your comment, yes, that's correct. I will add a check so that the app only works on instances where the $provider->getCSP() function returns something. In the meantime, I couldn't find a way to disable the app on the appstore so I deleted it.

**Comment by elie195** [comment]
Could I re-open this request please? I just submitted the app back to the appstore following the merge of my pull request (thanks!): https://apps.owncloud.com/content/show.php/Duo+Two-Factor+Authentication?content=174748

**Comment by PVince81** [comment]
So if I understand correctly, the app would work out of the box with the unreleased 9.2 but needs hacks on 9.1. Not sure, I guess signing it in the future for 9.2 would be ok but not for 9.1.

@DeepDiver1975 @danimo

**Comment by elie195** [comment]
Correct, as stated in the appstore and in the appinfo XML, the app requires ownCloud 9.2. Since I was able to select v9.2 for the app in the appstore, I thought it would be supported. 

So in the meantime are you suggesting to close this request and resubmit it once 9.2 is released to the general public? Thanks

**Comment by PVince81** [comment]
@elie195 since 9.2 is still pre-alpha, there is no guarantee yet that the API is stable. If someone else wanted to add an additional method, they'd be allowed to do it on IProvider2 too (no IProvider3 at this point). So there is no guarantee that your app continues to work.

However once we reach beta (feature freeze), we should stop changing public APIs, so that's the best moment to have your app officially available. At this time, you can either ping us again here or reopen the ticket (so it doesn't matter if you close it or keep it open) :smile:

**Comment by elie195** [comment]
Thanks for the explanation, that makes sense. Is it ok to leave the app in the appstore in the meantime "unofficially"/unsigned?

**Comment by PVince81** [comment]
@elie195 yes, it should be fine. However, IIRC, only people who have enabled the "experimental apps" flag in their ownCloud will see it inside ownCloud. And when installing it, it will have a label "experimental" which is ok if users understand that.

**Comment by DeepDiver1975** [comment]
@elie195 

```
-----BEGIN CERTIFICATE-----
MIID8DCCAdgCAhAOMA0GCSqGSIb3DQEBCwUAMG0xCzAJBgNVBAYTAlVTMQ8wDQYD
VQQIDAZCb3N0b24xFjAUBgNVBAoMDW93bkNsb3VkIEluYy4xNTAzBgNVBAMMLG93
bkNsb3VkIENvZGUgU2lnbmluZyBJbnRlcm1lZGlhdGUgQXV0aG9yaXR5MB4XDTE2
MTExMTA5NTI1NloXDTI2MTEwOTA5NTI1NlowDjEMMAoGA1UEAwwDZHVvMIIBIjAN
BgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA3KIms6C+HtUHQrOSEubV48+8aFiy
sb/JrmFSQvqMPOTFSfsOJ6//eD1ylb70YnyWGQ3j6F5cy3ohwpsF3ohcYi1LaMQs
J+qRMVIwOktHYf3o0vzgYopZFvxzJm9ffUz/+7qqauHYMKVDh/SjeEBsol6VvO7M
4qivQ4qKFDgTCDgX1IV8jnyEUcL7e72W4HIJN8TNpw8dbe6INlHq7771oECZkXvq
UvlLgeE+SQCbE0mtGcYdQX2XbsMlrJ1Z4zmQBtOTP8hTGcEMQZw2osFRd3RLvzQQ
lJacR26DTHQ+HnSXQohrPBlQZWlb7Wh8cog5sCaHHylPLWgkw17eHRh0qwIDAQAB
MA0GCSqGSIb3DQEBCwUAA4ICAQA4iEraVTXFZxuzXq5WeSGAIYB1rFLvETvCEyEB
TAnMaFBcPh6G0mdfJgas7x5Hoohe8XwTSe5maWxNDKsobBj1rUbcvHuRlLZ6aJ/D
ggESqafsa8rBc5ixkjpfwl9ldKM6yja2AQWZ44VOz/UbHJe7oJ18ayPalXl+92fa
VVIt8LsJhhvf1ZphZ3O/43xiqZANY4NBIp8J6bL9t7DevXVl+en1HtR2k/0XIafs
kklEGUIV7RE93VOWsX0B/i+eCwG72ubtMIxdy7WQ/TzHl6FhJR7BISQu1HxCSur1
gwIaDRFK/IPtpoZx++/fzvGq9XES53yBwmOkD3kUKb/nnqdg1WtGsaAaOa8dSh4I
m5jvL5/0E6FUS8f5RH1FBZtwCtW3jTP/es8PS15lilMFzCJQOUYPRODs34IzCTLt
aZpvwiQSh5+CKURm4oJ7JXUsjqvx6O9UxS6Od5Gn6YaPI2GJaEg+r08kLPeM5mh8
7+GxYh4uHHdly04Q2WUiQfNV9PS9nwyyI7DsZWxn4PAoMY4ANoU4FnwbGed3GD/F
KY3EWtMrwzDsUdeGws/23hXQF8hwKdEuHUd3UEM4OHkubZDhm14xFSUBuqDBETeY
RVmumIla2jRxJDwAwXdO8l4kh6tY0nEUBmT5/Cer2/g2gW4z5E31vSPsGOc+NzHh
+YWpFA==
-----END CERTIFICATE-----
```
