### ISSUE TITLE
audioplayer.csr

### ISSUE THREAD

**Issue by Rello** [owncloud/appstore-issues#72]
http://apps.owncloud.com/content/show.php?content=174738
https://github.com/Rello/audioplayer

-----BEGIN CERTIFICATE REQUEST-----
MIICWzCCAUMCAQAwFjEUMBIGA1UEAwwLYXVkaW9wbGF5ZXIwggEiMA0GCSqGSIb3
DQEBAQUAA4IBDwAwggEKAoIBAQCe7h/D9C5jmeOQkSvjo7sL/IbBlPgtNoFZQyVk
/LY/pLgEqs5+9p1e2xZXYQwBSUpkWJ7K5LPo8AY4NQvsa/lH0J4Y8OiL9W6fEZ4J
aDXVk+EKeujaFGtPWMIJTVfyJeONtMH0/YE9zCa0YA1Z7VocV9bna7XkfGyjCm4i
M1pXGJujgn9dDs1sRv+uK655FueR9QJvvL/MhczQ+6JWIJkf5m/HEBVq3DHTS6Rg
Nv9DkaHkYPs2eLeZox9Eom6EF/CKF9B8ZsARTkcp9pk3aQ9Vxsa1V5MtNsFyBKx7
d3n0Z+Ddly/7AeQ7bOWpZ9M2w9s4BfeuvmpZRwozI27cYncDAgMBAAGgADANBgkq
hkiG9w0BAQsFAAOCAQEAiFh6bgXy3jQMUCZocz/vSGGP6zPzjQU+uAeBcJBpL/qy
b3Xgr1dNWFnQy27B/wCH9A9NESdvvW6Ftq/h4dvkgbNWd/4uLJ+Sq1123D/l6NNS
k8IA4UvieWXdsNDdle7NK6MCatJ79rFzrSBQswzRZ3RjFCUrTMPs3VlM1LbkK4do
p0nzY6b2X8o4dv8DK9eTzImNL7wcMxlS1v8WVcTReBA9848oWw5XxQiF/4T5Uz4N
7FlT7SzbAFQXLPt2tkfqanjMBF9mVnc4CpLu09Nhs7xqlMEmrhnyzH1EfYx7mk2t
AZHqibkiSpUQxFRCYEuVPAXucg3ZC3tLyuged2D/KQ==
-----END CERTIFICATE REQUEST-----

**Comment by Rello** [comment]
in included the key into my profile for verification in the app-store because I am still waiting the renaming there...
http://apps.owncloud.com/usermanager/gpg.php?username=z000ao8q

**Comment by Rello** [comment]
@danimo ;-)

**Comment by danimo** [comment]
```
-----BEGIN CERTIFICATE-----
MIID+DCCAeACAhANMA0GCSqGSIb3DQEBCwUAMG0xCzAJBgNVBAYTAlVTMQ8wDQYD
VQQIDAZCb3N0b24xFjAUBgNVBAoMDW93bkNsb3VkIEluYy4xNTAzBgNVBAMMLG93
bkNsb3VkIENvZGUgU2lnbmluZyBJbnRlcm1lZGlhdGUgQXV0aG9yaXR5MB4XDTE2
MDkwNTEzMzQxN1oXDTI2MDkwMzEzMzQxN1owFjEUMBIGA1UEAwwLYXVkaW9wbGF5
ZXIwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCe7h/D9C5jmeOQkSvj
o7sL/IbBlPgtNoFZQyVk/LY/pLgEqs5+9p1e2xZXYQwBSUpkWJ7K5LPo8AY4NQvs
a/lH0J4Y8OiL9W6fEZ4JaDXVk+EKeujaFGtPWMIJTVfyJeONtMH0/YE9zCa0YA1Z
7VocV9bna7XkfGyjCm4iM1pXGJujgn9dDs1sRv+uK655FueR9QJvvL/MhczQ+6JW
IJkf5m/HEBVq3DHTS6RgNv9DkaHkYPs2eLeZox9Eom6EF/CKF9B8ZsARTkcp9pk3
aQ9Vxsa1V5MtNsFyBKx7d3n0Z+Ddly/7AeQ7bOWpZ9M2w9s4BfeuvmpZRwozI27c
YncDAgMBAAEwDQYJKoZIhvcNAQELBQADggIBAF2bsHRT7ql6zBhs6MBQvItY8Vte
hbAUcbfmIG3mRngozU7L1XYzhN54YF10RL6EA5UCDpKR1VLrMLoNJVYKddb34deT
opAeFKyfgVo4ZF97omWMvbacAEoVbEd/MMPBat/pM4dX/3L+yon9ZbiwlJYQj3VT
bVIaJ+dLWTta/0zNGCXRvvbDagNW++5oWipAjtFQxPtJ7vH84f/+YkwYEhMlA3aU
ck2KFAQjlYAZ4bCnoutNtFlGp1vTxSEvY3vzMYp/HBvoitbpxCPY6bxG7nyzaWD/
54pFRURW/7l4VBUid2mjN1GyFi+JPjW4ecU6N7sqK55MhsF4TYSO7HC+FSMvbNGn
mpiVVU9WqL/W90lc1YX58GtpNbrtnNjSDJEU1dUf8Fn6VX0kQ/mDCZJ5lbWmI54m
a/iVayPh8dFvdVmVx+R+0/mNWTNijROHYBMD9aGn1DYrotP5PApAhlSTq1YMD0Ec
a+en4hp3fUyvhp3e8/y+qMSekE2CvE2e1JxOab5ByLwB5Zhpe5bF4t2bVWr6Qfdc
O9t2kJYnYTM+7lx/9XCVZSkuVE0DYLXCRTL+j0PI14MIj8c+WwSjYPxhQ1j1x03J
gqlsnSiy7i6dVTNnD1rXd4f0zUnf0y5/0LBaz3IIRzHRRo5UH6H3bW4BEdUDglTm
+/YBxMaUdS8YLE1b
-----END CERTIFICATE-----
```
