### ISSUE TITLE
certificate request

### ISSUE THREAD

**Issue by MichaelGottschlich** [owncloud/appstore-issues#73]
-----BEGIN CERTIFICATE REQUEST-----
MIICXDCCAUQCAQAwFzEVMBMGA1UEAwwMUkRTX1Rhc2tMaXN0MIIBIjANBgkqhkiG
9w0BAQEFAAOCAQ8AMIIBCgKCAQEArMUPdz/mp8s0oP+0/FZXtBwdgwgFIQLVQiSO
lFUKpn2rQJ/GmwxfXEAw0S1dYXEnmKuYI4SSqnPTY0C3dwc4eyHNwUrFCs8lczNQ
jqVTRQJK8K6cCLYQ+ZMDNDPCNEjqDn7CDOM9O2LBCn7+rsNrRpqdD55kt6+s91QG
7vFbZUhkwQ2uj/D4YOX0lpZIM8toyaCI2x0Yzw/TRjAXvuqXxg2yw0CzBVL59LVw
zGPnwCxpm8QKPeLWGR/9bclCtmoe8SNOydTVMdVLnHAWqrZcLIw4DQ5oq8+HUbPz
y1y1gPfpdwrv4/mVGouIjhKGrv9ol4syYOAK3OQwBBtqhZWBlwIDAQABoAAwDQYJ
KoZIhvcNAQEFBQADggEBAGS65DCOSHfL0yyguyj3P74Lv6QskwWobhh+ROZnFkjM
khTkpCyqFylaN8b75nzPROz9ofzn101ut5kCLzYui+MjF24vGAMKKaBf4MJ0P/MY
rjtHPuY/MHv3Hu8l0rqKZPz7Y3JKK5iroCNSBFgFRGa5Uoyr1RgBHpY7CmowO/KA
BJR9jH6yBwWHbNmkX+omJgXnNUJlIGTA2+rGLvpILrKLoVK1GJhR0QwWidnIqUOR
+CjCKtLa0VGSB42mxLEyXmmTFaf0llEMOviFaPQft6LZZ8IAJVYxQocFROaAB+6G
JRsTpTwCsnF9Vpi86dF51pKezK0e1uhAGlBGvfJXKGI=
-----END CERTIFICATE REQUEST-----

**Comment by ghost** [comment]
@MichaelGottschlich As you have no repositories linked / used in your profile the reference to the app you're trying to sign is missing.

This here is missing as well:

> and configure your GitHub account to show your mail address in your profile
> https://doc.owncloud.org/server/9.1/developer_manual/app/code_signing.html#how-to-get-your-app-signed

**Comment by DeepDiver1975** [comment]
no response -> close
