### ISSUE TITLE
CSR Request

### ISSUE THREAD

**Issue by jserra85** [owncloud/appstore-issues#74]
-----BEGIN CERTIFICATE REQUEST-----
MIICVjCCAT4CAQAwETEPMA0GA1UEAwwGc2Fjb3duMIIBIjANBgkqhkiG9w0BAQEF
AAOCAQ8AMIIBCgKCAQEA34grgKjL7gzK+0vOmdvMXGkZE36oi8nvr6FkrurlFnt/
G1Ns46D/7/tAsX9udMjQQ1clJNoEl5JlAQYFOffEsAcaWxpQj4ndZqTXD042HADT
fDiUz6PvFqvNLvBXPqYtumBhUE6d+B06kvxdOIYjdcHq7UfVZorQdqbeGKKizBWN
LvA2GpqFa2ehklWSfuctTPJVtrY35Ccd2iZC5YTr867iFnRSjpmHQ9+6NQEFffx1
loU6grgPsJJuG+NykbuixsCavWH0g4VhNGOA+3RNFxNorOfb000YcDWVmwYC+3PL
vYsCvyf/7ovheEaaXnyPjhVXUx+aU0DwpMaV6w5+SQIDAQABoAAwDQYJKoZIhvcN
AQELBQADggEBAIdghVtGIzXQGAdOl1ltXM1/PHCGTVv0DAJ2ozTamL0GOEWT7nze
wJRhcLz5JR5p+SizRZlsUiLbh2H/0XKWt3JAgoE7pQkjGAF3hULvcS27kKtBUvMD
6sP0UrULXowHnACAwKX4PeM3g4hT2UtbHhjVR7p4uBU5DyrkTB4thZ2An5uv6iyC
nWoKMn+CYtinFtSVHnecMVMsk+V+uTF9zstaikjSlGkzgNCQlNvJfuLwsMFOl+MU
TX6rEzKJPAAqSsr7+jKmCxLZIule9QMLgEGbgyXNX/WHz9ZhXO3pnwN0/eLr2LCM
qlx5NUF8duNXzWkOBQbHLzCfc/rgQSKDQRw=
-----END CERTIFICATE REQUEST-----

**Comment by ghost** [comment]
@jserra85 As you have no repositories linked / used in your profile the reference to the app you're trying to sign is missing.

This here is missing as well:

> and configure your GitHub account to show your mail address in your profile
> https://doc.owncloud.org/server/9.1/developer_manual/app/code_signing.html#how-to-get-your-app-signed

**Comment by DeepDiver1975** [comment]
no response -> close
