### ISSUE TITLE
Remove LibreOffice Online app from appstore

### ISSUE THREAD

**Issue by ghost** [owncloud/appstore-issues#75]
As seen in the comments of the page at https://apps.owncloud.com/content/show.php/LibreOffice+Online?content=174455 people are still trying to install that app.

However the readme of the github repos clearly says:

> This repository is obsolete, please use upstream RichDocuments application.
> https://github.com/COMU/libreonline-owncloud/blob/master/README.md

I think it might make sense to remove that app from the appstore to prevent confusion and issues with two different apps.

cc @farukuzun

**Comment by ghost** [comment]
Forgot to cc @PVince81 and @DeepDiver1975 . Might also have an opinion about this.

**Comment by DeepDiver1975** [comment]
done - thanks for letting us know!
