### ISSUE TITLE
Added file

### ISSUE THREAD

**Issue by dalenoe** [owncloud/appstore-issues#77]
I've had to add my own php script into the same directory that owncloud resides in. The script is a haproxy check. Anyway, How can I sign the file and/or core again to stop receiving that warning message?

**Comment by DeepDiver1975** [comment]
> that warning message?

you are talking about the integrity check I guess?

**Comment by dalenoe** [comment]
Yes. The integrity check. Don't really want to disable it

**Comment by DeepDiver1975** [comment]
let's continue in here https://github.com/owncloud/core/issues/27102
