### ISSUE TITLE
NetKnights / privacyIDEA CSR

### ISSUE THREAD

**Issue by cornelinux** [owncloud/appstore-issues#78]
Is this the way to go?

<pre>
-----BEGIN CERTIFICATE REQUEST-----
MIICZTCCAU0CAQAwIDEeMBwGA1UEAwwVdHdvZmFjdG9yX3ByaXZhY3lpZGVhMIIB
IjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApMTK0b/U0kGLs3F5El1kKpEX
8MBobnyn6WczJNIJwGUKH45gV8G0rM586aXX9mApeZFvew8az5SJDvJcCg4O/u3Y
5AsJhYxEsQ8Lcpy/PYHSYmFbEMa645fmlh+MDrfS2XtB6VjpleX9aolb65pYegc3
5XgslvXm0zF0XAZt7rjZNoK4alpl5TVLi8aho9kN/dXEdKkemn4OH9n+UCCdHI9d
V3BHYWbHh7OCeTGrzYG+dzxjEwHh+kByZsot6UhSc5ixn+mYprMcm/ohpEAvMnC4
II/hubzkGevrVB1gzGCRfGWBZ733aGWIzkUTCLwdYFBb2wyM4aIYysAXwWuavQID
AQABoAAwDQYJKoZIhvcNAQELBQADggEBAEFCduP1bhYqi2FF9m53f8EicjFvroi4
RAYmYik6ZdrfaDNxB97HuaJdnRzTrM8lFVeTfrIR2VbLxy0qm1+1CyZbG+0HzsNi
vg+HYaY3y2++eMPmdduLXyvr7AZXWgMicBi4HTsq4jqUKSxMx8fSq3vbegBm40se
M9Mh22yxUdaRGiaK2Bj/3IMImTiB9+eDRC1dxVX6mBg+/+NPi3ioXkK/uiePpCx1
MHy15YBmMfg8ggYqF7VlOk/uZ2HoqYjZac/LwSnVTiEkoHwXe40txzwcBBzME2oG
Ow8AWKLsw5f36kL4B43wQ8/2PfYx9HX5r5+oBlRZm8CyabxV4ZLGWN8=
-----END CERTIFICATE REQUEST-----

</pre>

**Comment by PVince81** [comment]
@DeepDiver1975

**Comment by DeepDiver1975** [comment]
here we go

````
-----BEGIN CERTIFICATE-----
MIIEAjCCAeoCAhASMA0GCSqGSIb3DQEBCwUAMG0xCzAJBgNVBAYTAlVTMQ8wDQYD
VQQIDAZCb3N0b24xFjAUBgNVBAoMDW93bkNsb3VkIEluYy4xNTAzBgNVBAMMLG93
bkNsb3VkIENvZGUgU2lnbmluZyBJbnRlcm1lZGlhdGUgQXV0aG9yaXR5MB4XDTE3
MDMyMjEwMzYyM1oXDTI3MDMyMDEwMzYyM1owIDEeMBwGA1UEAwwVdHdvZmFjdG9y
X3ByaXZhY3lpZGVhMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApMTK
0b/U0kGLs3F5El1kKpEX8MBobnyn6WczJNIJwGUKH45gV8G0rM586aXX9mApeZFv
ew8az5SJDvJcCg4O/u3Y5AsJhYxEsQ8Lcpy/PYHSYmFbEMa645fmlh+MDrfS2XtB
6VjpleX9aolb65pYegc35XgslvXm0zF0XAZt7rjZNoK4alpl5TVLi8aho9kN/dXE
dKkemn4OH9n+UCCdHI9dV3BHYWbHh7OCeTGrzYG+dzxjEwHh+kByZsot6UhSc5ix
n+mYprMcm/ohpEAvMnC4II/hubzkGevrVB1gzGCRfGWBZ733aGWIzkUTCLwdYFBb
2wyM4aIYysAXwWuavQIDAQABMA0GCSqGSIb3DQEBCwUAA4ICAQBZg0D2FpzM9J72
mVumB0CwBWL7A6r8GzyGdkhir7GiGVMHNk+Bf+SA/mcpVoK2BPuhSQRKqJQLM/Ub
qCqTPcu8JxOtquXN+K0Th3JeMZRuqNe9o/SK+EbD758qYQgwRuZbXetRfEXLgBLE
E2HIJUbJ1vSze6phJPZ1rO3Np3FsyE5JsHhyXSfzGRJHqTuLn+NDpfF5oIKuOyK1
l72eLjUHmDteL5Y4BKmTefHB+5ra2sOGkrTQi9LLlAqt6v9lGCi+mHGNhXPMvgFF
kPDAivVU4guhb7Qd5Y+2avWOkltn0d4zkm3e5fNxDbQx4jNJ6QE2+3YF9Ob9GA8N
F7LHns3GLaY0HbQhnpGMlMReiylvmNBZAj7UoC1IwETb30yQZABeoLFcW6fSyygF
IbxDpNw02FeSfCmzZ+7wycIERl/9WJaDAteEjhsvmS/O9AOInsVhQ04r+fB6v8jQ
O4PQlvIOxTQq4QzvK9M5QWIz9ns/FLvH4Anj9OVHYb8XkAyZr3JIHDWNpRqXry6d
GPl15+bWDv9E4LKcb3b/aGyY7vMjcHCV2NfgcwgzF7AOGWaFtx8HM4J2Nah18AW5
L4A3rZ5MBtzv5NiEw+ZRcolHWBQWaHjkTkwm7Bmt6tIQPRU96M4rN4qEY8Sr4iHk
L1WOP0h0/CcwBaz2U3CizmF/g37gVA==
-----END CERTIFICATE-----

**Comment by cornelinux** [comment]
thx!
