### ISSUE TITLE
Read information from info.xml rather than forcing the app dev to reenter everything for an app

### ISSUE THREAD

**Issue by BernhardPosselt** [owncloud/appstore-issues#8]
DRY

**Comment by oparoz** [comment]
:+1:

**Comment by karlitschek** [comment]
Good idea. But low priority from my point of view. Let's fix all the other problems first. :-)

**Comment by janklostermann** [comment]
I would not see it as low priority, if you give it a bigger scope: 
making `info.xml` or another file(s) in `appinfo` like `Readme.md` the well documented central point of information about apps, where all others get it from:
- http://apps.owncloud.com
- the in-owncloud appstore
- ...

Additionally it should include links to documentation (user, admin, developer), code, issues, etc. to make it as easy as possible to use and contribute. Thus much more support from the community can be gathered as access gets much easier. (e.g. adding a documentation link to the description of an app is a huge hurdle, as by searching around I can find quite a few descriptions in various places, but not the one that I see in the app store and wanted to improve. Earlier or later I give up and the chance for improvement is lost.)
Having everything required adequately filled out (e.g. working links to documentation - at least prepared stubs for later improvement, but easy to find) could then be an acceptance criteria for the release of an app, that could be included into the automated testsuite and this way improve the overall quality of the owncloud platform. Furthermore it would become easier to maintain as one would not need to understand all the complicated distribution of information in different places to get everything right.

Note: with some support of the owners/stakeholders and a coder I would offer to get this up and running (developing the new scheme, document it and merging the existing into it).

**Comment by DeepDiver1975** [comment]
fixed with marketplace.owncloud.com
