### ISSUE TITLE
user_ldap.csr

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/appstore-issues#90]
-----BEGIN CERTIFICATE REQUEST-----
MIICWTCCAUECAQAwFDESMBAGA1UEAwwJdXNlcl9sZGFwMIIBIjANBgkqhkiG9w0B
AQEFAAOCAQ8AMIIBCgKCAQEAvmx/3S7Yb70ZBoa0vpP5d4Mlppic2PwN02hsCLYp
qanYbinzOhU1W/utHK+74Q3dtWirF7yIiG2Mv8HnwOczIxO8x7GW+kCVKvvIVNP+
wxCXmZyrAuVyWFtcpdwxhUZTR1mt9rMHxu6TEFaAOoNGYO+xTZlB2dlWXL9iw/vT
iceRdPEA9VO8fBGs2LHIVWM6trLqGAVpXE4gy7SxLR/qoYEq3XhRS9HMZjdLY4p/
ghM2AmDNpenRV80mp4f5roRSZz0HGTzxUJX/0cK2SvfikvI/oeqhW7HfVBt0Xl8l
/SWKMbKbbdENbsBbbRryI+SXK4+JPq4EInLQhoWCK+KU6wIDAQABoAAwDQYJKoZI
hvcNAQELBQADggEBAJY1KxDdctB/sM/F35ff9oz492VPDOG2sbOk4/D4wAy2iuUo
g8U+xFlx4SzE1v3PzIQz9yV2GVFj4n9OoX7TFvdHeGvIZhS9MBCzZ7QE0nPDKZBy
H1CsQerPdaqTXDFU+NvDIcpjJg+L4KGmN7GKZnUegh83PdbGhzxeR41ymGpj1KdD
Qa7s3mOLAm5rzOeJsdqk//QbrZljb9I+cjMNiq7Cw2weOxf8KS14mc3KUG2B4NTS
KvTMDV2U8KESFEjaEkFTx3G55+C456tyb8BhitYdwD9j8+ZUQeGUDRpqJgWXuMcx
JUH83qKKQYsWeqGoxIbIr4xefADgCnrJNcCvgGs=
-----END CERTIFICATE REQUEST-----

**Comment by DeepDiver1975** [comment]
```
-----BEGIN CERTIFICATE-----
MIID9jCCAd4CAhAdMA0GCSqGSIb3DQEBCwUAMG0xCzAJBgNVBAYTAlVTMQ8wDQYD
VQQIDAZCb3N0b24xFjAUBgNVBAoMDW93bkNsb3VkIEluYy4xNTAzBgNVBAMMLG93
bkNsb3VkIENvZGUgU2lnbmluZyBJbnRlcm1lZGlhdGUgQXV0aG9yaXR5MB4XDTE3
MDUwODA3MTg1MFoXDTI3MDUwNjA3MTg1MFowFDESMBAGA1UEAwwJdXNlcl9sZGFw
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvmx/3S7Yb70ZBoa0vpP5
d4Mlppic2PwN02hsCLYpqanYbinzOhU1W/utHK+74Q3dtWirF7yIiG2Mv8HnwOcz
IxO8x7GW+kCVKvvIVNP+wxCXmZyrAuVyWFtcpdwxhUZTR1mt9rMHxu6TEFaAOoNG
YO+xTZlB2dlWXL9iw/vTiceRdPEA9VO8fBGs2LHIVWM6trLqGAVpXE4gy7SxLR/q
oYEq3XhRS9HMZjdLY4p/ghM2AmDNpenRV80mp4f5roRSZz0HGTzxUJX/0cK2Svfi
kvI/oeqhW7HfVBt0Xl8l/SWKMbKbbdENbsBbbRryI+SXK4+JPq4EInLQhoWCK+KU
6wIDAQABMA0GCSqGSIb3DQEBCwUAA4ICAQB/H6DniGJhCgposnE283YywZwC/03O
ljbOG10c5tP/qd34wdjV6Hpe6mE26NbA61mDRP1rLq31/dXwd9zCV0yzEwFA9uPM
J72qrPhquHHSjrpd/jpp8SNngr1GoD9Tt6G8AE+4iUfovIBugDj0gESuNaHyP/wt
lswZsjGmT8eqP68HZB4+PtpYZ1xeYu8Tx/nKI4ThlKoFNhJ/JbqArFsENwlG1ka9
8ZnwfyP8GE8GVaKkCxUjs3gbmYT88vtgTGZZe/75/y14zdilEtdgXURTWCSF1BG9
6qM28RdZY6zfS581NMN5OmxTFLY501k1LN6HNRJ0GfoRvhCHeqr3UnSibb9+7rws
EMI6+iX/U215UsJBE09EMV5TW2VTywuRBq4AFXx8OK4WF/kTpXBg3nABII+gNhMW
8vdFFy3cs07an17g8e1dM9hEPCeVgeNfQon90t6QbefeHcb4E2GLF0qA37HMO/Pt
XN1fvevVqhe0+BPBeCU0ywNVbv975k0/ufIBno9CONWw1t9KvZni7p/jX7vV3B6O
rniQinyLGr3ZkwA5NqSOfuSjd+rm5kJ4Eqr2eihzsoiJTBMw2+xuO13bsZi/xTx4
cYr3llHA3uP3O80MRkfrIrMcf2MbO6IO7eUEDInAc+w2AwkZQybLrmfXWZHtijPF
zdRhNuSiUCjekQ==
-----END CERTIFICATE-----
