### ISSUE TITLE
diagnostics code signing

### ISSUE THREAD

**Issue by mrow4a** [owncloud/appstore-issues#98]
App: https://github.com/owncloud/diagnostics

-----BEGIN CERTIFICATE REQUEST-----
MIIEWzCCAkMCAQAwFjEUMBIGA1UEAwwLZGlhZ25vc3RpY3MwggIiMA0GCSqGSIb3
DQEBAQUAA4ICDwAwggIKAoICAQCqnRh/IfOp9tBW0Ylvp4K9XHc/BCVMvQj7aDhL
lzln++bH6esfZ1sAgSwb6Maz9OiiLc/XEGfeVtgiTN7b0LsRQi6pt+IMqOHEWR0u
cmslAOlm93hNwH6CtmCdbBpIhdTVxWwezyefq24crZed1YFoAs80duDSOhEALm4y
3t+tbpCw/au6D7vuZHfxiJihw9G5QKIuuFeiFTmX7KAlzEwMvaqlvTDmS54auWv5
iWCQEzKjgxMUOdMTtWI1hSVNIBW/McOkUee9O9wtws1Pyr3b/A8fop7OCzM7g8k+
iGf0LR4eGdH/US6NdlmpBA16Wk/Ofidn+NiZF9eTnjD1LZMSdTuo37n2PwsQbJBJ
7uSzjEXqYa7UNv/RjSpI6GpyNtPKLOsGKtatfMaSfLHam/7qkUSgUBRiOng3HK+K
OxEmqDrIfJKEUt66KDuTgex+kF4osKcp8/O6FQmnW0qJHG5NZELyHb62wpsVzVbo
Zx+trJhZcHzPIz5Gcoekbe+1iO/Mn0KQdSNjeT9UyQ/uG76AglNnYflkWe1Z8/Nk
4wfkC3MvHY7+IfNgP57lhOcwZRockozPVg/O0xYk84mjguKYZL9IZ5TTbeIIFPwX
O6vCPTYw2BrkqAHSXpUENezD/+RzLWmDCTNeJOgc/jEKP+NSgUD7vMOHrRVxX+Nj
l4vNKwIDAQABoAAwDQYJKoZIhvcNAQELBQADggIBAC0b5BPL1acqrusrlCtMfMi0
mnDagiqidAzOQiAaOH72LTUoWoCQFfjFVpGG/jB6H6QNG12+fZlPccCS3RfazFiG
p+N+MyykypJBAgIQfn9zOkb4+PeAo3rB5bA9gPhSOerZR/N7dRBhC+Nr0TWa5UBj
idr7gXb9HmPwxthWDJ8uKJfo0b7plDWFrtnB8GsupRAaPGnplcn2PfmlNOSxMZrA
StTCzowQNzWJN+ulMzNVSasF37heZTM5AdXyQdrSd+24xvIMmpmxKK3p70lGliM1
xzMefkHqsR2Shz2jbGb7bX8HdkRTqugRelxKHiP5d8Ry7P5ja3K34jwPe8Lnfw3u
U9+yHk3cJ7ghMEWW+8Jbu/er+6B+y3azOsxqAKlOYtfAO3/tazqf13Xr1S0SZ/rD
PSmYqZZtcEAFY9hR/VADYPlFZ1j2L69B2/5ThlLgD3n8YRVTyViyy8T6voHlI1XZ
C/kXRBGBI2n4kMk3Oo8D3GFiskMxTIaUrkNKbrTgLexS9bhQKOpT1BniTUi4LRnc
/69cJdrSFQzykCf0xOLnieEn3/yuwKs+vCnHz3GQTNCuiTGUjKeOLTtz+I6UwXe8
7i3W5qAgayMqv7z5JwceM4z4MysHfWBDsmjHLOko9XS/8fWutppTRx5EFJdyRmZ8
CHwp2S+osFomMCNCeXFA
-----END CERTIFICATE REQUEST-----

**Comment by mrow4a** [comment]
@DeepDiver1975

**Comment by DeepDiver1975** [comment]
```
-----BEGIN CERTIFICATE-----
MIIE+DCCAuACAhA5MA0GCSqGSIb3DQEBCwUAMG0xCzAJBgNVBAYTAlVTMQ8wDQYD
VQQIDAZCb3N0b24xFjAUBgNVBAoMDW93bkNsb3VkIEluYy4xNTAzBgNVBAMMLG93
bkNsb3VkIENvZGUgU2lnbmluZyBJbnRlcm1lZGlhdGUgQXV0aG9yaXR5MB4XDTE3
MDcyODA4MTMyOFoXDTI3MDcyNjA4MTMyOFowFjEUMBIGA1UEAwwLZGlhZ25vc3Rp
Y3MwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQCqnRh/IfOp9tBW0Ylv
p4K9XHc/BCVMvQj7aDhLlzln++bH6esfZ1sAgSwb6Maz9OiiLc/XEGfeVtgiTN7b
0LsRQi6pt+IMqOHEWR0ucmslAOlm93hNwH6CtmCdbBpIhdTVxWwezyefq24crZed
1YFoAs80duDSOhEALm4y3t+tbpCw/au6D7vuZHfxiJihw9G5QKIuuFeiFTmX7KAl
zEwMvaqlvTDmS54auWv5iWCQEzKjgxMUOdMTtWI1hSVNIBW/McOkUee9O9wtws1P
yr3b/A8fop7OCzM7g8k+iGf0LR4eGdH/US6NdlmpBA16Wk/Ofidn+NiZF9eTnjD1
LZMSdTuo37n2PwsQbJBJ7uSzjEXqYa7UNv/RjSpI6GpyNtPKLOsGKtatfMaSfLHa
m/7qkUSgUBRiOng3HK+KOxEmqDrIfJKEUt66KDuTgex+kF4osKcp8/O6FQmnW0qJ
HG5NZELyHb62wpsVzVboZx+trJhZcHzPIz5Gcoekbe+1iO/Mn0KQdSNjeT9UyQ/u
G76AglNnYflkWe1Z8/Nk4wfkC3MvHY7+IfNgP57lhOcwZRockozPVg/O0xYk84mj
guKYZL9IZ5TTbeIIFPwXO6vCPTYw2BrkqAHSXpUENezD/+RzLWmDCTNeJOgc/jEK
P+NSgUD7vMOHrRVxX+Njl4vNKwIDAQABMA0GCSqGSIb3DQEBCwUAA4ICAQCYckaX
2I+DxcisTUjYlcEHgH5NwkQRm8UM3qOkMes+SK3WeQ/CpgGPcsYm0JkE5Ws8nChj
PxgqobZNs/kKiMD1APaS+ndGx9vdrSC1KJj8YVAzIPHsNe2kz7o79cu/l3C/aLhE
yj5V1rmH9JKFSzXworS7zGSXRpxlfTP1WKNy6bEdU810l+jOUDmdIEHaxCdfWJh4
PzggjSQGZ6l+GbYy1D8fNlGxlSaGdcXzE6qe7L2VWZXUZFjsVOxWOm4N5AiE2xlL
70GK6kDj0SsYrvjHCVl/0wy/fqm4mpXcnylP+xMSc2Sg++rBSYD1FZI1seGd7snP
UgjQNLkt6jKQiNpH7XSSi8WZwEtMRQhwUE6ErdaPGdteQCEkHPhNGRPd1dxDHmWK
ClInkRcnIwbGb+JILmNPxTLZDFdamAxYaxXDAkBrxa46aDkXtIhDOMdNXEQuAofu
WZY+I7rSJr9u1oi9eKx5C3+gl9R5srFF5lRvSeiF6eV/D+BVUQTuX/4KcJulHmRs
25O9TASTAJ3dtiorkasXxjBkL+v7T/HrXKwdraeacxoQea+DQMxnU+ngMwZjcOSX
DUL4HBgbrA24ynz4p1Hf1UZOAXrj2+Lco9Hxk8P8gLFUi97BEta6XrVTKbbcX4a7
pvKo6tZSEAQx4KdN2uG2Gwk0nZUXFpTaAPKu3Q==
-----END CERTIFICATE-----
```
