### ISSUE TITLE
Files paperhive code signing

### ISSUE THREAD

**Issue by mrow4a** [owncloud/appstore-issues#99]
App: https://github.com/owncloud/files_paperhive

**Comment by DeepDiver1975** [comment]
csr is wrong ...

![bildschirmfoto von 2017-07-28 10-12-01](https://user-images.githubusercontent.com/1005065/28708646-454a3156-737d-11e7-99d8-03609c107d32.png)

**Comment by DeepDiver1975** [comment]
> -----BEGIN PRIVATE KEY-----

lol

**Comment by mrow4a** [comment]
Will generate new one

**Comment by mrow4a** [comment]
-----BEGIN CERTIFICATE REQUEST-----
MIIEXzCCAkcCAQAwGjEYMBYGA1UEAwwPZmlsZXNfcGFwZXJoaXZlMIICIjANBgkq
hkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA9oRSoE4MwYrDlMhJSEma/6+sALSgGSpS
bBn5g2LlQomghLwRSumGTHoAnHapTiBm5UnOKtwCAhZO8xOVdDCwa02WPiG2VCMW
Y7SjSmxgmoZXcdfLKWdtM91RVko0tXEiJM7kdOOCWiKrN22HhyYkqDsta/qUmNyD
DccHffgOVXiSID05sUJ4DeJ9zlALCC1i785OP8f4Ql6PFetFwkZ6W9u5d6SiBzok
EjOwonDoMjzUggzAne7LBf2xwImmaJOVBaTalGuQJvjILccaIAXQGtwOAaX/s3Z1
PE9FGgm9/BDmnHfOcoe/SLeMREXZzO1UGzdMYI3ytoyZDtwsR43zXuTYDodIM2Gs
Cdpe2FGqtIviCQ5N4QGVkfQk1SRUeMEYjLH9HTbj5a97A0EPRiiyAsBFBRWLsN58
ckTftkxj+cGZ+JuIA76o6iQpxv8lwPHsKcl+hpkl6J0twH+WpmZOembmgFm+m4ay
H8+TphTqxNTVwDSehxA2abhSRX0K52KpE1OWPD6WDHQHMP+fbxZT1TpOLluctsA0
iAou6hj/GkXz7vIG5Jpg9J58u/5kANK8xjNNC0RKg+CgkFipOdzrXZRAMxV4A7Ld
cS4yp0aWjG1ki7/XFPWuZ4xih56ykFQzrSKqYPoGg7iH29kkB+IMI6VxuCyoIeVl
S76J0P7lE58CAwEAAaAAMA0GCSqGSIb3DQEBCwUAA4ICAQDKL0P6tvj6ojOacYOT
GHjvnAaW3eCU7QWkWtD0rGvL8t5azjDdW7Bbg6aVu4acEN1A/t/I69xQJjOz2wo8
iUobKST/ELQS9WOHcDI9+DAdqByN5ivc1SHZ4Z5hj95lYEjzfEAhsR3TC55TTsuR
xHyehlYIAl1FMbeIHNEilzizlb54Wg0uPcPAxnqMl2wyCyza1ymr3shO5aS3cevB
Z+BpQoRiLw3S0hNgHCClZThoFvjFXypVBzwxbH+22HIN7iwnoIbFruJ17X070P7l
P23R18M1S9m2zzgpc8SsTI3MfUcUWwQ1iwHAC2owdd/jXAIRSPSaApr1F/WfyLvT
DwPnU7FssdczzQF3uKsT+S5yTPhHZN06cFr7xxmJ4khp7rnzJ6Fb+js8hOzM/pie
QC0N1kk6y77/FsH+uYoSk0126slJ3T7bn0p5BPpHBX965lGYELDgShsDcu/EPk4H
+MO76634HJi194F5LtXnzs1J6x6S1tIYHPfZLZ4d4MgadjsrxTOwYoMniY6ssn/U
TWg6qIPqXivinSZmoDnusjOedG+A1LWwxHKFtejdAqV9dCFjpkodoPDqe9oxjdhb
P6GaRxCEgZLtySVcQEdp6Twp6cEH6ItdAf4Dy4GZ2XZ2SVRMOVmX/Rpy4l3JXPIA
0uZlJUGdHtGDkruy/bhHPsImrQ==
-----END CERTIFICATE REQUEST-----

**Comment by DeepDiver1975** [comment]
```
-----BEGIN CERTIFICATE-----
MIIE/DCCAuQCAhA6MA0GCSqGSIb3DQEBCwUAMG0xCzAJBgNVBAYTAlVTMQ8wDQYD
VQQIDAZCb3N0b24xFjAUBgNVBAoMDW93bkNsb3VkIEluYy4xNTAzBgNVBAMMLG93
bkNsb3VkIENvZGUgU2lnbmluZyBJbnRlcm1lZGlhdGUgQXV0aG9yaXR5MB4XDTE3
MDcyODExMjAyNloXDTI3MDcyNjExMjAyNlowGjEYMBYGA1UEAwwPZmlsZXNfcGFw
ZXJoaXZlMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA9oRSoE4MwYrD
lMhJSEma/6+sALSgGSpSbBn5g2LlQomghLwRSumGTHoAnHapTiBm5UnOKtwCAhZO
8xOVdDCwa02WPiG2VCMWY7SjSmxgmoZXcdfLKWdtM91RVko0tXEiJM7kdOOCWiKr
N22HhyYkqDsta/qUmNyDDccHffgOVXiSID05sUJ4DeJ9zlALCC1i785OP8f4Ql6P
FetFwkZ6W9u5d6SiBzokEjOwonDoMjzUggzAne7LBf2xwImmaJOVBaTalGuQJvjI
LccaIAXQGtwOAaX/s3Z1PE9FGgm9/BDmnHfOcoe/SLeMREXZzO1UGzdMYI3ytoyZ
DtwsR43zXuTYDodIM2GsCdpe2FGqtIviCQ5N4QGVkfQk1SRUeMEYjLH9HTbj5a97
A0EPRiiyAsBFBRWLsN58ckTftkxj+cGZ+JuIA76o6iQpxv8lwPHsKcl+hpkl6J0t
wH+WpmZOembmgFm+m4ayH8+TphTqxNTVwDSehxA2abhSRX0K52KpE1OWPD6WDHQH
MP+fbxZT1TpOLluctsA0iAou6hj/GkXz7vIG5Jpg9J58u/5kANK8xjNNC0RKg+Cg
kFipOdzrXZRAMxV4A7LdcS4yp0aWjG1ki7/XFPWuZ4xih56ykFQzrSKqYPoGg7iH
29kkB+IMI6VxuCyoIeVlS76J0P7lE58CAwEAATANBgkqhkiG9w0BAQsFAAOCAgEA
l3JabGGUQS/uyocZ81fEIPu42j1JMLj3KMfbkbyCiF3iFhnRCyIXk4vQPkStfbDU
SGzh22yZGaz3MzFE++9HBhwwgy25ljsw9yvP/drvlZrDVbGsUB236KOQRzn2GCB7
M8dMBACNX/8D/UTlIEGRupCFZ8aHxjVUgV5e2uT77xlAp8uD5yBKo2O61AwL+PEg
O9dPQ4JkIZKrItoHRAQxiKcUoBJdt2K2PJcM7CtpFHXV2oK8JGl6PylG474zNTE6
Z+dqxIuCCnfR8ETGLmUEJ6xZXOr2I7ZhAAQWNTLBngGTDtnBmuiwirZXT3pibyCo
J2HC1LPeAnYsYZ5xf+8B30nCJzAcEcaqAVXeaJdy90xTezKyIV4JXDHQyCuNJJpO
Y4d7p7m4IVEKbavpf9yerCl7QpGaG9gq3Yzixx76V/i1E4X9Ocya8nbar4xeCyys
Dh5A5XQUD/H/dmcF9rYuIcjKfS2x5td3fi4z/FsuH7Lwv9LsA0RY23LfzIxXyBN3
wTfPn8eN/QQESofaX6UXkFHMnh9UEo6h1xhVcoOJ8nfesR4eLD2kCanbisBAsYbu
S7skjdC1ZqiOmvtUBvp7TnoA3p4ssDI0gZWqNRqgW1nOtJj4NlO/RuaXZou+HgZS
h0n+nn9gczMfE0OcZwgz5i+kGxJ2/K9Q4ZrXZbnllVo=
-----END CERTIFICATE-----
```
